import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Content,PageHeader } from '@/components/shell';
import { ReportResults } from '@/components/report-results';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { canEditReportDefinition,canViewReportDefinition,executeReport,reportRegistry,validateReportConfiguration } from '@/lib/reporting';
import { archiveReportAction,duplicateReportAction } from '../actions';
export const dynamic='force-dynamic';
export default async function SavedReportPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{group?:string}>}){const actor=await currentUser(),id=Number((await params).id),query=await searchParams;if(!Number.isSafeInteger(id)||id<1)notFound();const report=await prisma.reportDefinition.findUnique({where:{id},include:{owner:true}});if(!report||!canViewReportDefinition(actor,report))notFound();const config=validateReportConfiguration(report.reportType,report.configuration);const result=await executeReport(prisma,actor,report.reportType,config);const editable=canEditReportDefinition(actor,report);return <Content><PageHeader eyebrow={`${reportRegistry[report.reportType].label} · ${report.visibility}`} title={report.name} description={report.description??'Saved report re-run against current CRM data.'} action={<div className="flex gap-2"><Link className="btn-secondary" href="/reports">Reports</Link>{editable&&<Link className="btn-primary" href={`/reports/new?reportId=${report.id}`}>Edit</Link>}</div>}/><p className="mb-4 text-sm text-slate-600">Owned by {report.owner.firstName} {report.owner.lastName} · updated {report.updatedAt.toISOString().slice(0,16).replace('T',' ')} UTC</p><ReportResults result={result} config={config} groupKey={query.group}/><div className="mt-5 flex gap-3">{editable&&<form action={duplicateReportAction}><input type="hidden" name="reportId" value={report.id}/><button className="btn-secondary">Duplicate as personal</button></form>}{editable&&<form action={archiveReportAction}><input type="hidden" name="reportId" value={report.id}/><button className="btn-secondary">Archive</button></form>}</div></Content>}
