import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Content, PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { can } from '@/lib/authorization';
import { prisma } from '@/lib/prisma';
import { forecastForRep, forecastForTeam, quarters } from '@/lib/forecast';
import { attentionIssues, attentionLabels, getForecastAttention, type AttentionIssue } from '@/lib/forecast-attention';
import { getSettings } from '@/lib/configuration';
import { formatCurrency } from '@/lib/display-format';
import { activeSalesRepWhere } from '@/lib/assignment-eligibility';
export const dynamic = 'force-dynamic';
type Filters = { userId?: string; year?: string; quarter?: string; currencyCode?: string; issue?:string; attentionPage?:string; attention?:string };
export default async function ForecastPage({ searchParams }: { searchParams: Promise<Filters> }) {
  const actor = await currentUser();
  if (!can(actor, 'sales.read')) notFound();
  const f = await searchParams;
  const [users, currencies] = await Promise.all([
    prisma.user.findMany({ where: { ...activeSalesRepWhere(), ...(actor.role === 'SALES' ? { id: actor.id } : {}) }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }),
    prisma.currency.findMany({ where: { active: true }, orderBy: { code: 'asc' } }),
  ]);
  const today = new Intl.DateTimeFormat('en-US', { timeZone: 'America/New_York', year: 'numeric', month: 'numeric' }).formatToParts(new Date());
  const part = (kind: string) => Number(today.find(item => item.type === kind)?.value);
  const year = Number.isInteger(Number(f.year)) && Number(f.year) >= 2000 && Number(f.year) <= 2100 ? Number(f.year) : part('year');
  const quarter = quarters.includes(f.quarter as never) ? f.quarter as 'Q1'|'Q2'|'Q3'|'Q4' : quarters[Math.floor((part('month') - 1) / 3)];
  const currencyCode = currencies.some(c => c.code === f.currencyCode) ? f.currencyCode! : 'USD';
  const userId = actor.role === 'SALES' ? actor.id : f.userId==='team'||!f.userId ? null : users.some(user => user.id === Number(f.userId)) ? Number(f.userId) : null;
  const rep = users.find(user => user.id === userId);
  const metrics = userId ? await forecastForRep(prisma, actor, { userId, year, quarter, currencyCode }) : actor.role!=='SALES' ? await forecastForTeam(prisma,actor,{users,year,quarter,currencyCode}) : null;
  const settings=await getSettings(prisma);
  const issue=attentionIssues.includes(f.issue as AttentionIssue)?f.issue as AttentionIssue:undefined;
  const allAttention=f.attention==='1'&&!f.year&&!f.quarter;
  const attention=await getForecastAttention(prisma,actor,{days:settings.COMMIT_FOLLOW_UP_DAYS,filters:{currencyCode,...(allAttention?{}:{year,quarter}),ownerId:userId??undefined,issue,page:Number(f.attentionPage)||1},mode:'DETAIL'});
  const attentionHref=(page:number)=>`/reports/forecast?${new URLSearchParams({userId:userId===null?'team':String(userId),...(allAttention?{attention:'1'}:{year:String(year),quarter}),currencyCode,...(issue?{issue}:{}),attentionPage:String(page)})}`;
  const money = (value: string | null) => value === null ? 'No target set' : formatCurrency(Number(value), currencyCode);
  return <Content><PageHeader eyebrow="Reports" title="Quarterly Forecast" description="Current open Opportunities by expected close date. Values are shown in one currency." action={<Link href="/reports" className="btn-secondary">Reports</Link>}/>
    <form method="get" className="panel mb-5 grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5">{actor.role !== 'SALES' && <label className="label">Sales Rep<select className="field" name="userId" defaultValue={userId??'team'}><option value="team">Team</option>{users.map(user => <option key={user.id} value={user.id}>{user.firstName} {user.lastName}</option>)}</select></label>}<label className="label">Year<input className="field" name="year" type="number" min="2000" max="2100" defaultValue={year}/></label><label className="label">Quarter<select className="field" name="quarter" defaultValue={quarter}>{quarters.map(q => <option key={q}>{q}</option>)}</select></label><label className="label">Currency<select className="field" name="currencyCode" defaultValue={currencyCode}>{currencies.map(c => <option key={c.code}>{c.code}</option>)}</select></label><label className="label">Attention issue<select className="field" name="issue" defaultValue={issue??''}><option value="">All issues</option>{attentionIssues.map(value=><option key={value} value={value}>{attentionLabels[value]}</option>)}</select></label><div className="self-end"><button className="btn-primary">View forecast</button></div></form>
    {metrics ? <><p className="mb-2 text-sm text-slate-600">Pipeline includes Pipeline, Best Case, and Commit categories. Weighted Pipeline uses an Opportunity probability override when present; otherwise it uses stage probability. Coverage uses a positive, complete target.</p><p className="mb-4 text-sm text-slate-600">{rep?`${rep.firstName} ${rep.lastName}`:'Team'} · {year} {quarter} · {currencyCode}{'opportunityCount' in metrics?` · ${metrics.opportunityCount} open Opportunities`:''}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Quarterly Target',money(metrics.target)],['Pipeline',money(metrics.pipeline)],['Weighted Pipeline',money(metrics.weightedPipeline)],['Commit',money(metrics.commit)],['Best Case',money(metrics.bestCase)],['Pipeline Coverage',metrics.pipelineCoverage ? `${metrics.pipelineCoverage}x` : '—'],['Weighted Coverage',metrics.weightedCoverage ? `${metrics.weightedCoverage}x` : '—'],['Commit Coverage',metrics.commitCoverage ? `${metrics.commitCoverage}x` : '—']].map(([label,value]) => <div className="panel p-5" key={label}><div className="label">{label}</div><div className="mt-1 text-xl font-semibold tabular-nums">{value}</div></div>)}</div>{metrics.targetStatus !== 'SET' && <p className="mt-4 text-sm text-amber-800">{metrics.targetStatus==='PARTIAL_TARGET'?'Required Sales targets are missing':metrics.targetStatus==='NO_TARGET'?'No target set':'Target is zero'}; coverage is unavailable.</p>}{'reps' in metrics&&<section className="panel mt-5 overflow-x-auto"><h2 className="border-b p-4 font-semibold">Sales Rep Forecast</h2><table className="w-full text-sm"><thead><tr>{['Rep','Commit','Weighted Pipeline','Target','Gap to Commit','Gap to Weighted','Target status'].map(label=><th className="p-2 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{metrics.reps.map(row=>{const user=users.find(item=>item.id===row.userId);return <tr className="border-t" key={row.userId}><td className="p-2">{user?.firstName} {user?.lastName}</td><td className="p-2">{money(row.commit)}</td><td className="p-2">{money(row.weightedPipeline)}</td><td className="p-2">{money(row.target)}</td><td className="p-2">{row.commitGap===null?'—':money(row.commitGap)}</td><td className="p-2">{row.weightedGap===null?'—':money(row.weightedGap)}</td><td className="p-2">{row.targetStatus.replaceAll('_',' ')}</td></tr>})}</tbody></table></section>}</> : <div className="panel p-5">No sales rep is available.</div>}
    <section className="mt-6"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">Forecast Attention · {attention.total} Opportunities</h2><span className="text-sm text-slate-600">Commit follow-up: {settings.COMMIT_FOLLOW_UP_DAYS} days</span></div><p className="mb-3 text-sm text-slate-600">{allAttention?'All open Opportunities':'Selected-quarter close dates plus missing close dates'}. Only directly linked Opportunity Activities clear a stale Commit warning.</p><div className="mb-3 flex flex-wrap gap-3 text-sm">{attentionIssues.map(value=><span key={value}>{attentionLabels[value]}: <strong>{attention.countByIssue[value]}</strong></span>)}</div><div className="panel overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead><tr>{['Opportunity','Account','Issues','Close date','Value','Category'].map(label=><th className="p-3 text-left" key={label}>{label}</th>)}</tr></thead><tbody>{attention.rows.map(row=><tr className="border-t" key={row.id}><td className="p-3"><Link className="text-orange-800 underline" href={`/opportunities/${row.id}`}>{row.name}</Link></td><td className="p-3">{row.account}</td><td className="p-3">{row.issues.map(value=>attentionLabels[value]).join(', ')}</td><td className="p-3">{row.closeDate??'—'}</td><td className="p-3">{formatCurrency(Number(row.value),row.currencyCode)}</td><td className="p-3">{row.forecastCategory.replaceAll('_',' ')}</td></tr>)}</tbody></table>{!attention.rows.length&&<p className="p-4 text-sm text-slate-600">No matching attention items.</p>}</div>{attention.pages>1&&<nav className="mt-3 flex gap-4 text-sm">{attention.page>1&&<Link className="underline" href={attentionHref(attention.page-1)}>Previous</Link>}<span>Page {attention.page} of {attention.pages}</span>{attention.page<attention.pages&&<Link className="underline" href={attentionHref(attention.page+1)}>Next</Link>}</nav>}</section>
  </Content>;
}
