import * as XLSX from 'xlsx';
import type { expiringReport, ExpiringFilters } from './price-exception-expiration';
import { normalizeExpiration } from './price-exception-expiration';

type Result=Awaited<ReturnType<typeof expiringReport>>;
export function expiringWorkbook(report:Result,filters:ExpiringFilters,generatedBy:string,generatedAt=new Date()) {
  const book=XLSX.utils.book_new();
  const headers=['PE Number','Sales Rep','Account / Customer','Product / SKU','Status','Expiration Date','Days Until Expiration','Expiration State','MOQ / Tier Summary'];
  const meta=[['Generated',generatedAt],['Generated By',generatedBy],['Expiration Scope',normalizeExpiration(filters.expiration)],['Sales Rep Scope',filters.salesRep??'All permitted reps'],['Status Scope',filters.status??'ACTIVE'],['Total PE Count',report.count],[]];
  const rows=report.rows.map(row=>[row.code,row.rep,row.account,row.product?`${row.product.product??''} ${row.product.sku}`.trim():'',row.status,row.expirationDate,row.days,row.state,row.tiers]);
  const sheet=XLSX.utils.aoa_to_sheet([...meta,headers,...(rows.length?rows:[['No Price Exceptions match these filters.']])],{cellDates:true});
  sheet.B1.z='yyyy-mm-dd hh:mm';
  for(let index=0;index<rows.length;index++){const cell=sheet[`F${index+9}`];if(cell?.t==='d')cell.z='yyyy-mm-dd';}
  sheet['!cols']=[18,23,34,36,15,19,24,20,24].map(wch=>({wch}));
  sheet['!autofilter']={ref:`A8:I${Math.max(9,8+rows.length)}`};
  sheet['!freeze']={xSplit:0,ySplit:8};
  XLSX.utils.book_append_sheet(book,sheet,'Expiring Price Exceptions');
  return book;
}
