import { Prisma, PriceExceptionStatus, type PrismaClient } from '@prisma/client';
import { pageNumber } from './crm-validation';
import type { Actor } from './authorization';
import { scopedPriceExceptionWhere } from './price-exception-visibility';
export type PriceExceptionFilters={q?:string;status?:string;distributor?:string;varName?:string;endUser?:string;expiration?:string;unresolved?:string;salesRep?:string;page?:string};
const party=(raw:string|undefined,accountField:'distributorAccount'|'varAccount'|'endUserAccount',sourceField:'distributorSourceName'|'varSourceName'|'endUserSourceName'):Prisma.PriceExceptionWhereInput|undefined=>raw?.trim()?{OR:[{[sourceField]:{contains:raw.trim().slice(0,100),mode:'insensitive'}},{[accountField]:{name:{contains:raw.trim().slice(0,100),mode:'insensitive'}}}]}:undefined;
export function priceExceptionWhere(filters:PriceExceptionFilters,now=new Date()):Prisma.PriceExceptionWhereInput{const and:Prisma.PriceExceptionWhereInput[]=[];if(filters.q?.trim()){const q=filters.q.trim().slice(0,100);and.push({OR:[{peCode:{contains:q,mode:'insensitive'}},{predecessorPeCode:{contains:q,mode:'insensitive'}},{distributorSourceName:{contains:q,mode:'insensitive'}},{varSourceName:{contains:q,mode:'insensitive'}},{endUserSourceName:{contains:q,mode:'insensitive'}},{lines:{some:{sourceSku:{contains:q,mode:'insensitive'}}}}]});}if(Object.values(PriceExceptionStatus).includes(filters.status as PriceExceptionStatus))and.push({status:filters.status as PriceExceptionStatus});for(const condition of [party(filters.distributor,'distributorAccount','distributorSourceName'),party(filters.varName,'varAccount','varSourceName'),party(filters.endUser,'endUserAccount','endUserSourceName')])if(condition)and.push(condition);if(filters.expiration==='expired')and.push({expirationDate:{lt:now}});if(filters.expiration==='future')and.push({expirationDate:{gte:now}});if(filters.expiration==='none')and.push({expirationDate:null});if(filters.unresolved==='yes')and.push({OR:[{AND:[{distributorSourceName:{not:null}},{distributorAccountId:null}]},{AND:[{varSourceName:{not:null}},{varAccountId:null}]},{AND:[{endUserSourceName:{not:null}},{endUserAccountId:null}]},{lines:{some:{productSkuId:null}}}]});if(filters.salesRep==='unassigned')and.push({assignedSalesRepUserId:null,sourceType:'LEGACY_WORKBOOK'});else if(filters.salesRep&&/^\d+$/.test(filters.salesRep)){const id=Number(filters.salesRep);if(Number.isSafeInteger(id)&&id>0)and.push({assignedSalesRepUserId:id});}return and.length?{AND:and}:{}}
export async function listPriceExceptions(db:PrismaClient,filters:PriceExceptionFilters,actor:Actor){const where=scopedPriceExceptionWhere(actor,priceExceptionWhere(filters));const count=await db.priceException.count({where});const{page,pages}=pageNumber(filters.page,count);const [rows,salesReps]=await Promise.all([db.priceException.findMany({where,orderBy:[{status:'asc'},{expirationDate:'desc'},{id:'desc'}],skip:(page-1)*25,take:25,include:{assignedSalesRepUser:{select:{id:true,firstName:true,lastName:true,active:true,archivedAt:true}},distributorAccount:{select:{id:true,name:true}},varAccount:{select:{id:true,name:true}},endUserAccount:{select:{id:true,name:true}},_count:{select:{lines:true}},lines:{where:{productSkuId:null},select:{id:true},take:1}}}),actor.role==='SALES'?Promise.resolve([]):db.user.findMany({where:{OR:[{active:true,archivedAt:null,role:{in:['SALES','SALES_MANAGER']}},{assignedPriceExceptions:{some:{}}}]},orderBy:[{lastName:'asc'},{firstName:'asc'}],select:{id:true,firstName:true,lastName:true,active:true,archivedAt:true}})]);return{rows,count,page,pages,salesReps}}
export function priceExceptionHref(filters:PriceExceptionFilters,page?:number){const params=new URLSearchParams();for(const[key,value]of Object.entries(filters))if(value&&key!=='page')params.set(key,value);if(page)params.set('page',String(page));return`/price-exceptions?${params}`}
export function accountPriceExceptionRoles(row:{distributorAccountId:number|null;varAccountId:number|null;endUserAccountId:number|null},accountId:number){return [['Distributor/OEM',row.distributorAccountId],['VAR/ISV',row.varAccountId],['End User',row.endUserAccountId]].filter(([,id])=>id===accountId).map(([role])=>role as string)}
export function accountPriceExceptionWhere(accountId:number,actor?:Actor):Prisma.PriceExceptionWhereInput{const where={OR:[{distributorAccountId:accountId},{varAccountId:accountId},{endUserAccountId:accountId}]};return actor?scopedPriceExceptionWhere(actor,where):where}
