import { createHash } from 'node:crypto';
import * as XLSX from 'xlsx';
import { Prisma, type PrismaClient } from '@prisma/client';
import { inspectZip, maxXlsxBytes } from './import-xlsx';
import { normalizePartNumber } from './product-import';
import { can, type Actor } from './authorization';

export const planFields=['account','planItem','sku','units','revenue','priorRevenue','comments','rep'] as const;
export type PlanField=typeof planFields[number];
export type SheetMapping={sheet:string;headerRow:number;columns:Partial<Record<PlanField,number>>;repId?:number;include?:boolean};
export type ImportConfig={year:number;currencyCode:string;name:string;revision:number;mappings:SheetMapping[]};
export type RowReview={sheet:string;row:number;include:boolean;accountId?:number|null;skuId?:number|null;repId?:number|null;carryAccount?:boolean};
export type ImportReview={config:ImportConfig;rows:RowReview[];sha256:string;configSha256:string};
export function sanitizeSalesPlanMappings(mappings:SheetMapping[]){
  if(!Array.isArray(mappings)||!mappings.length||mappings.length>30)throw new Error('Choose valid worksheet mappings.');
  const seen=new Set<string>();
  return mappings.map(mapping=>{
    if(!mapping||typeof mapping.sheet!=='string'||!mapping.sheet||mapping.sheet.length>31||seen.has(mapping.sheet)||!Number.isInteger(mapping.headerRow)||mapping.headerRow<1||mapping.headerRow>5000||!mapping.columns||typeof mapping.columns!=='object')throw new Error('Invalid worksheet mapping.');
    seen.add(mapping.sheet);
    const columns:Partial<Record<PlanField,number>>={};
    for(const field of planFields){const value=mapping.columns[field];if(value!==undefined){if(!Number.isInteger(value)||value<0||value>=50)throw new Error('Invalid mapped column.');columns[field]=value;}}
    if(mapping.repId!==undefined&&(!Number.isSafeInteger(mapping.repId)||mapping.repId<=0))throw new Error('Invalid mapped sales rep.');
    return {sheet:mapping.sheet,headerRow:mapping.headerRow,columns,include:mapping.include!==false,...(mapping.repId?{repId:mapping.repId}:{})};
  });
}
export function salesPlanMappingTemplate(mappings:SheetMapping[]){return sanitizeSalesPlanMappings(mappings).map(mapping=>({sheet:mapping.sheet,headerRow:mapping.headerRow,columns:mapping.columns,include:mapping.include}));}
function configDigest(config:ImportConfig){return createHash('sha256').update(JSON.stringify([config.year,config.currencyCode,config.name,config.revision,config.mappings.map(m=>[m.sheet,m.headerRow,m.repId??null,m.include!==false,planFields.map(field=>m.columns[field]??null)])])).digest('hex');}
const clean=(v:unknown,max=2000)=>String(v??'').trim().replace(/\s+/g,' ').slice(0,max);
const bounded=(v:unknown,max:number,label:string)=>{const value=String(v??'').trim().replace(/\s+/g,' ');if(value.length>max)throw new Error(`${label} exceeds ${max} characters; shorten it in the source before import.`);return value;};
const key=(s:string)=>clean(s).toLocaleLowerCase();
const validNumber=(v:string,places:number)=>{const s=v.trim().replace(/[$,\s]/g,'');if(!s||s==='-')return null;if(!new RegExp(`^\\d{1,15}(?:\\.\\d{1,${places}})?$`).test(s))throw new Error(`Invalid nonnegative number: ${v.slice(0,40)}`);return new Prisma.Decimal(s);};
function workbook(buffer:Buffer){if(!buffer.length||buffer.length>maxXlsxBytes||inspectZip(buffer))throw new Error('Choose a valid unencrypted .xlsx workbook under 4 MB.');const book=XLSX.read(buffer,{type:'buffer',dense:true,cellDates:false,cellFormula:false,cellHTML:false,bookVBA:false,bookDeps:false,bookFiles:false});if(book.SheetNames.length>30)throw new Error('Too many worksheets.');return book;}
function sheets(book:XLSX.WorkBook){return book.SheetNames.map(name=>{const ws=book.Sheets[name];const rows=XLSX.utils.sheet_to_json<(string|number|null)[]>(ws,{header:1,defval:'',raw:false});if(rows.length>5000||rows.some(row=>row.length>50))throw new Error('Worksheet exceeds import limits.');return {name,rows};});}
function cell(row:(string|number|null)[],index:number|undefined){const v=index===undefined?'':row[index];return String(v??'').trim().replace(/\s+/g,' ');}
export function inspectSalesPlanWorkbook(buffer:Buffer){const book=workbook(buffer);return {sha256:createHash('sha256').update(buffer).digest('hex'),sheets:sheets(book).map(s=>({name:s.name,rows:s.rows.length,preview:s.rows.slice(0,8).map(r=>r.map(v=>clean(v,120)).slice(0,12))}))};}
function normalize(buffer:Buffer,config:ImportConfig){const book=workbook(buffer);const all=sheets(book);if(!Number.isInteger(config.year)||config.year<2000||config.year>2100||!/^[A-Z]{3}$/.test(config.currencyCode)||!clean(config.name,255)||!Number.isInteger(config.revision)||config.revision<1||config.revision>999)throw new Error('Choose a valid plan year, currency, name, and revision.');
 const rows:{sheet:string;row:number;account:string;carrySuggestion:string;planItem:string;sku:string;units:Prisma.Decimal|null;revenue:Prisma.Decimal|null;priorRevenue:Prisma.Decimal|null;comments:string;rep:string;selectedRepId:number|null;warning:string[]}[]=[];
 const selected=sanitizeSalesPlanMappings(config.mappings).filter(m=>m.include!==false);if(!selected.length||new Set(selected.map(m=>m.sheet)).size!==selected.length)throw new Error('Select distinct worksheets.');
 for(const m of selected){const s=all.find(s=>s.name===m.sheet);if(!s||!Number.isInteger(m.headerRow)||m.headerRow<1||m.headerRow>s.rows.length||!m.columns.account&&m.columns.account!==0)throw new Error('Check worksheet header and Account mapping.');for(const value of Object.values(m.columns))if(value!==undefined&&(!Number.isInteger(value)||value<0||value>=50))throw new Error('Invalid column mapping.');if(!m.repId&&m.columns.rep===undefined)throw new Error('Choose a rep or map a Sales Rep column.');let previous='';let section='PLAN';for(let i=m.headerRow;i<s.rows.length;i++){const r=s.rows[i];const account=cell(r,m.columns.account),planItem=cell(r,m.columns.planItem),sku=cell(r,m.columns.sku),unitsText=cell(r,m.columns.units),revenueText=cell(r,m.columns.revenue),priorText=cell(r,m.columns.priorRevenue),comments=cell(r,m.columns.comments),rep=cell(r,m.columns.rep);if(/development projects/i.test(account)){section='DEVELOPMENT';previous='';continue;}if(/^(?:sales plan - accounts|\d{4} plan)$/i.test(account)){section='PLAN';previous='';continue;}if(/^(?:total|subtotal)(?:$|\s+(?:direct|oem|channel|label|media|sales|plan|revenue|units))/i.test(account)&&(!sku||sku==='-')&&!planItem){previous='';continue;}if(!account&&!planItem&&!sku&&!unitsText&&!revenueText&&!priorText&&!comments)continue;if(section==='DEVELOPMENT'&&!/\d/.test(unitsText)&&!/\d/.test(revenueText))continue;if(account)previous=account;const warning:string[]=[];if(section==='DEVELOPMENT')warning.push('Development Project has an annual value; review inclusion as an official Sales Plan line.');if(!account&&previous)warning.push(`Blank Account; suggested carry-forward: ${previous}. Review before linking.`);if(!account&&!previous)warning.push('No Account.');if(!sku)warning.push('No SKU.');rows.push({sheet:s.name,row:i+1,account:bounded(account,500,'Account text'),carrySuggestion:bounded(!account?previous:'',500,'Account suggestion'),planItem:bounded(planItem,1000,'Plan Item'),sku:bounded(sku,500,'SKU text'),units:validNumber(unitsText,3),revenue:validNumber(revenueText,2),priorRevenue:validNumber(priorText,2),comments:bounded(comments,4000,'Comments'),rep:bounded(rep,255,'Sales Rep text'),selectedRepId:m.repId??null,warning});}}
 if(rows.length>5000||!rows.length)throw new Error('No annual plan lines selected.');return rows;
}
export async function previewSalesPlanImport(client:PrismaClient,actor:Actor,buffer:Buffer,config:ImportConfig){if(!can(actor,'sales-plan.manage'))throw new Error('Access denied');const rows=normalize(buffer,config);const [accounts,skus,users]=await Promise.all([client.account.findMany({where:{archivedAt:null,status:'ACTIVE'},select:{id:true,name:true}}),client.productSku.findMany({where:{active:true,product:{active:true,archivedAt:null}},select:{id:true,normalizedPartNumber:true,partNumber:true}}),client.user.findMany({where:{role:{in:['SALES','SALES_MANAGER']}},select:{id:true,firstName:true,lastName:true,active:true,archivedAt:true}})]);
 const accountMap=new Map<string,number[]>(),skuMap=new Map<string,number[]>(),userMap=new Map<string,number[]>();for(const a of accounts)accountMap.set(key(a.name),[...(accountMap.get(key(a.name))??[]),a.id]);for(const s of skus)skuMap.set(s.normalizedPartNumber,[...(skuMap.get(s.normalizedPartNumber)??[]),s.id]);for(const u of users){const k=key(`${u.firstName} ${u.lastName}`);userMap.set(k,[...(userMap.get(k)??[]),u.id]);const first=key(u.firstName);userMap.set(first,[...(userMap.get(first)??[]),u.id]);}
 const review=rows.map(r=>{const accountIds=accountMap.get(key(r.account))??[],skuIds=skuMap.get(normalizePartNumber(r.sku))??[],repIds=r.selectedRepId?[r.selectedRepId]:userMap.get(key(r.rep))??[];const warnings=[...r.warning];if(r.account&&accountIds.length!==1)warnings.push('Account unresolved or ambiguous.');if(r.sku&&skuIds.length!==1)warnings.push('SKU unresolved or ambiguous.');if(repIds.length!==1)warnings.push('Sales rep unresolved or ambiguous.');return {...r,units:r.units?.toString()??null,revenue:r.revenue?.toFixed(2)??null,priorRevenue:r.priorRevenue?.toFixed(2)??null,accountId:accountIds.length===1?accountIds[0]:null,skuId:skuIds.length===1?skuIds[0]:null,repId:repIds.length===1?repIds[0]:null,warnings};});const seen=new Map<string,typeof review[number]>();for(const row of review){const identity=JSON.stringify([row.repId??key(row.rep),key(row.account),normalizePartNumber(row.sku)]);const earlier=seen.get(identity);if(earlier&&earlier.sheet!==row.sheet)row.warnings.push(`Possible duplicate of ${earlier.sheet} row ${earlier.row}; exclude one copy.`);else seen.set(identity,row);}return {sha256:createHash('sha256').update(buffer).digest('hex'),configSha256:configDigest(config),rows:review,accounts,skus,users};}
export async function finalizeSalesPlanImport(client:PrismaClient,actor:Actor,buffer:Buffer,filename:string,review:ImportReview){if(!can(actor,'sales-plan.manage'))throw new Error('Access denied');const sha=createHash('sha256').update(buffer).digest('hex');if(sha!==review.sha256)throw new Error('Workbook changed since preview.');if(configDigest(review.config)!==review.configSha256)throw new Error('Mapping changed since preview. Review the workbook again.');const preview=await previewSalesPlanImport(client,actor,buffer,review.config);if(review.rows.length!==preview.rows.length||review.rows.some((r,i)=>r.sheet!==preview.rows[i].sheet||r.row!==preview.rows[i].row))throw new Error('Preview is stale.');const currency=await client.currency.findUnique({where:{code:review.config.currencyCode}});if(!currency?.active)throw new Error('Currency is inactive.');const users=await client.user.findMany({where:{id:{in:review.rows.map(r=>r.repId).filter((v):v is number=>!!v)}},select:{id:true,firstName:true,lastName:true,role:true,active:true,archivedAt:true}});const byUser=new Map(users.map(u=>[u.id,u]));const activeAccounts=new Set(preview.accounts.map(a=>a.id)),activeSkus=new Set(preview.skus.map(s=>s.id));const grouped=new Map<number,{sourceName:string;lines:Prisma.SalesPlanLineCreateWithoutPlanInput[]} >();for(let i=0;i<review.rows.length;i++){const choice=review.rows[i],r=preview.rows[i];if(!choice.include)continue;const rep=byUser.get(choice.repId??0);if(!rep||!['SALES','SALES_MANAGER'].includes(rep.role))throw new Error(`Row ${r.row}: choose an existing Sales rep.`);if(choice.accountId&&!activeAccounts.has(choice.accountId))throw new Error(`Row ${r.row}: Account is not operational.`);if(choice.skuId&&!activeSkus.has(choice.skuId))throw new Error(`Row ${r.row}: SKU is not operational.`);if(!r.account&&choice.accountId&&!choice.carryAccount)throw new Error(`Row ${r.row}: explicitly approve Account carry-forward.`);const entry=grouped.get(rep.id)??{sourceName:r.rep||`${rep.firstName} ${rep.lastName}`,lines:[]};entry.lines.push({originalSalesRepName:r.rep||null,originalAccountText:r.account||null,accountCarryForwardSuggested:!!r.carrySuggestion,account:choice.accountId?{connect:{id:choice.accountId}}:undefined,originalSkuText:r.sku||null,productSku:choice.skuId?{connect:{id:choice.skuId}}:undefined,planItem:r.planItem||null,annualPlannedUnits:r.units?new Prisma.Decimal(r.units):null,annualPlannedRevenue:r.revenue?new Prisma.Decimal(r.revenue):null,priorYearRevenue:r.priorRevenue?new Prisma.Decimal(r.priorRevenue):null,comments:r.comments||null,sourceWorksheet:r.sheet,sourceRow:r.row});grouped.set(rep.id,entry);}if(!grouped.size)throw new Error('Select at least one line.');
 const seenLines=new Map<string,string>();for(const [ownerId,entry] of grouped)for(const line of entry.lines){const identity=JSON.stringify([ownerId,key(line.originalAccountText??''),normalizePartNumber(line.originalSkuText??'')]);const earlier=seenLines.get(identity);if(earlier&&earlier!==line.sourceWorksheet)throw new Error('Duplicate annual lines across worksheets. Exclude one copy in review.');seenLines.set(identity,line.sourceWorksheet);}
 return client.$transaction(async tx=>{const accountIds=[...new Set(review.rows.filter(r=>r.include&&r.accountId).map(r=>r.accountId!))],skuIds=[...new Set(review.rows.filter(r=>r.include&&r.skuId).map(r=>r.skuId!))];const [checkedAccounts,checkedSkus,checkedOwners,checkedCurrency]=await Promise.all([tx.account.findMany({where:{id:{in:accountIds},archivedAt:null,status:'ACTIVE'},select:{id:true}}),tx.productSku.findMany({where:{id:{in:skuIds},active:true,product:{active:true,archivedAt:null}},select:{id:true}}),tx.user.findMany({where:{id:{in:[...grouped.keys()]},role:{in:['SALES','SALES_MANAGER']}},select:{id:true}}),tx.currency.findUnique({where:{code:review.config.currencyCode},select:{active:true}})]);if(checkedAccounts.length!==accountIds.length||checkedSkus.length!==skuIds.length||checkedOwners.length!==grouped.size||!checkedCurrency?.active)throw new Error('A selected Account, SKU, rep, or currency changed eligibility. Preview again.');const created=[];for(const [ownerId,entry] of grouped){const fingerprint=createHash('sha256').update(JSON.stringify({sha,year:review.config.year,currency:review.config.currencyCode,ownerId,mappings:review.config.mappings,lines:entry.lines.map(l=>[l.sourceWorksheet,l.sourceRow,l.originalAccountText,l.originalSkuText])})).digest('hex');if(await tx.salesPlan.findUnique({where:{importFingerprint:fingerprint}}))throw new Error('This plan import was already finalized.');if(await tx.salesPlan.findUnique({where:{ownerId_planYear_currencyCode_revision:{ownerId,planYear:review.config.year,currencyCode:review.config.currencyCode,revision:review.config.revision}}}))throw new Error('This revision already exists for a rep. Choose a new revision.');const active=await tx.salesPlan.findMany({where:{ownerId,planYear:review.config.year,currencyCode:review.config.currencyCode,status:'ACTIVE'}});for(const prior of active){if(review.config.revision<=prior.revision)throw new Error('A new official plan needs a higher revision.');await tx.salesPlan.update({where:{id:prior.id},data:{status:'SUPERSEDED',supersededAt:new Date(),supersededById:actor.id}});}const plan=await tx.salesPlan.create({data:{planYear:review.config.year,currencyCode:review.config.currencyCode,ownerId,originalOwnerName:entry.sourceName,name:clean(review.config.name,255),revision:review.config.revision,status:'ACTIVE',sourceFileName:clean(filename,255),sourceSha256:sha,importFingerprint:fingerprint,createdById:actor.id,activatedAt:new Date(),lines:{create:entry.lines}}});created.push(plan.id);}return created;},{isolationLevel:'Serializable'});
}
