import * as XLSX from 'xlsx';

type Cell = string | number | Date | null;
type Summary = { rep:string; target:number|null; plan:number|null; difference:number|null; planPercent:number|null; qPlan:(number|null)[]; qTarget:(number|null)[]; pipeline:number; bestCase:number; commit:number };
type Approved = {rep:string;account:string;planItem:string;product:string;sku:string;units:number|null;revenue:number|null;priorRevenue:number|null;quarters:(number|null)[][];allocationStatus:string;comments:string;revision:number;status:string};
type Pipeline = {rep:string;account:string;opportunity:string;stage:string;category:string;date:Date;quarter:string;product:string;sku:string;quantity:number;unitPrice:number;value:number;opportunityTotal:number;currency:string;probability:number;planned:string;matchStatus:string};
type Comparison = {rep:string;account:string;product:string;sku:string;planned:number|null;units:number|null;pipeline:number;bestCase:number;commit:number;pipelineDifference:number|null;commitDifference:number|null;classification:string};
export const moneyFormat = (code:string) => code === 'USD' ? '$#,##0.00;[Red]($#,##0.00)' : `"${code}" #,##0.00;[Red]("${code}" #,##0.00)`;
export const easternGeneratedAt = (date:Date) => `${new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',year:'numeric'}).format(date)} at ${new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit',hour12:true}).format(date)} ET`;
const units = '#,##0.###';
const percent = '0.0%';
export function sheet(headers:string[], rows:Cell[][], widths:number[], formats:Record<number,string>, headerRow=1) {
  const worksheet=XLSX.utils.aoa_to_sheet([...Array.from({length:headerRow-1},()=>[]),headers,...rows]);
  worksheet['!cols']=widths.map(wch=>({wch}));
  worksheet['!autofilter']={ref:`A${headerRow}:${XLSX.utils.encode_col(headers.length-1)}${rows.length+headerRow}`};
  worksheet['!rows']=Array.from({length:rows.length+headerRow},(_,i)=>({hpt:i===headerRow-1?30:20}));
  for(let r=headerRow;r<rows.length+headerRow;r++)for(const [column,format] of Object.entries(formats)){const cell=worksheet[XLSX.utils.encode_cell({r,c:Number(column)})];if(cell&&cell.t==='n')cell.z=format;}
  return worksheet;
}
function totalColumn(rows:Summary[], getter:(row:Summary)=>number|null) { const values=rows.map(getter);return values.every(value=>value!==null)?values.reduce<number>((total,value)=>total+value!,0):null; }
export function salesPlanManagementWorkbook(input:{year:number;currencyCode:string;scope:string;generatedAt:Date;generatedBy:string;missingPlanReps:number;summary:Summary[];approved:Approved[];pipeline:Pipeline[];comparison:Comparison[]}) {
  const book=XLSX.utils.book_new();
  const money=moneyFormat(input.currencyCode);
  const summaryHeaders=['Sales Rep','Annual Sales Target','Official Annual Sales Plan','Difference to Target','Plan as % of Target','Q1 Plan Allocation','Q2 Plan Allocation','Q3 Plan Allocation','Q4 Plan Allocation','Q1 Target','Q2 Target','Q3 Target','Q4 Target','Annual Open Pipeline','Annual Best Case','Annual Commit'];
  const summaryRow=(r:Summary):Cell[]=>[r.rep,r.target,r.plan,r.difference,r.planPercent,...r.qPlan,...r.qTarget,r.pipeline,r.bestCase,r.commit];
  const summaryRows=input.summary.map(summaryRow);
  if(input.summary.length>1){const rows=input.summary;const target=totalColumn(rows,r=>r.target),plan=totalColumn(rows,r=>r.plan);summaryRows.push(['Team Total',target,plan,target!==null&&plan!==null?plan-target:null,target&&plan!==null?plan/target:null,...[0,1,2,3].map(i=>totalColumn(rows,r=>r.qPlan[i])),...[0,1,2,3].map(i=>totalColumn(rows,r=>r.qTarget[i])),...(['pipeline','bestCase','commit'] as const).map(k=>rows.reduce((n,r)=>n+r[k],0))]);}
  const target=totalColumn(input.summary,r=>r.target),plan=totalColumn(input.summary,r=>r.plan);
  const meta:Cell[][]=[['SalesHub','Sales Plan Management Workbook'],['Plan Year',input.year],['Currency',input.currencyCode],['Rep Scope',input.scope],['Generated',easternGeneratedAt(input.generatedAt)],['Generated By',input.generatedBy],['About this workbook','Sales Plan is the approved annual commitment. Pipeline, Best Case, and Commit reflect current SalesHub Opportunities as of the generated time.'],['Forecast snapshot','Forecast values reflect current SalesHub Opportunity data at the time this workbook was generated.'],['Active Sales reps without a plan',input.missingPlanReps],[],['Management Snapshot'],['Annual Sales Target',target],['Official Annual Sales Plan',plan],['Difference to Target',target!==null&&plan!==null?plan-target:null],['Current Open Pipeline',input.summary.reduce((n,r)=>n+r.pipeline,0)],['Best Case',input.summary.reduce((n,r)=>n+r.bestCase,0)],['Commit',input.summary.reduce((n,r)=>n+r.commit,0)],['Reps with Active Plan',input.summary.length],['Active Reps Missing Plan',input.missingPlanReps],[],summaryHeaders,...summaryRows];
  const headerRow=meta.findIndex(row=>row[0]==='Sales Rep')+1;
  const executive=XLSX.utils.aoa_to_sheet(meta);executive['!cols']=[{wch:34},...Array.from({length:15},()=>({wch:23}))];executive['!autofilter']={ref:`A${headerRow}:P${meta.length}`};executive['!rows']=Array.from({length:meta.length},(_,i)=>({hpt:i===headerRow-1?34:i===6||i===7?28:20}));
  for(let r=headerRow;r<meta.length;r++)for(let c=1;c<16;c++){const cell=executive[XLSX.utils.encode_cell({r,c})];if(cell?.t==='n')cell.z=c===4?percent:money;}
  for(const r of [11,12,13,14,15,16]){const cell=executive[`B${r+1}`];if(cell?.t==='n')cell.z=money;}
  XLSX.utils.book_append_sheet(book,executive,'Executive Summary');
  const approvedHeaders=['Sales Rep','Account','Plan Item','Product / Model','Exact SKU','Annual Planned Units','Annual Planned Revenue','Prior-Year Revenue','Q1 Units','Q1 Revenue','Q2 Units','Q2 Revenue','Q3 Units','Q3 Revenue','Q4 Units','Q4 Revenue','Allocation Status','Comments','Plan Revision','Plan Status'];
  const approvedRows=input.approved.map(r=>[r.rep,r.account,r.planItem,r.product,r.sku,r.units,r.revenue,r.priorRevenue,...r.quarters.flat(),r.allocationStatus,r.comments,r.revision,r.status]);
  XLSX.utils.book_append_sheet(book,sheet(approvedHeaders,approvedRows,[22,30,35,27,23,20,23,20,15,19,15,19,15,19,15,19,20,55,15,15],{5:units,6:money,7:money,8:units,9:money,10:units,11:money,12:units,13:money,14:units,15:money}),'Approved Sales Plan');
  const pipelineHeaders=['Sales Rep','Account','Opportunity','Stage','Forecast Category','Expected Close Date','Forecast Quarter','Product / Model','Exact SKU','Quantity','Unit Price','Product Line Value','Opportunity Total Value','Currency','Probability','Planned Business?','Plan Match Status'];
  const pipelineRows=input.pipeline.map(r=>[r.rep,r.account,r.opportunity,r.stage,r.category,r.date,r.quarter,r.product,r.sku,r.quantity,r.unitPrice,r.value,r.opportunityTotal,r.currency,r.probability,r.planned,r.matchStatus]);
  const pipelineSheet=sheet(pipelineHeaders,pipelineRows,[22,34,38,20,19,22,18,28,23,14,17,21,24,12,16,20,30],{9:units,10:money,11:money,12:money,14:percent});
  for(let r=1;r<=pipelineRows.length;r++){const cell=pipelineSheet[`F${r+1}`];if(cell)cell.z='mmm d, yyyy';}
  if(!pipelineRows.length){XLSX.utils.sheet_add_aoa(pipelineSheet,[[`No current ${input.year} Opportunities match this export scope.`]],{origin:'A2'});pipelineSheet['!autofilter']={ref:'A1:Q2'};}
  XLSX.utils.book_append_sheet(book,pipelineSheet,'Current Opportunity Pipeline');
  const comparisonHeaders=['Sales Rep','Account','Product / Model','Exact SKU','Annual Planned Revenue','Annual Planned Units','Open Pipeline','Best Case','Commit','Pipeline vs Plan Difference','Commit vs Plan Difference','Status / Classification'];
  const comparisonRows=input.comparison.map(r=>[r.rep,r.account,r.product,r.sku,r.planned,r.units,r.pipeline,r.bestCase,r.commit,r.pipelineDifference,r.commitDifference,r.classification]);
  XLSX.utils.book_append_sheet(book,sheet(comparisonHeaders,comparisonRows,[22,34,28,23,23,20,20,20,20,28,26,28],{4:money,5:units,6:money,7:money,8:money,9:money,10:money}),'Plan vs Pipeline Detail');
  return book;
}
