import * as XLSX from 'xlsx';
import { supportCaseAge, type SupportReportFilters } from './support-report';
import { supportPriorityLabels,supportStatusLabels,supportSourceLabels } from './support-cases';
import type { supportReport } from './support-report';

type Report=Awaited<ReturnType<typeof supportReport>>;
export function supportReportWorkbook(report:Report,filters:SupportReportFilters,generatedBy:string){
  const book=XLSX.utils.book_new();
  const summary:(string|number|Date|null)[][]=[['Support Case Summary'],['Generated',report.now],['Generated by',generatedBy],['Filter scope',Object.entries(filters).filter(([key,value])=>key!=='page'&&value).map(([key,value])=>`${key}: ${value}`).join('; ')||'Current cases'],[],['KPI','Value'],['Open Cases',report.summary.open],['High / Critical',report.summary.highCritical],['Overdue Follow-ups',report.summary.overdue],['Opened in period',report.summary.opened],['Resolved in period',report.summary.resolved],['Average age of open cases (days)',report.summary.averageOpenDays],['Average time to resolution (days)',report.summary.averageResolutionDays],[],['Status','Count'],...report.groups.status.map(x=>[supportStatusLabels[x.label as keyof typeof supportStatusLabels]??x.label,x.count]),[],['Priority','Count'],...report.groups.priority.map(x=>[supportPriorityLabels[x.label as keyof typeof supportPriorityLabels]??x.label,x.count]),[],['Category','Count'],...report.groups.category.map(x=>[x.label,x.count])];
  XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(summary,{cellDates:true}),'Support Case Summary');
  const headers=['Case Number','Account','Contact','Subject','Status','Priority','Category','Assigned To','Product / SKU','Serial Number','Purchased From','Linked Purchased-From Account','Source','Opened','Next Follow-up','Resolved','Closed','Case Age (days)','Resolution Time (days)','Archived'];
  const rows=report.rows.map(row=>[row.caseNumber,row.customerNameText??row.account?.name??'',row.contact?`${row.contact.firstName} ${row.contact.lastName}`:'',row.subject,supportStatusLabels[row.status],supportPriorityLabels[row.priority],row.category?.name??'',row.assignedTo?`${row.assignedTo.firstName} ${row.assignedTo.lastName}`:'',row.productSku?.partNumber??'',row.serialNumber??'',row.purchaseSourceText??'',row.purchasedFromAccount?.name??'',supportSourceLabels[row.source],row.openedAt,row.nextFollowUpAt,row.resolvedAt,row.closedAt,supportCaseAge(row,report.now),row.resolvedAt?Math.round((row.resolvedAt.getTime()-row.openedAt.getTime())/86400000*10)/10:null,row.archivedAt?'Archived':'Current']);
  const detail=XLSX.utils.aoa_to_sheet([headers,...rows],{cellDates:true});
  if(!rows.length){detail.A2={t:'s',v:'No Support Cases match these filters.'};detail['!ref']='A1:T2';}
  for(const key of Object.keys(detail)){if(key.startsWith('!'))continue;const cell=detail[key];if(cell?.v instanceof Date){cell.t='d';cell.z='yyyy-mm-dd hh:mm';}}
  detail['!cols']=headers.map((header)=>({wch:Math.max(16,Math.min(32,header.length+3))}));
  XLSX.utils.book_append_sheet(book,detail,'Support Cases');return book;
}
