import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Content, PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { canManageAttribution, campaignStatuses } from '@/lib/marketing-attribution';
import { prisma } from '@/lib/prisma';
import { saveCampaign, setCampaignArchive } from '@/app/marketing/attribution/actions';

export default async function CampaignPage({ params }: { params: Promise<{ id: string }> }) {
  const actor = await currentUser(); if (!canManageAttribution(actor)) notFound();
  const id = Number((await params).id); if (!Number.isSafeInteger(id) || id < 1) notFound();
  const campaign = await prisma.marketingCampaign.findUnique({ where: { id }, include: { tradeShow: { select: { id: true, name: true } }, influences: { include: { tradeShowLead: { select: { id: true, tradeShowId: true, contactId: true, convertedOpportunityId: true } }, contact: { select: { id: true, firstName: true, lastName: true } } }, orderBy: [{ occurredAt: 'desc' }, { id: 'desc' }], take: 50 } } }); if (!campaign) notFound();
  const [leadCount, contactCount, opportunityCount] = await Promise.all([
    prisma.campaignInfluence.count({ where: { campaignId: id, voidedAt: null, tradeShowLeadId: { not: null } } }),
    prisma.contact.count({ where: { OR: [{ campaignInfluences: { some: { campaignId: id, voidedAt: null } } }, { tradeShowLeads: { some: { campaignInfluences: { some: { campaignId: id, voidedAt: null } } } } }] } }),
    prisma.opportunity.count({ where: { OR: [{ campaignInfluences: { some: { campaignId: id, voidedAt: null } } }, { originatingTradeShowLead: { is: { campaignInfluences: { some: { campaignId: id, voidedAt: null } } } } }, { contacts: { some: { contact: { OR: [{ campaignInfluences: { some: { campaignId: id, voidedAt: null } } }, { tradeShowLeads: { some: { campaignInfluences: { some: { campaignId: id, voidedAt: null } } } } }] } } } }] } }),
  ]);
  return <Content><PageHeader eyebrow="Campaigns" title={campaign.name} action={<Link className="btn-secondary" href="/marketing/campaigns">All Campaigns</Link>}/>
    <div className="panel mb-5 p-5 text-sm"><p>{campaign.archivedAt ? 'Archived' : campaign.status} · {leadCount} Trade Show leads · {contactCount} Contacts · {opportunityCount} Opportunities</p>{campaign.tradeShow && <p className="mt-2">Trade Show: <Link className="text-orange-800 underline" href={`/trade-shows/${campaign.tradeShow.id}`}>{campaign.tradeShow.name}</Link></p>}<p className="mt-2 text-slate-600">Counts reflect current links and active touches; they do not assign revenue credit.</p></div>
    <form action={saveCampaign} className="panel grid gap-3 p-5 sm:grid-cols-2"><input type="hidden" name="id" value={id}/><label className="text-sm">Name<input className="field mt-1 block w-full" name="name" defaultValue={campaign.name} required maxLength={160}/></label><label className="text-sm">Year<input className="field mt-1 block w-full" name="year" type="number" min={1900} max={2200} defaultValue={campaign.year ?? ''}/></label><label className="text-sm">Category<input className="field mt-1 block w-full" name="category" maxLength={120} defaultValue={campaign.category ?? ''}/></label><label className="text-sm">Status<select className="field mt-1 block w-full" name="status" defaultValue={campaign.status}>{campaignStatuses.map(status => <option key={status}>{status}</option>)}</select></label><label className="text-sm">Start date<input className="field mt-1 block w-full" name="startDate" type="date" defaultValue={campaign.startDate?.toISOString().slice(0, 10) ?? ''}/></label><label className="text-sm">End date<input className="field mt-1 block w-full" name="endDate" type="date" defaultValue={campaign.endDate?.toISOString().slice(0, 10) ?? ''}/></label><label className="text-sm sm:col-span-2">Description<textarea className="field mt-1 block w-full" name="description" maxLength={10000} defaultValue={campaign.description ?? ''}/></label><button className="btn-primary justify-self-start">Save Campaign</button></form>
    <form action={setCampaignArchive} className="mt-3"><input type="hidden" name="id" value={id}/><input type="hidden" name="archive" value={campaign.archivedAt ? 'false' : 'true'}/><button className="btn-secondary">{campaign.archivedAt ? 'Reactivate' : 'Archive'} Campaign</button></form>
    <section className="panel mt-5 p-5"><h2 className="mb-3 text-lg font-semibold">Recent Campaign Influence</h2><ul className="divide-y text-sm">{campaign.influences.map(touch => <li key={touch.id} className="py-2">{touch.occurredAt.toISOString().slice(0, 10)} · {touch.sourceContext}{touch.tradeShowLead ? <> · <Link className="text-orange-800 underline" href={`/trade-shows/${touch.tradeShowLead.tradeShowId}/leads/${touch.tradeShowLead.id}`}>Lead #{touch.tradeShowLead.id}</Link></> : touch.contact ? <> · <Link className="text-orange-800 underline" href={`/contacts/${touch.contact.id}`}>{touch.contact.firstName} {touch.contact.lastName}</Link></> : null}{touch.voidedAt && <span className="ml-2 text-slate-500">Voided</span>}</li>)}</ul>{!campaign.influences.length && <p className="text-sm text-slate-500">No touches recorded.</p>}</section>
  </Content>;
}
