'use client';
import { useState } from 'react';
import { previewUpload, confirmUpload } from './actions';
import type { ImportPlan } from '@/lib/import-plan';
const labels:Record<keyof ImportPlan['counts'],string> = {newAccounts:'New Accounts',updatedAccounts:'Updated Accounts',unchangedAccounts:'Unchanged Accounts',newContacts:'New Contacts',updatedContacts:'Updated Contacts',unchangedContacts:'Unchanged Contacts',skippedRows:'Skipped rows',warnings:'Warnings',errors:'Errors'};
export function ImportWorkflow({template}:{template:string}) {
  const [file,setFile] = useState<File|null>(null), [sheet,setSheet] = useState(''), [sheets,setSheets] = useState<string[]>([]), [filename,setFilename] = useState(''), [plan,setPlan] = useState<ImportPlan|null>(null), [busy,setBusy] = useState(false), [message,setMessage] = useState(''), [result,setResult] = useState<ImportPlan['counts']|null>(null);
  function load(selected:File|undefined) {
    setPlan(null); setResult(null); setMessage(''); setFile(null); setSheet(''); setSheets([]); if (!selected) return;
    setFilename(selected.name);
    const name = selected.name.toLowerCase();
    if (!name.endsWith('.csv') && !name.endsWith('.xlsx')) { setMessage('Choose a CSV or XLSX file.'); return; }
    if (selected.size > (name.endsWith('.csv') ? 2_000_000 : 4_000_000)) { setMessage(name.endsWith('.csv') ? 'CSV limit is 2 MB.' : 'XLSX limit is 4 MB.'); return; }
    setFile(selected);
  }
  function uploadForm(selectedSheet=sheet) { const form=new FormData(); if (file) form.set('file',file); if (selectedSheet) form.set('sheet',selectedSheet); return form; }
  async function preview() { if (!file) return; setBusy(true); setMessage(''); setResult(null); try { const response=await previewUpload(uploadForm()); setPlan(response.plan ?? null); setSheets(response.sheets ?? []); if (response.selectedSheet) setSheet(response.selectedSheet); if (response.error) setMessage(response.error); } catch { setMessage('Preview failed. Please try again.'); } finally { setBusy(false); } }
  async function confirm() { if (!plan || !file) return; setBusy(true); setMessage(''); try { const response=await confirmUpload(uploadForm(),plan.digest); if (response.ok) { setResult(response.counts); setPlan(null); setFile(null); setSheet(''); setSheets([]); } else setMessage(response.message); } catch { setMessage('Import failed. No result was returned. Check the data before retrying.'); } finally { setBusy(false); } }
  const link = `data:text/csv;charset=utf-8,${encodeURIComponent(template)}`;
  return <div className="space-y-5"><section className="panel p-6"><h2 className="text-lg font-semibold">1. Upload CSV or XLSX</h2><p className="mt-2 text-sm text-slate-600">Use one row per Account or Contact. Both formats use the same headers and validation. Headers are case insensitive. Blank cells preserve existing values. Business roles use internal codes separated by |. Contact Account mapping uses an exact name after case and whitespace normalization.</p><a className="mt-3 inline-block text-sm font-semibold text-orange-800 underline" href={link} download="accounts-contacts-template.csv">Download CSV header template (also valid for XLSX)</a><p className="mt-2 text-xs text-slate-600">Paste the template header into the first row of an XLSX worksheet. CSV limit: 2 MB. XLSX limit: 4 MB compressed, 5,000 import rows, 50 columns. For workbooks with several populated sheets, choose the import sheet below; sheets are never combined.</p><p className="mt-2 text-xs text-slate-600">Required: record_type; account_name for Account rows; contact_first_name and contact_last_name for Contact rows. Values for record_type: account or contact. Status: ACTIVE or INACTIVE. Boolean fields: true or false. Owner: exact CRM email. Territory and Industry: codes. Business roles: END_USER, DISTRIBUTOR, VAR, ISV, OEM, PARTNER.</p><div className="mt-4 flex flex-wrap items-center gap-3"><input aria-label="CSV or XLSX file" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>load(e.target.files?.[0])}/><button className="btn-primary" disabled={!file || busy} onClick={()=>void preview()}>Parse, validate & preview</button></div>{sheets.length > 1 && <label className="mt-3 block text-sm">Worksheet <select className="ml-2 rounded border border-slate-300 p-2" value={sheet} onChange={e=>{setSheet(e.target.value);setPlan(null);setMessage('');}}><option value="">Choose a worksheet</option>{sheets.map(name=><option key={name} value={name}>{name}</option>)}</select></label>}{filename && <p className="mt-2 text-sm text-slate-600">{filename}</p>}</section>
    {message && <p role="alert" className="rounded border border-red-300 bg-red-50 p-4 text-sm text-red-900">{message}</p>}
    {result && <section className="panel p-6"><h2 className="text-lg font-semibold">Import complete</h2><p className="mt-2 text-sm">All changes were applied in one transaction.</p><Counts counts={result}/></section>}
    {plan && <section className="panel p-6"><h2 className="text-lg font-semibold">2. Preview proposed changes</h2><Counts counts={plan.counts}/>{plan.errors.length > 0 && <ul className="mt-4 list-disc pl-5 text-sm text-red-800">{plan.errors.map(e=><li key={e}>{e}</li>)}</ul>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Line</th><th className="p-2">Type / record</th><th className="p-2">Status</th><th className="p-2">Before</th><th className="p-2">Proposed changes</th><th className="p-2">Messages</th></tr></thead><tbody>{plan.items.map(i=><tr key={i.line} className="border-b align-top"><td className="p-2">{i.line}</td><td className="p-2">{i.type}: {i.label}</td><td className="p-2 font-semibold">{i.status}</td><td className="p-2">{i.before}</td><td className="p-2">{i.after}</td><td className="p-2 text-red-800">{i.messages.join(' ')}</td></tr>)}</tbody></table></div><div className="mt-5"><button className="btn-primary" disabled={busy || !plan.digest || !!plan.errors.length || !!plan.counts.errors || !plan.items.length} onClick={()=>void confirm()}>Confirm and apply import</button><p className="mt-2 text-xs text-slate-600">This writes only after confirmation. If records changed since preview, confirm is refused.</p></div></section>}
  </div>;
}
function Counts({counts}:{counts:ImportPlan['counts']}) { return <div className="mt-4 grid gap-2 sm:grid-cols-3">{Object.entries(counts).map(([key,value])=><div className="rounded bg-slate-50 p-3 text-sm" key={key}><strong>{value}</strong> {labels[key as keyof typeof labels]}</div>)}</div>; }
