'use client';
import { useState } from 'react';
import { previewUpload, confirmUpload } from './actions';
import type { ImportPlan } from '@/lib/import-plan';
const labels:Record<keyof ImportPlan['counts'],string> = {newAccounts:'New Accounts',updatedAccounts:'Updated Accounts',unchangedAccounts:'Unchanged Accounts',newContacts:'New Contacts',updatedContacts:'Updated Contacts',unchangedContacts:'Unchanged Contacts',skippedRows:'Skipped rows',warnings:'Warnings',errors:'Errors'};
export function ImportWorkflow({template}:{template:string}) {
  const [file,setFile] = useState<File|null>(null), [sheet,setSheet] = useState(''), [sheets,setSheets] = useState<string[]>([]), [filename,setFilename] = useState(''), [plan,setPlan] = useState<ImportPlan|null>(null), [busy,setBusy] = useState(false), [message,setMessage] = useState(''), [result,setResult] = useState<ImportPlan['counts']|null>(null);
  function load(selected:File|undefined) {
    setPlan(null); setResult(null); setMessage(''); setFile(null); setSheet(''); setSheets([]); if (!selected) return;
    setFilename(selected.name);
    const name = selected.name.toLowerCase();
    if (!name.endsWith('.csv') && !name.endsWith('.xlsx')) { setMessage('Choose a CSV or XLSX file.'); return; }
    if (selected.size > (name.endsWith('.csv') ? 2_000_000 : 4_000_000)) { setMessage(name.endsWith('.csv') ? 'CSV limit is 2 MB.' : 'XLSX limit is 4 MB.'); return; }
    setFile(selected);
  }
  function uploadForm(selectedSheet=sheet) { const form=new FormData(); if (file) form.set('file',file); if (selectedSheet) form.set('sheet',selectedSheet); return form; }
  async function preview() { if (!file) return; setBusy(true); setMessage(''); setResult(null); try { const response=await previewUpload(uploadForm()); setPlan(response.plan ?? null); setSheets(response.sheets ?? []); if (response.selectedSheet) setSheet(response.selectedSheet); if (response.error) setMessage(response.error); } catch { setMessage('Preview failed. Please try again.'); } finally { setBusy(false); } }
  async function confirm() { if (!plan || !file) return; setBusy(true); setMessage(''); try { const response=await confirmUpload(uploadForm(),plan.digest); if (response.ok) { setResult(response.counts); setPlan(null); setFile(null); setSheet(''); setSheets([]); } else setMessage(response.message); } catch { setMessage('Import failed. Check your file and try again.'); } finally { setBusy(false); } }
  const link = `data:text/csv;charset=utf-8,${encodeURIComponent(template)}`;
  return <div className="space-y-5"><section className="panel p-6"><h2 className="text-lg font-semibold">1. Upload CSV or XLSX</h2><p className="mt-2 text-sm text-slate-600">Use one row per Account or Contact. Enter an Account name for Account rows and a first and last name for Contact rows. Blank cells leave existing values unchanged.</p><a className="mt-3 inline-block text-xs font-medium text-slate-600 underline hover:text-orange-800" href={link} download="accounts-contacts-template.csv">Download import template</a><p className="mt-2 text-xs text-slate-600">The template works with CSV or XLSX. File limits: CSV 2 MB; XLSX 4 MB, 5,000 rows, and 50 columns. For an XLSX workbook, select the worksheet to import.</p><p className="mt-2 text-xs text-slate-600">Set record_type to account or contact. Use CRM codes for Industry, Territory, and Business Roles; separate multiple Business Roles with |. The owner email must match an existing CRM user. For Contacts, use the Account name from the same file or from CRM. Business Role codes: END_USER, DISTRIBUTOR, VAR, ISV, OEM, PARTNER. Status uses ACTIVE or INACTIVE; yes/no fields use true or false.</p><div className="mt-4 flex flex-wrap items-center gap-3"><input aria-label="CSV or XLSX file" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>load(e.target.files?.[0])}/><button className="btn-primary" disabled={!file || busy} onClick={()=>void preview()}>Preview changes</button></div>{sheets.length > 1 && <label className="mt-3 block text-sm">Worksheet <select className="ml-2 rounded border border-slate-300 p-2" value={sheet} onChange={e=>{setSheet(e.target.value);setPlan(null);setMessage('');}}><option value="">Choose a worksheet</option>{sheets.map(name=><option key={name} value={name}>{name}</option>)}</select></label>}{filename && <p className="mt-2 text-sm text-slate-600">{filename}</p>}</section>
    {message && <p role="alert" className="rounded border border-red-300 bg-red-50 p-4 text-sm text-red-900">{message}</p>}
    {result && <section className="panel p-6"><h2 className="text-lg font-semibold">Import complete</h2><p className="mt-2 text-sm">The reviewed changes have been saved.</p><Counts counts={result}/></section>}
    {plan && <section className="panel p-6"><h2 className="text-lg font-semibold">2. Review proposed changes</h2><Counts counts={plan.counts}/>{plan.errors.length > 0 && <ul className="mt-4 list-disc pl-5 text-sm text-red-800">{plan.errors.map(e=><li key={e}>{e}</li>)}</ul>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Line</th><th className="p-2">Type / record</th><th className="p-2">Status</th><th className="p-2">Before</th><th className="p-2">Proposed changes</th><th className="p-2">Messages</th></tr></thead><tbody>{plan.items.map(i=><tr key={i.line} className="border-b align-top"><td className="p-2">{i.line}</td><td className="p-2">{i.type}: {i.label}</td><td className="p-2 font-semibold">{i.status}</td><td className="p-2">{i.before}</td><td className="p-2">{i.after}</td><td className="p-2 text-red-800">{i.messages.join(' ')}</td></tr>)}</tbody></table></div><div className="mt-5"><button className="btn-primary" disabled={busy || !plan.digest || !!plan.errors.length || !!plan.counts.errors || !plan.items.length} onClick={()=>void confirm()}>Confirm and apply import</button><p className="mt-2 text-xs text-slate-600">Changes are applied only after you confirm. If CRM records change after preview, review the import again.</p></div></section>}
  </div>;
}
function Counts({counts}:{counts:ImportPlan['counts']}) { return <div className="mt-4 grid gap-2 sm:grid-cols-3">{Object.entries(counts).map(([key,value])=><div className="rounded bg-slate-50 p-3 text-sm" key={key}><strong>{value}</strong> {labels[key as keyof typeof labels]}</div>)}</div>; }
