import { operationalActivityWhere } from '@/lib/operational-where';
import Link from 'next/link';
import { Content,PageHeader } from '@/components/shell';
import { DashboardEditor } from '@/components/dashboard-editor';
import { SaveSuccess } from '@/components/save-success';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { availableDashboardWidgets,dashboardAccountWhere,dashboardActivityWhere,dashboardItemPresentationSection,dashboardPeriod,dashboardPresentationSectionKeys,dashboardPresentationSectionTitles,dashboardTaskWhere,dashboardWidgetRegistry,getEffectiveDashboardLayout,pipelineReportHref,type DashboardLayoutItem,type SavedReportWidgetStyle } from '@/lib/dashboard';
import { forecastForRep,forecastForTeam } from '@/lib/forecast';
import { defaultReportConfiguration,executePipelineReport,executeReport,reportRegistry,savedReportWhere,validateReportConfiguration,type PipelineReportResult,type ReportConfiguration } from '@/lib/reporting';
import { hasNoActivityInDays,latestAccountActivityOrder } from '@/lib/engagement';
import { dayBounds } from '@/lib/work';
import { getSettings } from '@/lib/configuration';
import { formatCurrency } from '@/lib/display-format';
import { resetPersonalDashboardAction,savePersonalDashboardAction } from './dashboard-actions';
import { salesLeadQueueWhere } from '@/lib/trade-show-leads';

export const dynamic='force-dynamic';
const money=(value:string|null,currency:string)=>value===null?'No target set':formatCurrency(Number(value),currency);
const ratio=(value:string|null)=>value===null?'—':`${value}x`;
const span=(size:'HALF'|'FULL')=>size==='FULL'?'lg:col-span-2':'';

function SummaryTable({title,result,currency,href}:{title:string;result:PipelineReportResult;currency:string;href:string}){return <section className="panel h-full overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">{title}</h2><Link className="text-sm text-orange-800 underline" href={href}>View report</Link></div><div className="max-h-72 overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-2">{title.replace('Pipeline by ','')}</th><th className="px-4 py-2 text-right">Deals</th><th className="px-4 py-2 text-right">Pipeline</th></tr></thead><tbody>{result.groups.map(group=>{const metric=group.metrics.find(value=>value.currency===currency);return <tr className="border-t even:bg-slate-50/60" key={group.key}><td className="px-4 py-2">{group.label}</td><td className="px-4 py-2 text-right">{metric?.opportunityCount??0}</td><td className="px-4 py-2 text-right tabular-nums">{money(metric?.pipeline??'0',currency)}</td></tr>;})}</tbody></table>{!result.groups.length&&<p className="p-4 text-sm text-slate-500">No Opportunities this quarter.</p>}</div></section>;}

type ExecutedReport=Awaited<ReturnType<typeof executeReport>>;
const printable=(value:unknown):string=>value===null||value===undefined?'—':Array.isArray(value)?value.map(printable).join(', '):typeof value==='object'?(('name' in value!&&typeof (value as {name?:unknown}).name==='string')?String((value as {name:string}).name):'—'):String(value);
function SavedReportWidget({name,title,style,config,result,reportId}:{name:string;title?:string;style:SavedReportWidgetStyle;config:ReportConfiguration;result:ExecutedReport;reportId:number}){
  const heading=title||name,rows=result.rows as unknown as Record<string,unknown>[],groups=result.groups as unknown as {key:string;label:string}[];
  return <section className="panel h-full overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-semibold">{heading}</h2><p className="text-xs text-slate-500">Saved Report</p></div><Link className="text-sm text-orange-800 underline" href={`/reports/${reportId}`}>Open report</Link></div>
    {style==='KPI'?<div className="p-5"><p className="text-sm text-slate-600">Matching records</p><p className="mt-1 text-3xl font-semibold tabular-nums">{rows.length}</p>{!rows.length&&<p className="mt-2 text-sm text-slate-500">No matching records.</p>}</div>:
    style==='GROUPED_SUMMARY'?<div className="max-h-72 overflow-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-2 text-left">Group</th><th className="px-4 py-2 text-right">Records</th></tr></thead><tbody>{groups.slice(0,8).map(group=><tr className="border-t" key={group.key}><td className="px-4 py-2">{group.label}</td><td className="px-4 py-2 text-right">{rows.filter(row=>Array.isArray(row.groupKeys)&&(row.groupKeys as unknown[]).includes(group.key)).length}</td></tr>)}</tbody></table>{!groups.length&&<p className="p-4 text-sm text-slate-500">No matching records.</p>}</div>:
    <div className="max-h-72 overflow-auto"><table className="w-full min-w-max text-sm"><thead className="bg-slate-50"><tr>{config.columns.slice(0,3).map(column=><th className="px-4 py-2 text-left" key={column}>{reportRegistry[result.reportType].columns[column]}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((row,index)=><tr className="border-t" key={String(row.id??index)}>{config.columns.slice(0,3).map(column=><td className="max-w-56 truncate px-4 py-2" key={column}>{printable(row[column])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-sm text-slate-500">No matching records.</p>}</div>}
  </section>;
}

export default async function HomePage({searchParams}:{searchParams:Promise<{currency?:string;customize?:string;saved?:string}>}){
  const actor=await currentUser(),params=await searchParams,effective=await getEffectiveDashboardLayout(prisma,actor);
  const reportItems=effective.configuration.items.filter((item):item is Extract<DashboardLayoutItem,{kind:'SAVED_REPORT'}>=>item.kind==='SAVED_REPORT');
  const savedReports=await prisma.reportDefinition.findMany({where:savedReportWhere(actor),select:{id:true,name:true,reportType:true,configuration:true},orderBy:{name:'asc'}});
  if(params.customize==='1')return <Content><PageHeader eyebrow="Dashboard" title="Customize Dashboard" description="Choose, order, and size the widgets shown on your Dashboard." action={<Link className="btn-secondary" href="/">Dashboard</Link>}/><DashboardEditor initial={effective.configuration} widgets={availableDashboardWidgets(actor)} reports={savedReports.map(report=>({id:report.id,name:report.name,reportType:reportRegistry[report.reportType].label,grouped:!!validateReportConfiguration(report.reportType,report.configuration).groupBy}))} action={savePersonalDashboardAction} cancelHref="/" submitLabel="Save Dashboard"/><form action={resetPersonalDashboardAction} className="mt-3"><button className="text-sm font-semibold text-orange-800 underline">Reset to Role Default</button></form></Content>;

  const keys=new Set(effective.configuration.items.filter((item):item is Extract<DashboardLayoutItem,{kind:'BUILTIN'}>=>item.kind==='BUILTIN').map(item=>item.key));
  const salesData=['FORECAST_SUMMARY','PIPELINE_BY_REP','PIPELINE_BY_STAGE','PIPELINE_BY_PRODUCT_CATEGORY','CLOSING_OPPORTUNITIES'].some(key=>keys.has(key as never));
  const now=new Date(),period=dashboardPeriod(now);
  const currencies=salesData?await prisma.currency.findMany({where:{active:true},select:{code:true},orderBy:{code:'asc'}}):[];
  const currency=currencies.some(value=>value.code===params.currency)?params.currency!:currencies.some(value=>value.code==='USD')?'USD':currencies[0]?.code??'USD';
  const reps=salesData?(actor.role==='SALES'?[{id:actor.id,firstName:'Me',lastName:'',role:actor.role}]:await prisma.user.findMany({where:{active:true,archivedAt:null,role:{in:['SALES','SALES_MANAGER']}},select:{id:true,firstName:true,lastName:true,role:true},orderBy:[{lastName:'asc'},{firstName:'asc'}]})):[];
  const ids=reps.map(rep=>rep.id);
  const forecast=salesData?(actor.role==='SALES'?await forecastForRep(prisma,actor,{userId:actor.id,...period,currencyCode:currency}):await forecastForTeam(prisma,actor,{users:reps,...period,currencyCode:currency})):null;
  const config=defaultReportConfiguration('PIPELINE');config.filters=[{field:'status',operator:'eq',value:'OPEN'},{field:'closeDate',operator:'preset',value:'THIS_QUARTER'},{field:'currency',operator:'eq',value:currency},{field:'forecastCategory',operator:'eq',value:'IN_FORECAST'}];if(actor.role!=='SALES')config.filters.push({field:'activeSalesRep',operator:'eq',value:true});
  const report=(groupBy:'stage'|'owner'|'productCategory')=>executePipelineReport(prisma,actor,{...config,groupBy},now);
  const [stage,categories]=salesData?await Promise.all([report('stage'),keys.has('PIPELINE_BY_PRODUCT_CATEGORY')?report('productCategory'):null]):[null,null];
  const settings=keys.has('STALE_ACCOUNTS')?await getSettings(prisma):null;
  const [accounts,tasks,activities,myTradeShowLeads,marketingCounts,executedReports]=await Promise.all([
    keys.has('STALE_ACCOUNTS')?prisma.account.findMany({where:dashboardAccountWhere(actor),select:{id:true,name:true,activities:{where:operationalActivityWhere,orderBy:latestAccountActivityOrder(),take:1,select:{activityDate:true}}},orderBy:{name:'asc'}}):[],
    keys.has('OVERDUE_TASKS')?prisma.task.findMany({where:dashboardTaskWhere(actor,dayBounds(now).start,ids.length?ids:[actor.id]),select:{id:true,subject:true,dueDate:true},orderBy:[{dueDate:'asc'},{id:'asc'}],take:6}):[],
    keys.has('RECENT_ACTIVITY')?prisma.activity.findMany({where:dashboardActivityWhere(actor,ids),select:{id:true,subject:true,activityDate:true,account:{select:{name:true}}},orderBy:[{activityDate:'desc'},{id:'desc'}],take:6}):[],
    keys.has('MY_TRADE_SHOW_LEADS')?Promise.all([prisma.tradeShowLead.count({where:salesLeadQueueWhere(actor)}),prisma.tradeShowLead.count({where:salesLeadQueueWhere(actor,{status:'NEW'})}),prisma.tradeShowLead.findMany({where:salesLeadQueueWhere(actor),select:{id:true,tradeShowId:true,firstName:true,lastName:true,sourceCompany:true,status:true,tradeShow:{select:{name:true}}},orderBy:[{followUpAt:'asc'},{updatedAt:'desc'}],take:5})]):null,
    keys.has('MARKETING_SUMMARY')?Promise.all([prisma.account.count({where:{archivedAt:null,status:'ACTIVE'}}),prisma.tradeShowLead.count({where:{tradeShow:{archivedAt:null}}}),prisma.tradeShowLead.count({where:{tradeShow:{archivedAt:null},routing:'MARKETING_FOLLOW_UP'}}),prisma.tradeShowLead.count({where:{tradeShow:{archivedAt:null},routing:'REFERRED_TO_PARTNER'}})]):null,
    Promise.allSettled(reportItems.map(async item=>{const definition=savedReports.find(report=>report.id===item.reportId);if(!definition)throw new Error('Unavailable');const validated=validateReportConfiguration(definition.reportType,definition.configuration);return {item,definition,config:validated,result:await executeReport(prisma,actor,definition.reportType,validated,now)};})),
  ]);
  const stale=settings?accounts.filter(account=>hasNoActivityInDays(account.activities[0]?.activityDate??null,settings.STALE_ACCOUNT_WARNING_DAYS,now)):[];
  const drill=(groupBy?:'owner'|'stage'|'productCategory',commit=false)=>pipelineReportHref({currency,groupBy,commit,team:actor.role!=='SALES'}).replace('/reports/new?',actor.role==='READ_ONLY'?'/reports/pipeline-view?':'/reports/new?');
  const reportResults=new Map(executedReports.map((result,index)=>[reportItems[index].reportId,result]));
  const render=(item:DashboardLayoutItem)=>{
    if(item.kind==='SAVED_REPORT'){const execution=reportResults.get(item.reportId);return execution?.status==='fulfilled'?<SavedReportWidget name={execution.value.definition.name} title={item.title} style={item.style} config={execution.value.config} result={execution.value.result} reportId={item.reportId}/>:<section className="panel p-4"><h2 className="font-semibold">{item.title??'Saved Report'}</h2><p className="mt-2 text-sm text-slate-500">Report unavailable.</p><Link className="mt-3 inline-block text-sm text-orange-800 underline" href="/?customize=1">Manage Dashboard</Link></section>;}
    const title=dashboardWidgetRegistry[item.key].title;
    if(item.key==='FORECAST_SUMMARY'&&forecast){const cards=[['Pipeline',money(forecast.pipeline,currency),drill()],['Weighted Pipeline',money(forecast.weightedPipeline,currency),drill()],['Commit',money(forecast.commit,currency),drill(undefined,true)],['Quarterly Target',money(forecast.target,currency),'/reports/forecast'],['Pipeline Coverage',ratio(forecast.pipelineCoverage),'/reports/forecast'],['Weighted Coverage',ratio(forecast.weightedCoverage),'/reports/forecast'],['Commit Coverage',ratio(forecast.commitCoverage),'/reports/forecast']];return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,href])=><Link href={href} key={label} className="panel p-4 hover:border-orange-300"><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{value}</p></Link>)}</div>;}
    if(item.key==='PIPELINE_BY_REP'&&forecast&&'reps' in forecast)return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">{title}</h2><Link className="text-sm text-orange-800 underline" href="/reports/forecast">View forecast</Link></div><div className="overflow-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50"><tr>{['Sales rep','Pipeline','Weighted Pipeline','Commit','Target','Pipeline Coverage','Weighted Coverage','Commit Coverage'].map(value=><th className="px-4 py-2 text-left" key={value}>{value}</th>)}</tr></thead><tbody>{forecast.reps.map(rep=>{const user=reps.find(value=>value.id===rep.userId);return <tr className="border-t" key={rep.userId}><td className="px-4 py-2"><Link className="text-orange-800 underline" href={`/reports/forecast?userId=${rep.userId}&year=${period.year}&quarter=${period.quarter}&currencyCode=${currency}`}>{user?.firstName} {user?.lastName}</Link></td><td className="px-4 py-2">{money(rep.pipeline,currency)}</td><td className="px-4 py-2">{money(rep.weightedPipeline,currency)}</td><td className="px-4 py-2">{money(rep.commit,currency)}</td><td className="px-4 py-2">{rep.targetStatus==='MISSING_TARGET'?'Missing Target':money(rep.target,currency)}</td><td className="px-4 py-2">{ratio(rep.pipelineCoverage)}</td><td className="px-4 py-2">{ratio(rep.weightedCoverage)}</td><td className="px-4 py-2">{ratio(rep.commitCoverage)}</td></tr>;})}</tbody></table></div></section>;
    if(item.key==='PIPELINE_BY_STAGE'&&stage)return <SummaryTable title={title} result={stage} currency={currency} href={drill('stage')}/>;
    if(item.key==='PIPELINE_BY_PRODUCT_CATEGORY'&&categories)return <SummaryTable title={title} result={categories} currency={currency} href={drill('productCategory')}/>;
    if(item.key==='CLOSING_OPPORTUNITIES'&&stage)return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">{title}</h2><Link className="text-sm text-orange-800 underline" href={drill()}>View report</Link></div><div className="overflow-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50"><tr>{['Opportunity','Account','Owner','Stage','Value','Close date'].map(value=><th className="px-4 py-2 text-left" key={value}>{value}</th>)}</tr></thead><tbody>{stage.rows.slice(0,8).map(row=><tr className="border-t" key={row.id}><td className="px-4 py-2"><Link className="text-orange-800 underline" href={`/opportunities/${row.id}`}>{row.opportunity}</Link></td><td className="px-4 py-2">{row.accounts}</td><td className="px-4 py-2">{row.owner}</td><td className="px-4 py-2">{row.stage}</td><td className="px-4 py-2">{money(row.value,currency)}</td><td className="px-4 py-2">{row.closeDate??'—'}</td></tr>)}</tbody></table>{!stage.rows.length&&<p className="p-4 text-sm text-slate-500">No Opportunities closing this quarter.</p>}</div></section>;
    if(item.key==='STALE_ACCOUNTS')return <section className="panel p-4"><h2 className="font-semibold">{title}</h2><p className="mt-1 text-sm text-slate-600">{stale.length} active Accounts</p><ul className="mt-3 divide-y text-sm">{stale.slice(0,5).map(account=><li className="py-2" key={account.id}><Link className="text-orange-800 underline" href={`/accounts/${account.id}`}>{account.name}</Link></li>)}</ul><Link className="mt-3 inline-block text-sm text-orange-800 underline" href={`/reports/new?reportType=ACCOUNT_ACTIVITY&configured=1&minDays=${settings?.STALE_ACCOUNT_WARNING_DAYS}`}>View Account engagement</Link></section>;
    if(item.key==='OVERDUE_TASKS')return <section className="panel p-4"><h2 className="font-semibold">{title}</h2><ul className="mt-3 divide-y text-sm">{tasks.map(task=><li className="py-2" key={task.id}><Link className="text-orange-800 underline" href={`/tasks/${task.id}`}>{task.subject}</Link><span className="ml-2 text-slate-500">{task.dueDate?.toISOString().slice(0,10)}</span></li>)}</ul>{!tasks.length&&<p className="mt-3 text-sm text-slate-500">No overdue Tasks.</p>}<Link className="mt-3 inline-block text-sm text-orange-800 underline" href={actor.role==='SALES'||actor.role==='MARKETING_MANAGER'?`/tasks?assignedToId=${actor.id}`:'/tasks'}>View Tasks</Link></section>;
    if(item.key==='RECENT_ACTIVITY')return <section className="panel p-4"><h2 className="font-semibold">{title}</h2><ul className="mt-3 divide-y text-sm">{activities.map(activity=><li className="py-2" key={activity.id}><span className="font-medium">{activity.subject}</span><span className="ml-2 text-slate-500">{activity.account?.name} · {activity.activityDate.toISOString().slice(0,10)}</span></li>)}</ul>{!activities.length&&<p className="mt-3 text-sm text-slate-500">No recent Activities.</p>}</section>;
    if(item.key==='MY_TRADE_SHOW_LEADS'&&myTradeShowLeads){const [total,newCount,leads]=myTradeShowLeads;return <section className="panel p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold">{title}</h2><Link className="text-sm text-orange-800 underline" href="/trade-shows/my-leads">Open queue</Link></div><div className="mt-3 flex gap-5 text-sm"><span><strong className="text-xl tabular-nums">{total}</strong> active</span><span><strong className="text-xl tabular-nums">{newCount}</strong> not yet contacted</span></div><ul className="mt-3 divide-y text-sm">{leads.map(lead=><li className="py-2" key={lead.id}><Link className="font-medium text-orange-800 underline" href={`/trade-shows/${lead.tradeShowId}/leads/${lead.id}`}>{lead.firstName} {lead.lastName}</Link><span className="ml-2 text-slate-500">{lead.sourceCompany??lead.tradeShow.name} · {lead.status}</span></li>)}</ul>{!leads.length&&<p className="mt-3 text-sm text-slate-500">No actionable Trade Show leads assigned.</p>}</section>}
    if(item.key==='MARKETING_SUMMARY'&&marketingCounts)return <section className="panel p-4"><div className="flex items-center justify-between"><h2 className="font-semibold">{title}</h2><Link className="text-sm text-orange-800 underline" href="/reports/trade-shows">Trade Show reports</Link></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Active Accounts',marketingCounts[0],'/accounts'],['Trade Show Leads',marketingCounts[1],'/trade-shows'],['Marketing Follow-Up',marketingCounts[2],'/reports/new?reportType=TRADE_SHOW&routing=MARKETING_FOLLOW_UP'],['Partner-Referred Leads',marketingCounts[3],'/reports/new?reportType=TRADE_SHOW&routing=REFERRED_TO_PARTNER']].map(([label,value,href])=><Link className="rounded-md border p-3 hover:border-orange-300" href={String(href)} key={String(label)}><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></Link>)}</div></section>;
    if(item.key==='ADMIN_SHORTCUTS')return <section className="panel p-4"><h2 className="font-semibold">{title}</h2><div className="mt-3 flex flex-wrap gap-4 text-sm">{[['Users','/administration/users'],['Sales Targets','/administration/sales-targets'],['Imports','/administration/imports'],['Dashboard Views','/administration/dashboard-views']].map(([label,href])=><Link className="text-orange-800 underline" href={href} key={href}>{label}</Link>)}</div></section>;
    return null;
  };
  const dashboardSections=dashboardPresentationSectionKeys.map(section=>({section,items:effective.configuration.items.filter(item=>dashboardItemPresentationSection(item)===section)})).filter(group=>group.items.length);
  const feedback=params.saved==='dashboard'?'Dashboard updated.':params.saved==='dashboard-reset'?'Dashboard reset to your role default.':null;
  return <Content><PageHeader eyebrow="BIXOLON SalesHub" title="Dashboard" description="Overview of current activity and business performance." action={<Link className="btn-secondary" href="/?customize=1">Customize Dashboard</Link>}/>{feedback&&<SaveSuccess message={feedback}/>}<div className="mb-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600"><p>{period.year} {period.quarter}{effective.personalized?' · Personalized':' · Role default'}</p>{salesData&&<form className="flex items-center gap-2"><label htmlFor="dashboard-currency">Currency</label><select id="dashboard-currency" className="field min-w-24" name="currency" defaultValue={currency}>{currencies.map(value=><option key={value.code}>{value.code}</option>)}</select><button className="btn-secondary">View</button></form>}</div><div className="space-y-6">{dashboardSections.map(group=><section className="space-y-3" key={group.section}><h2 className="border-b pb-2 text-xs font-semibold uppercase tracking-wide text-slate-600">{dashboardPresentationSectionTitles[group.section]}</h2><div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{group.items.map(item=><div className={span(item.size)} key={item.kind==='BUILTIN'?item.key:`report-${item.reportId}`}>{render(item)}</div>)}</div></section>)}</div>{!effective.configuration.items.length&&<section className="panel p-6 text-center"><p className="text-slate-600">No Dashboard widgets are selected.</p><Link className="mt-3 inline-block text-orange-800 underline" href="/?customize=1">Customize Dashboard</Link></section>}</Content>;
}
