import Link from 'next/link';
import { Content, PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { dashboardAccountWhere, dashboardActivityWhere, dashboardPeriod, dashboardTaskWhere, getDashboardViewForRole, pipelineReportHref } from '@/lib/dashboard';
import { forecastForRep, forecastForTeam } from '@/lib/forecast';
import { defaultReportConfiguration, executePipelineReport, type PipelineReportResult } from '@/lib/reporting';
import { hasNoActivityInDays, latestAccountActivityOrder } from '@/lib/engagement';
import { dashboardOpenTaskWhere, dayBounds } from '@/lib/work';
import { getSettings } from '@/lib/configuration';
import { formatCurrency } from '@/lib/display-format';

export const dynamic = 'force-dynamic';
const money = (value: string | null, currency: string) => value === null ? 'No target set' : formatCurrency(Number(value), currency);
const ratio = (value: string | null) => value === null ? '—' : `${value}x`;
function SummaryTable({ title, result, currency, href }: { title: string; result: PipelineReportResult; currency: string; href: string }) {
  return <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">{title}</h2><Link className="text-sm text-orange-800 underline" href={href}>View report</Link></div><div className="max-h-72 overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-4 py-2">{title.replace('Pipeline by ', '')}</th><th className="px-4 py-2 text-right">Deals</th><th className="px-4 py-2 text-right">Pipeline</th></tr></thead><tbody>{result.groups.map(group => { const metric = group.metrics.find(x => x.currency === currency); return <tr key={group.key} className="border-t even:bg-slate-50/60 hover:bg-orange-50/40"><td className="px-4 py-2">{group.label}</td><td className="px-4 py-2 text-right">{metric?.opportunityCount ?? 0}</td><td className="px-4 py-2 text-right tabular-nums">{money(metric?.pipeline ?? '0', currency)}</td></tr>; })}</tbody></table>{!result.groups.length && <p className="p-4 text-sm text-slate-500">No Opportunities this quarter.</p>}</div></section>;
}

export default async function HomePage({ searchParams }: { searchParams: Promise<{ currency?: string }> }) {
  const actor = await currentUser(), view = getDashboardViewForRole(actor);
  const show = (section: typeof view.sections[number]) => view.sections.includes(section);
  const now = new Date(), period = dashboardPeriod(now), params = await searchParams;
  if (show('marketing')) {
    const [accounts, tasks] = await Promise.all([
      prisma.account.count({ where: { archivedAt: null, status: 'ACTIVE' } }),
      prisma.task.count({ where: { ...dashboardOpenTaskWhere(), assignedToId: actor.id } }),
    ]);
    return <Content><PageHeader eyebrow="BIXOLON SalesHub" title="Dashboard" description="Marketing overview."/><div className="grid gap-3 sm:grid-cols-2"><Link className="panel p-5 hover:border-orange-300" href="/accounts"><p className="text-sm text-slate-600">Active Accounts</p><p className="mt-2 text-2xl font-semibold">{accounts}</p></Link><Link className="panel p-5 hover:border-orange-300" href={`/tasks?assignedToId=${actor.id}`}><p className="text-sm text-slate-600">My open Tasks</p><p className="mt-2 text-2xl font-semibold">{tasks}</p></Link></div></Content>;
  }
  const currencies = await prisma.currency.findMany({ where: { active: true }, select: { code: true }, orderBy: { code: 'asc' } });
  const currency = currencies.some(c => c.code === params.currency) ? params.currency! : currencies.some(c => c.code === 'USD') ? 'USD' : currencies[0]?.code ?? 'USD';
  const reps = actor.role === 'SALES' ? [{ id: actor.id, firstName: 'Me', lastName: '', role: actor.role }] : await prisma.user.findMany({ where: { active: true, archivedAt: null, role: { in: ['SALES','SALES_MANAGER'] } }, select: { id: true, firstName: true, lastName: true, role: true }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] });
  const ids = reps.map(rep => rep.id);
  const forecast = actor.role === 'SALES'
    ? await forecastForRep(prisma, actor, { userId: actor.id, ...period, currencyCode: currency })
    : await forecastForTeam(prisma, actor, { users: reps, ...period, currencyCode: currency });
  const config = defaultReportConfiguration('PIPELINE');
  config.filters = [{ field: 'status', operator: 'eq', value: 'OPEN' }, { field: 'closeDate', operator: 'preset', value: 'THIS_QUARTER' }, { field: 'currency', operator: 'eq', value: currency }, { field: 'forecastCategory', operator: 'eq', value: 'IN_FORECAST' }];
  if (actor.role !== 'SALES') config.filters.push({ field: 'activeSalesRep', operator: 'eq', value: true });
  const report = (groupBy: 'stage'|'owner'|'productCategory') => executePipelineReport(prisma, actor, { ...config, groupBy }, now);
  const [stage, owners, categories] = await Promise.all([report('stage'), show('reps') ? report('owner') : null, show('category') ? report('productCategory') : null]);
  const settings = show('stale') ? await getSettings(prisma) : null;
  const [accounts, tasks, activities] = await Promise.all([
    show('stale') ? prisma.account.findMany({ where: dashboardAccountWhere(actor), select: { id: true, name: true, activities: { where: { archivedAt: null }, orderBy: latestAccountActivityOrder(), take: 1, select: { activityDate: true } } }, orderBy: { name: 'asc' } }) : [],
    show('tasks') ? prisma.task.findMany({ where: dashboardTaskWhere(actor, dayBounds(now).start, ids), select: { id: true, subject: true, dueDate: true }, orderBy: [{ dueDate: 'asc' }, { id: 'asc' }], take: 6 }) : [],
    show('activities') ? prisma.activity.findMany({ where: dashboardActivityWhere(actor, ids), select: { id: true, subject: true, activityDate: true, account: { select: { name: true } } }, orderBy: [{ activityDate: 'desc' }, { id: 'desc' }], take: 6 }) : [],
  ]);
  const stale = settings ? accounts.filter(a => hasNoActivityInDays(a.activities[0]?.activityDate ?? null, settings.STALE_ACCOUNT_WARNING_DAYS, now)) : [];
  const drill = (groupBy?: 'owner'|'stage'|'productCategory', commit = false) => pipelineReportHref({ currency, groupBy, commit, team: actor.role !== 'SALES' }).replace('/reports/new?', actor.role === 'READ_ONLY' ? '/reports/pipeline-view?' : '/reports/new?');
  const cards = [
    ['Pipeline', money(forecast.pipeline,currency),drill()], ['Weighted Pipeline',money(forecast.weightedPipeline,currency),drill()], ['Commit',money(forecast.commit,currency),drill(undefined,true)], ['Quarterly Target',money(forecast.target,currency),'/reports/forecast'],
    ['Pipeline Coverage',ratio(forecast.pipelineCoverage),'/reports/forecast'], ['Weighted Coverage',ratio(forecast.weightedCoverage),'/reports/forecast'], ['Commit Coverage',ratio(forecast.commitCoverage),'/reports/forecast'],
  ];
  return <Content><PageHeader eyebrow="BIXOLON SalesHub" title="Dashboard" description="Overview of current sales activity and pipeline."/>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600"><p>{view.title} · {period.year} {period.quarter} · Expected close date</p><form method="get" className="flex items-center gap-2"><label htmlFor="dashboard-currency">Currency</label><select id="dashboard-currency" className="field min-w-24" name="currency" defaultValue={currency}>{currencies.map(c => <option key={c.code}>{c.code}</option>)}</select><button className="btn-secondary">View</button></form></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label,value,href]) => <Link href={href} key={label} className="panel p-4 hover:border-orange-300"><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{value}</p></Link>)}</div>
    {forecast.targetStatus !== 'SET' && <p className="mt-3 text-sm text-slate-600">{forecast.targetStatus === 'NO_TARGET' ? 'No target is set' : forecast.targetStatus === 'PARTIAL_TARGET' ? 'One or more Sales users have a Missing Target' : 'Target is zero'} for {currency}; coverage is unavailable.</p>}
    {show('reps') && 'reps' in forecast && <section className="panel mt-5 overflow-x-auto"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">Sales rep forecast</h2><Link className="text-sm text-orange-800 underline" href="/reports/forecast">View forecast</Link></div><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Sales rep','Pipeline','Weighted Pipeline','Commit','Target','Pipeline Coverage','Weighted Coverage','Commit Coverage'].map(x => <th className="px-4 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{forecast.reps.map(rep => { const user = reps.find(x => x.id === rep.userId); return <tr key={rep.userId} className="border-t even:bg-slate-50/60 hover:bg-orange-50/40"><td className="px-4 py-2"><Link className="text-orange-800 underline" href={`/reports/forecast?userId=${rep.userId}&year=${period.year}&quarter=${period.quarter}&currencyCode=${currency}`}>{user?.firstName} {user?.lastName}</Link></td><td className="px-4 py-2">{money(rep.pipeline,currency)}</td><td className="px-4 py-2">{money(rep.weightedPipeline,currency)}</td><td className="px-4 py-2">{money(rep.commit,currency)}</td><td className="px-4 py-2">{rep.targetStatus === 'MISSING_TARGET' ? 'Missing Target' : money(rep.target,currency)}</td><td className="px-4 py-2">{ratio(rep.pipelineCoverage)}</td><td className="px-4 py-2">{ratio(rep.weightedCoverage)}</td><td className="px-4 py-2">{ratio(rep.commitCoverage)}</td></tr>; })}</tbody></table></section>}
    <div className="mt-5 grid gap-4 lg:grid-cols-2">{show('stage') && <SummaryTable title="Pipeline by Stage" result={stage} currency={currency} href={drill('stage')}/ >}{owners && <SummaryTable title="Pipeline by Sales Rep" result={owners} currency={currency} href={drill('owner')}/ >}{categories && <SummaryTable title="Pipeline by Product Category" result={categories} currency={currency} href={drill('productCategory')}/ >}</div>
    {show('closing') && <section className="panel mt-5 overflow-x-auto"><div className="flex items-center justify-between border-b px-4 py-3"><h2 className="font-semibold">Opportunities closing this quarter</h2><Link className="text-sm text-orange-800 underline" href={drill()}>View report</Link></div><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Opportunity','Account','Owner','Stage','Forecast','Value','Close date'].map(x => <th className="px-4 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{stage.rows.slice(0,8).map(row => <tr key={row.id} className="border-t even:bg-slate-50/60 hover:bg-orange-50/40"><td className="px-4 py-2"><Link className="text-orange-800 underline" href={`/opportunities/${row.id}`}>{row.opportunity}</Link></td><td className="px-4 py-2">{row.accounts}</td><td className="px-4 py-2">{row.owner}</td><td className="px-4 py-2">{row.stage}</td><td className="px-4 py-2">{row.forecastCategory.replace('_',' ')}</td><td className="px-4 py-2">{money(row.value,currency)}</td><td className="px-4 py-2">{row.closeDate ?? '—'}</td></tr>)}</tbody></table>{!stage.rows.length && <p className="p-4 text-sm text-slate-500">No Opportunities closing this quarter.</p>}</section>}
    <div className="mt-5 grid gap-4 lg:grid-cols-3">{show('stale') && <section className="panel p-4"><h2 className="font-semibold">Accounts with no activity {settings?.STALE_ACCOUNT_WARNING_DAYS}+ days</h2><p className="mt-1 text-sm text-slate-600">{stale.length} active Accounts</p><ul className="mt-3 divide-y text-sm">{stale.slice(0,5).map(a => <li className="py-2" key={a.id}><Link className="text-orange-800 underline" href={`/accounts/${a.id}`}>{a.name}</Link></li>)}</ul><Link className="mt-3 inline-block text-sm text-orange-800 underline" href={`/reports/new?reportType=ACCOUNT_ACTIVITY&configured=1&minDays=${settings?.STALE_ACCOUNT_WARNING_DAYS}`}>View Account engagement</Link></section>}
    {show('tasks') && <section className="panel p-4"><h2 className="font-semibold">Overdue Tasks</h2><ul className="mt-3 divide-y text-sm">{tasks.map(t => <li className="py-2" key={t.id}><Link className="text-orange-800 underline" href={`/tasks/${t.id}`}>{t.subject}</Link><span className="ml-2 text-slate-500">{t.dueDate?.toISOString().slice(0,10)}</span></li>)}</ul>{!tasks.length && <p className="mt-3 text-sm text-slate-500">No overdue Tasks.</p>}<Link className="mt-3 inline-block text-sm text-orange-800 underline" href={actor.role === 'SALES' ? `/tasks?assignedToId=${actor.id}` : '/tasks'}>View Tasks</Link></section>}
    {show('activities') && <section className="panel p-4"><h2 className="font-semibold">Recent Activities</h2><ul className="mt-3 divide-y text-sm">{activities.map(a => <li className="py-2" key={a.id}><span className="font-medium">{a.subject}</span><span className="ml-2 text-slate-500">{a.account?.name} · {a.activityDate.toISOString().slice(0,10)}</span></li>)}</ul>{!activities.length && <p className="mt-3 text-sm text-slate-500">No recent Activities.</p>}</section>}</div>
    {show('admin') && <div className="mt-5 flex flex-wrap gap-3 text-sm"><Link className="text-orange-800 underline" href="/administration/users">Users</Link><Link className="text-orange-800 underline" href="/administration/sales-targets">Sales Targets</Link><Link className="text-orange-800 underline" href="/administration/imports">Imports</Link></div>}
  </Content>;
}
