import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Content,PageHeader } from '@/components/shell';
import { ReportCloseDateFields } from '@/components/report-close-date-fields';
import { ReportResults } from '@/components/report-results';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { canCreateReport, canEditReportDefinition, canShareReport, canViewReportDefinition, executePipelineReport, getCreatableReportTypes } from '@/lib/reporting';
import { filterValue,pipelineConfigFromParams } from '@/lib/report-builder';
import { saveReportAction } from '../actions';
export const dynamic='force-dynamic';
type Params=Record<string,string|string[]|undefined>;
const selected=(config:ReturnType<typeof pipelineConfigFromParams>,name:string)=>String(filterValue(config,name)??'');
export default async function NewReportPage({searchParams}:{searchParams:Promise<Params>}){const params=await searchParams,actor=await currentUser();if(!getCreatableReportTypes(actor).includes('PIPELINE'))notFound();const reportId=Number(Array.isArray(params.reportId)?params.reportId[0]:params.reportId);const saved=Number.isSafeInteger(reportId)&&reportId>0?await prisma.reportDefinition.findUnique({where:{id:reportId}}):null;if(saved&&(!canViewReportDefinition(actor,saved)||!canEditReportDefinition(actor,saved)))notFound();const config=pipelineConfigFromParams(params,saved?.configuration);const [result,owners,stages,accounts,categories,projects,currencies]=await Promise.all([executePipelineReport(prisma,actor,config),prisma.user.findMany({where:{active:true,archivedAt:null,...(actor.role==='SALES'?{id:actor.id}:{})},orderBy:[{lastName:'asc'},{firstName:'asc'}]}),prisma.salesStage.findMany({orderBy:[{sortOrder:'asc'},{id:'asc'}]}),prisma.account.findMany({where:{archivedAt:null,status:'ACTIVE',...(actor.role==='SALES'?{ownerId:actor.id}:{})},select:{id:true,name:true},orderBy:{name:'asc'}}),prisma.productCategory.findMany({where:{active:true},orderBy:{name:'asc'}}),prisma.project.findMany({where:{archivedAt:null},orderBy:{name:'asc'}}),prisma.currency.findMany({where:{active:true},orderBy:{code:'asc'}})]);const preset=String(config.filters.find(x=>x.field==='closeDate'&&x.operator==='preset')?.value??'');const between=config.filters.find(x=>x.field==='closeDate'&&x.operator==='between')?.value as {from:string;to:string}|undefined;return <Content><PageHeader eyebrow="Reports" title={saved?'Edit Pipeline Report':'Pipeline Report'} description="Build and preview an Opportunity report using current SalesHub data." action={<Link className="btn-secondary" href="/reports">Reports</Link>}/>
 <form method="get" className="panel space-y-5 p-5">
  <input type="hidden" name="configured" value="1"/>{config.filters.some(filter => filter.field === 'activeSalesRep') && <input type="hidden" name="activeSalesRep" value="1"/>}{saved&&<input type="hidden" name="reportId" value={saved.id}/>}
  <fieldset><legend className="mb-3 text-base font-semibold">Opportunity filters</legend><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
   <label className="label">Status<select className="field" name="status" defaultValue={selected(config,'status')}><option value="">Any</option><option value="OPEN">Open</option><option value="WON">Closed Won</option><option value="LOST">Closed Lost</option></select></label>
   <label className="label">Sales Rep<select className="field" name="ownerId" defaultValue={selected(config,'ownerId')}><option value="">All permitted</option>{owners.map(x=><option value={x.id} key={x.id}>{x.firstName} {x.lastName}</option>)}</select></label>
   <label className="label">Stage<select className="field" name="stageId" defaultValue={selected(config,'stageId')}><option value="">All</option>{stages.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
   <label className="label">Forecast Category<select className="field" name="forecastCategory" defaultValue={selected(config,'forecastCategory')}><option value="">All</option><option value="IN_FORECAST">In forecast</option>{['PIPELINE','BEST_CASE','COMMIT','OMITTED','CLOSED'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label>
   <label className="label">Account<select className="field" name="accountId" defaultValue={selected(config,'accountId')}><option value="">All</option>{accounts.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
  </div></fieldset>
  <fieldset className="border-t border-slate-200 pt-5"><legend className="mb-3 pr-3 text-base font-semibold">Scope and commercial filters</legend><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
   <label className="label">Product Category<select className="field" name="productCategoryId" defaultValue={selected(config,'productCategoryId')}><option value="">All</option>{categories.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
   <label className="label">Project<select className="field" name="projectId" defaultValue={selected(config,'projectId')}><option value="">All</option>{projects.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
   <label className="label">Currency<select className="field" name="currency" defaultValue={selected(config,'currency')}><option value="">All currencies</option>{currencies.map(x=><option value={x.code} key={x.code}>{x.code}</option>)}</select></label>
   <ReportCloseDateFields initialChoice={between?'CUSTOM':preset||'ANY'} initialFrom={between?.from} initialTo={between?.to}/>
  </div></fieldset>
  <fieldset className="border-t border-slate-200 pt-5"><legend className="mb-3 pr-3 text-base font-semibold">Display options</legend><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
   <label className="label">Group By<select className="field" name="groupBy" defaultValue={config.groupBy??''}><option value="">None</option>{Object.entries({owner:'Sales Rep',stage:'Stage',account:'Account',industry:'Industry',territory:'Territory',productCategory:'Product Category',project:'Project'}).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
   <label className="label">Sort<select className="field" name="sortField" defaultValue={config.sort[0]?.field??'closeDate'}>{Object.entries({closeDate:'Close Date',opportunity:'Opportunity',account:'Account',owner:'Owner',stage:'Stage',value:'Value'}).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>
   <label className="label">Sort Direction<select className="field" name="sortDirection" defaultValue={config.sort[0]?.direction??'asc'}><option value="asc">Ascending</option><option value="desc">Descending</option></select></label>
  </div></fieldset>
  <fieldset className="rounded-md border border-orange-200 bg-orange-50/50 p-4"><legend className="px-1 text-base font-semibold text-slate-900">Metrics</legend><div className="mt-1 flex flex-wrap gap-x-5 gap-y-3">{Object.entries({pipeline:'Pipeline',weightedPipeline:'Weighted Pipeline',opportunityCount:'Opportunity Count',averageOpportunityValue:'Average Value'}).map(([value,label])=><label className="text-sm" key={value}><input className="mr-2" type="checkbox" name="metrics" value={value} defaultChecked={config.metrics.includes(value)}/>{label}</label>)}</div></fieldset>
  <fieldset className="border-t border-slate-200 pt-4"><legend className="pr-3 text-sm font-semibold text-slate-700">Columns shown in details</legend><div className="mt-2 flex flex-wrap gap-x-5 gap-y-3">{Object.entries({opportunity:'Opportunity',account:'Account',owner:'Owner',stage:'Stage',closeDate:'Close Date',value:'Value',weightedValue:'Weighted Value',currency:'Currency'}).map(([value,label])=><label className="text-sm" key={value}><input className="mr-2" type="checkbox" name="columns" value={value} defaultChecked={config.columns.includes(value)}/>{label}</label>)}</div></fieldset>
  <div className="border-t border-slate-200 pt-4"><button className="btn-primary">Preview</button></div>
 </form>
 <ReportResults result={result} config={config} groupKey={typeof params.group==='string'?params.group:undefined}/>
 {canCreateReport(actor)&&<form action={saveReportAction} className="panel mt-6 grid gap-4 p-5 sm:grid-cols-2"><div className="border-b border-slate-200 pb-4 sm:col-span-2"><h2 className="text-lg font-semibold">Save This Report</h2><p className="mt-1 text-sm text-slate-600">Save the current filters, metrics, and detail columns for future use.</p></div><input type="hidden" name="reportType" value="PIPELINE"/><input type="hidden" name="configuration" value={JSON.stringify(config)}/>{saved&&<input type="hidden" name="reportId" value={saved.id}/>}<label className="label">Report name<input className="field" name="name" required maxLength={120} defaultValue={saved?.name??''}/></label><label className="label">Visibility<select className="field" name="visibility" defaultValue={saved?.visibility??'PERSONAL'}><option value="PERSONAL">Personal</option>{canShareReport(actor)&&<option value="SHARED">Shared</option>}</select></label><label className="label sm:col-span-2">Description<textarea className="field" name="description" maxLength={1000} defaultValue={saved?.description??''}/></label><div><button className="btn-primary">{saved?'Save changes':'Save report'}</button></div></form>}
 </Content>}
