"use client";
import { useSubmitGuard } from "@/lib/submit-guard";
import Link from "next/link";
import { useActionState, useState } from "react";
import { submitContact, type FormState } from "@/app/contacts/actions";
import { createContactForTradeShowLead } from "@/app/trade-shows/[id]/leads/[leadId]/resolve/actions";
import { createResolutionContactAction } from "@/app/trade-shows/[id]/contact-resolution/actions";
import { AddressFields } from "@/components/address-fields";
import { addressFields, hasAddress, type Address } from "@/lib/address";
import type { MarketingPreference } from "@prisma/client";
type Initial = Address & { accountId: number | null; useAccountAddress?: boolean | null; firstName: string; lastName: string; title: string | null; email: string | null; phone: string | null; mobile: string | null; active: boolean; isPrimary: boolean; marketingPreference?: MarketingPreference };
type AccountOption = Address & { id: number; name: string };
export function ContactForm({ id, initial, accounts, accountId, leadContext, resolutionContext }: { id?: number; initial?: Initial; accounts: AccountOption[]; accountId?: number; leadContext?: {tradeShowId:number;leadId:number}; resolutionContext?:{tradeShowId:number;leadId:number;returnTo?:string} }) {
  const sourceContext=resolutionContext??leadContext;
  const submit: (state: FormState, form: FormData) => Promise<FormState> = resolutionContext ? createResolutionContactAction.bind(null,resolutionContext.tradeShowId,resolutionContext.leadId,resolutionContext.returnTo??"") : leadContext ? createContactForTradeShowLead.bind(null,leadContext.tradeShowId,leadContext.leadId) : submitContact.bind(null, id ?? null, id ? null : accountId ?? null);
  const [state, action, pending] = useActionState(submit, { errors: {} } as FormState);
  const guard = useSubmitGuard(state);
  const retained=(key:string,fallback:string|number|boolean|null|undefined="")=>state.values?.[key]??String(fallback??"");
  const [selectedAccountId, setSelectedAccountId] = useState(retained("accountId",initial?.accountId ?? accountId));
  const [addressMode, setAddressMode] = useState<"account" | "different">(() => state.values?.addressMode === "account" ? "account" : state.values?.addressMode === "different" || (initial && (initial.useAccountAddress === false || initial.useAccountAddress === null && hasAddress(initial))) ? "different" : "account");
  const selectedAccount = accounts.find(account => String(account.id) === selectedAccountId);
  const effectiveMode = selectedAccountId ? addressMode : "different";
  const error = (key: string) => state.errors[key] && <p className="mt-1 text-sm text-red-700">{state.errors[key]}</p>;
  return <form key={state.reviewToken ?? 'contact'} action={action} onSubmit={guard} className="panel max-w-4xl p-6" aria-label={id ? "Edit contact" : "Create contact"}>
    {state.message && <p role="alert" className="mb-5 rounded bg-red-50 p-3 text-sm text-red-800">{state.message}</p>}
    {!!state.matches?.length && <section className="mb-5 rounded border border-amber-300 bg-amber-50 p-4 text-sm" role="alert"><h2 className="font-semibold">Possible duplicate Contact found</h2><p className="mt-1">We found an existing Contact that may be the same person. Please review it before creating or saving this Contact.</p>{state.matches.some(match => match.reason === 'email') && <p className="mt-2 font-medium">A Contact with this email already exists.</p>}{state.matches.some(match => match.archived) && <p className="mt-2">An archived Contact may be available to restore. Review it before creating a new record.</p>}<ul className="mt-3 space-y-3">{state.matches.map(match => <li key={match.id} className="rounded border border-amber-200 bg-white p-3"><p className="font-medium">{match.name}{match.archived ? ' — Archived' : match.inactive ? ' — Inactive' : ''}</p><p className="text-slate-700">{match.email ?? 'No email'} · {match.accountName ?? 'No Account'}{match.title ? ` · ${match.title}` : ''}</p><p className="mt-1 text-slate-600">{match.reason === 'email' ? 'Same email address' : match.reason === 'same-account-name' ? 'Same name and Account' : 'Same name; at least one Contact has no Account'}</p><Link className="mt-2 inline-block font-medium text-orange-800 underline" href={`/contacts/${match.id}`} target="_blank" rel="noopener noreferrer">Open existing Contact</Link></li>)}</ul><p className="mt-3">If these are different people, you can continue after reviewing them.</p></section>}
    <div className="grid gap-5 sm:grid-cols-2">
      <div className="sm:col-span-2"><label className="label" htmlFor="accountId">Account (optional)</label><select className="field" name="accountId" id="accountId" value={selectedAccountId} onChange={event => setSelectedAccountId(event.target.value)} disabled={!!accountId && !id}><option value="">No account</option>{accounts.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}{initial?.accountId && !accounts.some((a) => a.id === initial.accountId) && <option value={initial.accountId}>Current account (inactive)</option>}</select>{!!accountId && !id && <input type="hidden" name="accountId" value={accountId}/>}{error("accountId")}</div>
      {([ ["firstName", "First name"], ["lastName", "Last name"], ["title", "Title"], ["email", "Email"], ["phone", "Office phone"], ["mobile", "Mobile phone"] ] as const).map(([key, label]) => <div key={key}><label className="label" htmlFor={key}>{label}{key === "firstName" || key === "lastName" ? " *" : ""}</label><input className="field" id={key} name={key} type={key === "email" ? "email" : key === "phone" || key === "mobile" ? "tel" : "text"} required={key === "firstName" || key === "lastName"} maxLength={key === "email" ? 254 : key === "title" ? 200 : key === "phone" || key === "mobile" ? 50 : 100} defaultValue={retained(key,initial?.[key])}/>{error(key)}</div>)}
      <div><label className="label" htmlFor="active">Status</label><select className="field" id="active" name="active" defaultValue={retained("active",initial?.active === false ? "false" : "true")}><option value="true">Active</option><option value="false">Inactive</option></select></div>
      {!sourceContext && <div><label className="label" htmlFor="marketingPreference">Marketing communications</label><select className="field" id="marketingPreference" name="marketingPreference" defaultValue={retained("marketingPreference",initial?.marketingPreference ?? "UNKNOWN")}><option value="UNKNOWN">Not specified</option><option value="OPTED_IN">Opted in</option><option value="OPTED_OUT">Opted out</option></select><p className="mt-1 text-xs text-slate-600">Record the Contact&apos;s preference for receiving marketing communications.</p><p className="mt-1 text-xs text-slate-600">Opted out: Do not include this Contact in marketing audience exports.</p></div>}
      {sourceContext && <><input type="hidden" name="marketingPreference" value="UNKNOWN"/><div className="rounded bg-slate-50 p-3 text-sm"><span className="font-semibold">Marketing communications</span><span className="block text-slate-600">Not specified</span></div></>}
      <label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input type="checkbox" name="isPrimary" defaultChecked={state.values?state.values.isPrimary==="true":initial?.isPrimary} className="accent-orange-700"/>Primary contact for selected account</label>{error("isPrimary")}
      <div className="sm:col-span-2 border-t border-slate-200 pt-5"><h2 className="text-base font-semibold">Location / Address</h2>{selectedAccountId && <div className="mt-3 space-y-2 text-sm"><label className="flex gap-2"><input type="radio" name="addressMode" value="account" checked={effectiveMode === "account"} onChange={() => setAddressMode("account")}/>Use Account address</label>{effectiveMode === "account" && <p className="ml-6 text-slate-600">{selectedAccount ? addressFields.map(([key]) => selectedAccount[key]).filter(Boolean).join(", ") || "No Account address saved" : "Account address unavailable"}</p>}<label className="flex gap-2"><input type="radio" name="addressMode" value="different" checked={effectiveMode === "different"} onChange={() => setAddressMode("different")}/>Use different address</label></div>}{!selectedAccountId && <input type="hidden" name="addressMode" value="different"/>}{effectiveMode === "account" && initial && hasAddress(initial) && <p className="mt-2 text-xs text-slate-600">Saved Contact address is kept. Choose “Use different address” later to use it again.</p>}</div>
      {effectiveMode === "different" && <AddressFields initial={{...initial,...Object.fromEntries(["addressLine1","addressLine2","city","stateProvince","postalCode","country"].map(key=>[key,retained(key,initial?.[key as keyof Initial] as string|null)]))} as Address} errors={state.errors}/>}
      {leadContext && <label className="sm:col-span-2 flex items-start gap-2 rounded bg-amber-50 p-3 text-sm"><input className="mt-1" type="checkbox" name="confirmDuplicate"/>I reviewed the exact-email matches shown above and explicitly want to create a new Contact.</label>}
    </div><div className="mt-7 flex justify-end gap-2"><Link href={resolutionContext ? `/trade-shows/${resolutionContext.tradeShowId}/contact-resolution${resolutionContext.returnTo?`?returnTo=${encodeURIComponent(resolutionContext.returnTo)}`:""}` : leadContext ? `/trade-shows/${leadContext.tradeShowId}/leads/${leadContext.leadId}/edit` : id ? `/contacts/${id}` : accountId ? `/accounts/${accountId}?tab=contacts` : "/contacts"} className="btn-secondary">Cancel</Link><button type="submit" className="btn-primary disabled:opacity-60" name={state.matches?.length ? 'reviewedContact' : undefined} value={state.reviewToken} disabled={pending}>{pending ? "Saving…" : state.matches?.length ? id ? "Save changes anyway" : "Create new Contact anyway" : id ? "Save contact" : "Create contact"}</button></div>
  </form>;
}
