"use client";
import Link from "next/link";
import { useActionState } from "react";
import type { MarketingAudienceConfig } from "@/lib/marketing-audiences";
import { saveAudience, type AudienceFormState } from "@/app/marketing/audiences/actions";

type Option={value:string|number;label:string};
type Props={audience?:{id:number;name:string;description:string|null;visibility:string;filterConfig:MarketingAudienceConfig};options:{accounts:Option[];industries:Option[];territories:Option[];users:Option[];partners:Option[];tradeShows:Option[];competitors:Option[]}};
function Select({name,label,value,children}:{name:string;label:string;value?:string|number|boolean;children:React.ReactNode}){return <div><label className="label" htmlFor={name}>{label}</label><select className="field" id={name} name={name} defaultValue={value===undefined?"":String(value)}><option value="">Any</option>{children}</select></div>}
function Options({items}:{items:Option[]}){return <>{items.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</>}
export function MarketingAudienceForm({audience,options}:Props){
  const [state,action,pending]=useActionState(saveAudience,{} as AudienceFormState),c=audience?.filterConfig??{preference:"OPTED_IN"};
  return <form action={action} className="report-builder panel p-5 md:p-6" aria-label={audience?"Edit marketing audience":"Create marketing audience"}>
    {audience&&<input type="hidden" name="audienceId" value={audience.id}/>} {state.message&&<p role="alert" className="rounded bg-red-50 p-3 text-sm text-red-800">{state.message}</p>}
    <section className="report-section"><h2 className="report-section-title">Audience</h2><div className="report-filter-grid"><div><label className="label" htmlFor="name">Name *</label><input className="field" id="name" name="name" required maxLength={120} defaultValue={audience?.name??""}/></div><div><label className="label" htmlFor="description">Description</label><input className="field" id="description" name="description" maxLength={1000} defaultValue={audience?.description??""}/></div><Select name="visibility" label="Visibility" value={audience?.visibility??"PERSONAL"}><option value="PERSONAL">Personal</option><option value="SHARED">Shared</option></Select></div></section>
    <section className="report-section report-primary-filters"><h2 className="report-section-title">Contact filters</h2><div className="report-filter-grid"><div><label className="label" htmlFor="search">Name or email</label><input className="field" id="search" name="search" defaultValue={c.search??""}/></div><div><label className="label" htmlFor="title">Title contains</label><input className="field" id="title" name="title" defaultValue={c.title??""}/></div><Select name="preference" label="Marketing Preference" value={c.preference}><option value="UNKNOWN">Unknown / Not Confirmed</option><option value="OPTED_IN">Opted In</option><option value="OPTED_OUT">Opted Out</option></Select><Select name="emailPresence" label="Email" value={c.emailPresence}><option value="PRESENT">Present</option><option value="MISSING">Missing</option></Select></div></section>
    <section className="report-section"><h2 className="report-section-title">Account filters</h2><div className="report-filter-grid"><Select name="accountId" label="Account" value={c.accountId}><Options items={options.accounts}/></Select><Select name="industry" label="Industry" value={c.industry}><Options items={options.industries}/></Select><Select name="businessRole" label="Business Role" value={c.businessRole}>{[["END_USER","End User"],["DISTRIBUTOR","Distributor"],["VAR","VAR"],["ISV","ISV"],["OEM","OEM"],["PARTNER","Partner"],["MEDIA_PARTNER","Media Partner"]].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select><Select name="territory" label="Territory" value={c.territory}><Options items={options.territories}/></Select><Select name="accountOwnerId" label="Account Owner" value={c.accountOwnerId}><Options items={options.users}/></Select><Select name="activeAccount" label="Account status" value={c.activeAccount}><option value="true">Active / non-archived</option><option value="false">Inactive or archived</option></Select></div></section>
    <section className="report-section"><h2 className="report-section-title">Trade Show filters</h2><div className="report-filter-grid"><Select name="tradeShowId" label="Trade Show" value={c.tradeShowId}><Options items={options.tradeShows}/></Select><div><label className="label" htmlFor="showDateFrom">Show date from</label><input className="field" type="date" id="showDateFrom" name="showDateFrom" defaultValue={c.showDateFrom??""}/></div><div><label className="label" htmlFor="showDateTo">Show date to</label><input className="field" type="date" id="showDateTo" name="showDateTo" defaultValue={c.showDateTo??""}/></div><Select name="leadStatus" label="Lead Status" value={c.leadStatus}>{["NEW","CONTACTED","QUALIFIED","CONVERTED","DISQUALIFIED"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</Select><Select name="routing" label="Lead Routing" value={c.routing}>{[["UNREVIEWED","Unreviewed"],["BIXOLON_SALES","BIXOLON Sales"],["REFERRED_TO_PARTNER","Referred to Partner"],["MARKETING_FOLLOW_UP","Marketing Follow-Up"]].map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</Select><Select name="assignedSalesRepId" label="Assigned Sales Rep" value={c.assignedSalesRepId}><Options items={options.users}/></Select><Select name="referralPartnerId" label="Referral Partner" value={c.referralPartnerId}><Options items={options.partners}/></Select><Select name="converted" label="Conversion" value={c.converted}><option value="true">Converted</option><option value="false">Not Converted</option></Select><div><label className="label" htmlFor="productInterest">Product Interest contains</label><input className="field" id="productInterest" name="productInterest" defaultValue={c.productInterest??""}/></div><Select name="competitorId" label="Resolved Competitor" value={c.competitorId}><Options items={options.competitors}/></Select></div></section>
    <div className="mt-3 flex justify-end gap-2"><Link className="btn-secondary" href={audience?`/marketing/audiences/${audience.id}`:"/marketing/audiences"}>Cancel</Link><button className="btn-primary disabled:opacity-60" disabled={pending}>{pending?"Saving…":audience?"Save audience":"Create audience"}</button></div>
  </form>;
}
