import { RecoverableActionForm } from '@/components/recoverable-action-form';
import Link from 'next/link';
import type { Actor } from '@/lib/authorization';
import { canManageAttribution } from '@/lib/marketing-attribution';
import { addInfluence, setFirstTouch, voidInfluence } from '@/app/marketing/attribution/actions';

type Touch = { id: number; occurredAt: Date; sourceContext: string; campaign: { name: string; archivedAt: Date | null } };
export function MarketingAttributionCard({ actor, leadSource, influences, sources, campaigns, contactId, tradeShowLeadId, tradeShowId }: { actor: Actor; leadSource: string | null; influences: Touch[]; sources?: { id: number; name: string; active: boolean }[]; campaigns?: { id: number; name: string }[]; contactId?: number; tradeShowLeadId?: number; tradeShowId?: number }) {
  const manage = canManageAttribution(actor) && (contactId || tradeShowLeadId);
  return <section className="panel p-5"><h2 className="mb-3 text-lg font-semibold">Marketing Attribution</h2><p className="text-sm"><span className="font-medium">Lead Source:</span> {leadSource ?? '—'}</p><h3 className="mt-4 text-sm font-semibold">Campaign Influence</h3>
    {influences.length ? <ul className="mt-1 divide-y text-sm">{influences.map(touch => <li key={touch.id} className="py-2"><span>{touch.campaign.name} — {touch.occurredAt.toISOString().slice(0, 10)}</span>{touch.campaign.archivedAt && <span className="ml-2 text-xs text-slate-500">Archived Campaign</span>}{manage && <details className="mt-1 text-xs"><summary className="cursor-pointer text-orange-800">Correct touch</summary><RecoverableActionForm action={voidInfluence} className="mt-2 flex gap-2"><input type="hidden" name="id" value={touch.id}/><input className="field" name="reason" maxLength={1000} required placeholder="Reason for voiding"/><button className="btn-secondary">Void touch</button></RecoverableActionForm></details>}</li>)}</ul> : <p className="mt-1 text-sm text-slate-500">No campaign touches recorded.</p>}
    {manage && <div className="mt-4 space-y-3 border-t pt-3"><details><summary className="cursor-pointer text-sm font-medium text-orange-800">Correct Lead Source</summary><RecoverableActionForm action={setFirstTouch} className="mt-2 flex flex-wrap gap-2">{contactId && <input type="hidden" name="contactId" value={contactId}/>}{tradeShowLeadId && <input type="hidden" name="tradeShowLeadId" value={tradeShowLeadId}/>}{tradeShowId && <input type="hidden" name="tradeShowId" value={tradeShowId}/>}<select className="field" name="sourceId"><option value="">Unknown</option>{sources?.map(source => <option key={source.id} value={source.id}>{source.name}{source.active ? '' : ' (inactive)'}</option>)}</select><input className="field" name="reason" maxLength={1000} required placeholder="Correction reason"/><button className="btn-secondary">Save</button></RecoverableActionForm></details><details><summary className="cursor-pointer text-sm font-medium text-orange-800">Add Campaign Influence</summary><RecoverableActionForm action={addInfluence} className="mt-2 flex flex-wrap gap-2">{contactId && <input type="hidden" name="contactId" value={contactId}/>}{tradeShowLeadId && <input type="hidden" name="tradeShowLeadId" value={tradeShowLeadId}/>}{tradeShowId && <input type="hidden" name="tradeShowId" value={tradeShowId}/>}<select className="field" name="campaignId" required><option value="">Choose Campaign</option>{campaigns?.map(campaign => <option key={campaign.id} value={campaign.id}>{campaign.name}</option>)}</select><input className="field" name="occurredAt" type="datetime-local" required/><input className="field" name="notes" maxLength={10000} placeholder="Context or note"/><button className="btn-secondary">Add touch</button></RecoverableActionForm></details><Link className="text-xs text-orange-800 underline" href="/marketing/campaigns">Manage Campaigns</Link></div>}
  </section>;
}
