'use client';
import { useActionState, useEffect, useState } from 'react';
import { submitTask, archiveTask, reactivateTask, type WorkState } from '@/app/tasks/actions';
import { submitActivity } from '@/app/activities/actions';
import { submitNote, archiveNote, reactivateNote } from '@/app/notes/actions';
import { useSubmitGuard } from '@/lib/submit-guard';
import { activityChoices, retainedActivitySelections, type RelatedOption } from '@/lib/activity-relations';
import { SaveSuccessFromQuery } from '@/components/save-success';
import { ActivityContactPicker } from '@/components/activity-contact-picker';
type Option = { id: number; name: string };
type Props = { kind: 'task'|'activity'|'note'; id?: number; createKey?: string; initial?: Record<string, string | number | null>; accounts: Option[]; opportunities: RelatedOption[]; projects: RelatedOption[]; users: Option[]; currentUser?: Option | null; contacts?: (Option & { accountId: number | null; accountName?: string | null; email?: string | null; active: boolean; archivedAt?: Date | null })[]; linkedContactIds?: number[]; activityTypes?: { code: string; name: string }[]; lockAccountId?: number; lockOpportunityId?: number; lockProjectId?: number; calendarAction?: (old: WorkState, form: FormData) => Promise<WorkState>; calendarTimeZone?: string };
export function WorkForm({ kind, id, createKey, initial = {}, accounts, opportunities, projects, users, currentUser, contacts = [], linkedContactIds = [], activityTypes = [], lockAccountId, lockOpportunityId, lockProjectId, calendarAction, calendarTimeZone }: Props) {
  const handler = calendarAction ? (_id: number | null, old: WorkState, form: FormData) => calendarAction(old, form) : kind === 'task' ? submitTask : kind === 'activity' ? submitActivity : submitNote;
  const [state, action, pending] = useActionState(handler.bind(null, id ?? null), { errors: {} } as WorkState);
  const guard = useSubmitGuard(state);
  const val = (key: string) => String(state.values?.[key] ?? initial[key] ?? '');
  const [selectedAccountId, setSelectedAccountId] = useState(Number(lockAccountId ?? initial.accountId ?? 0));
  const [selectedOpportunityId, setSelectedOpportunityId] = useState(Number(lockOpportunityId ?? initial.opportunityId ?? 0));
  const [selectedProjectId, setSelectedProjectId] = useState(Number(lockProjectId ?? initial.projectId ?? 0));
  const [selectedContactIds, setSelectedContactIds] = useState(linkedContactIds);
  const [followUpDate, setFollowUpDate] = useState(val('followUpDate'));
  useEffect(() => {
    if (!state.values || kind !== 'activity') return;
    setSelectedAccountId(Number(state.values.accountId || 0));
    setSelectedOpportunityId(Number(state.values.opportunityId || 0));
    setSelectedProjectId(Number(state.values.projectId || 0));
    setSelectedContactIds(state.values.contactIds ? state.values.contactIds.split(',').map(Number) : []);
    setFollowUpDate(state.values.followUpDate ?? '');
  }, [kind, state.values]);
  const select = (key: string, label: string, options: { value: string; label: string }[], empty = 'None') => <div><label className="label" htmlFor={key}>{label}</label><select className="field" id={key} name={key} defaultValue={val(key)}><option value="">{empty}</option>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select>{state.errors[key] && <p className="text-sm text-red-700">{state.errors[key]}</p>}</div>;
  const records = (items: Option[]) => items.map(o => ({ value: String(o.id), label: o.name }));
  const assignmentSelect = (key: 'assignedToId' | 'userId', label: string) => <div><label className="label" htmlFor={key}>{label}</label><select className="field" id={key} name={key} defaultValue={val(key)}><option value="">None</option>{currentUser && Number(initial[key]) === currentUser.id && <optgroup label="Current assignment"><option value={currentUser.id}>{currentUser.name} (no longer eligible)</option></optgroup>}{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select>{state.errors[key] && <p className="text-sm text-red-700">{state.errors[key]}</p>}</div>;
  const projectOptions = [...projects];
  const currentProjectId = Number(val('projectId'));
  if (currentProjectId && !projectOptions.some(p => p.id === currentProjectId)) projectOptions.push({ id: currentProjectId, name: 'Current Project (archived)', accountIds: [] });
  const historical = { opportunityId: Number(initial.opportunityId || 0), projectId: Number(initial.projectId || 0), contactIds: linkedContactIds };
  const originalAccountId = Number(initial.accountId || 0);
  const choices = activityChoices(selectedAccountId, originalAccountId, opportunities, projects, contacts, historical, { opportunityId: selectedOpportunityId, projectId: selectedProjectId });
  function changeAccount(accountId: number) {
    const kept = retainedActivitySelections(accountId, originalAccountId, opportunities, projects, contacts, historical, { opportunityId: selectedOpportunityId, projectId: selectedProjectId, contactIds: selectedContactIds });
    setSelectedAccountId(accountId); setSelectedOpportunityId(kept.opportunityId); setSelectedProjectId(kept.projectId); setSelectedContactIds(kept.contactIds);
  }
  function changeOpportunity(opportunityId: number) {
    const kept = retainedActivitySelections(selectedAccountId, originalAccountId, opportunities, projects, contacts, historical, { opportunityId, projectId: selectedProjectId, contactIds: selectedContactIds }, 'opportunity');
    setSelectedOpportunityId(kept.opportunityId); setSelectedProjectId(kept.projectId);
  }
  function changeProject(projectId: number) {
    const kept = retainedActivitySelections(selectedAccountId, originalAccountId, opportunities, projects, contacts, historical, { opportunityId: selectedOpportunityId, projectId, contactIds: selectedContactIds }, 'project');
    setSelectedOpportunityId(kept.opportunityId); setSelectedProjectId(kept.projectId);
  }
  const activitySelect = (key: 'opportunityId'|'projectId', label: string, items: RelatedOption[], selected: number, change: (id: number) => void) => <div><label className="label" htmlFor={key}>{label}</label><select className="field" id={key} name={key} value={selected || ''} onChange={event => change(Number(event.target.value))}><option value="">None</option>{state.errors[key] && selected && !items.some(item => item.id === selected) && <option value={selected}>{label} (review relationship)</option>}{items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{state.errors[key] && <p className="text-sm text-red-700">{state.errors[key]}</p>}</div>;
  return <>{kind==='task'&&id&&<SaveSuccessFromQuery recordName="Task"/>}<form key={JSON.stringify(state.values ?? {})} action={action} onSubmit={guard} className="panel grid gap-4 p-6 sm:grid-cols-2">
    {!id && kind !== "note" && <p className="sm:col-span-2 text-sm text-slate-600">{kind === "activity" ? "Record work that already happened, such as a call, meeting, or email." : "Track work that still needs to be done."}</p>}
    {createKey && !id && <input type="hidden" name="createKey" value={createKey}/>}
    {kind !== 'note' && <div className="sm:col-span-2"><label className="label" htmlFor="subject">Subject</label><input className="field" id="subject" name="subject" defaultValue={val('subject')} required maxLength={200}/>{state.errors.subject && <p className="text-sm text-red-700">{state.errors.subject}</p>}</div>}
    {kind === 'note' ? <div className="sm:col-span-2"><label className="label" htmlFor="body">Note</label><textarea className="field min-h-32" id="body" name="body" defaultValue={val('body')} required maxLength={10000}/>{state.errors.body && <p className="text-sm text-red-700">{state.errors.body}</p>}</div> : <div className="sm:col-span-2"><label className="label" htmlFor="description">Description</label><textarea className="field min-h-24" id="description" name="description" defaultValue={val('description')} maxLength={5000}/>{state.errors.description && <p className="text-sm text-red-700">{state.errors.description}</p>}</div>}
    {lockAccountId ? <input type="hidden" name="accountId" value={lockAccountId}/> : kind === 'activity' ? <div><label className="label" htmlFor="accountId">Account</label><select className="field" id="accountId" name="accountId" value={selectedAccountId || ''} onChange={event => changeAccount(Number(event.target.value))} required><option value="">Choose Account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select>{state.errors.accountId && <p className="text-sm text-red-700">{state.errors.accountId}</p>}</div> : select('accountId','Account',records(accounts))}
    {lockOpportunityId ? <input type="hidden" name="opportunityId" value={lockOpportunityId}/> : kind === 'activity' ? activitySelect('opportunityId','Opportunity',choices.opportunities,selectedOpportunityId,changeOpportunity) : select('opportunityId','Opportunity',records(opportunities))}
    {lockProjectId ? <input type="hidden" name="projectId" value={lockProjectId}/> : kind === 'activity' ? activitySelect('projectId','Project',choices.projects,selectedProjectId,changeProject) : select('projectId','Project',records(projectOptions))}
    {kind === 'activity' && <p className="sm:col-span-2 text-xs text-slate-500">Choose an Account first. Opportunities and Projects must belong to that Account; choosing either also limits the other to linked records. Active Contacts at the Account and eligible unassigned Contacts are available.</p>}
    {kind === 'task' && <>{assignmentSelect('assignedToId','Assignee')}{select('status','Status',['OPEN','IN_PROGRESS','COMPLETED','CANCELLED'].map(x => ({value:x,label:x.replace('_',' ')})),'Choose status')}{select('priority','Priority',['LOW','NORMAL','HIGH','URGENT'].map(x => ({value:x,label:x})),'Choose priority')}<div><label className="label" htmlFor="dueDate">Due date</label><input className="field" type="date" id="dueDate" name="dueDate" defaultValue={val('dueDate')}/></div></>}
    {kind === 'activity' && <>{select('type','Activity type',activityTypes.map(x => ({value:x.code,label:x.name})),'Choose type')}{assignmentSelect('userId','Responsible user')}{select('direction','Direction',[{value:'NA',label:'N/A'},{value:'INBOUND',label:'Inbound'},{value:'OUTBOUND',label:'Outbound'}],'Choose direction')}<div><label className="label" htmlFor="activityDate">Activity date and time {calendarTimeZone ? `(${calendarTimeZone})` : "(UTC)"}</label><input className="field" type="datetime-local" id="activityDate" name="activityDate" defaultValue={val('activityDate')} required/>{state.errors.activityDate && <p className="text-sm text-red-700">{state.errors.activityDate}</p>}</div><ActivityContactPicker contacts={choices.contacts} selectedIds={selectedContactIds} onChange={setSelectedContactIds} accountSelected={selectedAccountId > 0} error={state.errors.contactIds}/><div className="sm:col-span-2"><label className="label" htmlFor="outcome">Outcome</label><textarea className="field" id="outcome" name="outcome" defaultValue={val('outcome')} maxLength={2000}/>{state.errors.outcome && <p className="text-sm text-red-700">{state.errors.outcome}</p>}</div><div className="sm:col-span-2"><label className="label" htmlFor="nextStep">Next step</label><textarea className="field" id="nextStep" name="nextStep" defaultValue={val('nextStep')} maxLength={2000}/>{state.errors.nextStep && <p className="text-sm text-red-700">{state.errors.nextStep}</p>}</div><div><label className="label" htmlFor="followUpDate">Follow-Up Date</label><input className="field" type="date" id="followUpDate" name="followUpDate" value={followUpDate} onChange={event=>setFollowUpDate(event.target.value)}/><p className="mt-1 text-xs text-slate-500">Record when this Activity should be followed up.</p>{state.errors.followUpDate && <p className="text-sm text-red-700">{state.errors.followUpDate}</p>}</div>{!id&&/^\d{4}-\d{2}-\d{2}$/.test(followUpDate)&&<label className="flex items-start gap-3 self-end pb-2 text-sm font-medium text-slate-700"><input type="checkbox" name="createFollowUpTask" value="true" defaultChecked={val('createFollowUpTask')==='true'} className="mt-0.5 accent-orange-700"/><span>Create follow-up task<span className="mt-1 block text-xs font-normal text-slate-500">Add an assigned Task for this date.</span></span></label>}{state.errors.createFollowUpTask&&<p className="text-sm text-red-700 sm:col-span-2">{state.errors.createFollowUpTask}</p>}</>}
    <div className="sm:col-span-2"><button type="submit" className="btn-primary" disabled={pending}>{pending ? 'Saving…' : id ? 'Save changes' : `Create ${kind}`}</button>{state.message && <p role="status" className="mt-2 text-sm text-red-700">{state.message}</p>}</div>
  </form>{id && kind !== 'activity' && <ArchiveWork kind={kind} id={id}/>}</>;
}
function ArchiveWork({kind,id}: {kind:'task'|'note';id:number}) { const [state,action,pending] = useActionState((kind === 'task' ? archiveTask : archiveNote).bind(null,id),{errors:{}} as WorkState); return <form action={action} className="mt-5"><button className="btn-secondary" disabled={pending}>{pending ? 'Archiving…' : `Archive ${kind}`}</button>{state.message && <span className="ml-3 text-sm">{state.message}</span>}</form>; }
export function ReactivateTask({id}:{id:number}) { const [state,action,pending]=useActionState(reactivateTask.bind(null,id),{errors:{}} as WorkState); return <form action={action}><button className="btn-primary" disabled={pending}>{pending ? 'Reactivating…' : 'Reactivate task'}</button>{state.message && <span role="status" className="ml-3 text-sm">{state.message}</span>}</form>; }
export function ReactivateNote({id}:{id:number}) { const [state,action,pending]=useActionState(reactivateNote.bind(null,id),{errors:{}} as WorkState); return <form action={action}><button className="btn-primary" disabled={pending}>{pending ? 'Reactivating…' : 'Reactivate note'}</button>{state.message && <span role="status" className="ml-3 text-sm">{state.message}</span>}</form>; }
