'use client';
import { useActionState, useEffect, useRef, useState } from 'react';
import { submitTask, archiveTask, reactivateTask, type WorkState } from '@/app/tasks/actions';
import { submitActivity } from '@/app/activities/actions';
import { submitNote, archiveNote, reactivateNote } from '@/app/notes/actions';
import { useSubmitGuard } from '@/lib/submit-guard';
import { activityChoices, retainedActivitySelections, type RelatedOption } from '@/lib/activity-relations';
import { SaveSuccessFromQuery } from '@/components/save-success';
import { ActivityContactPicker } from '@/components/activity-contact-picker';
import { EntityPicker, type PickerResult } from '@/components/entity-picker';
type Option = { id: number; name: string };
type Props = { supportCase?: { id: number; caseNumber: string; contactName?: string | null }; kind: 'task'|'activity'|'note'; id?: number; createKey?: string; initial?: Record<string, string | number | null>; accounts: Option[]; opportunities: RelatedOption[]; projects: RelatedOption[]; users: Option[]; currentUser?: Option | null; contacts?: (Option & { accountId: number | null; accountName?: string | null; email?: string | null; active: boolean; archivedAt?: Date | null })[]; linkedContactIds?: number[]; activityTypes?: { code: string; name: string }[]; lockAccountId?: number; lockOpportunityId?: number; lockProjectId?: number; calendarAction?: (old: WorkState, form: FormData) => Promise<WorkState>; calendarTimeZone?: string };
export function WorkForm({ supportCase, kind, id, createKey, initial = {}, accounts, opportunities, projects, users, currentUser, contacts = [], linkedContactIds = [], activityTypes = [], lockAccountId, lockOpportunityId, lockProjectId, calendarAction, calendarTimeZone }: Props) {
  const handler = calendarAction ? (_id: number | null, old: WorkState, form: FormData) => calendarAction(old, form) : kind === 'task' ? submitTask : kind === 'activity' ? submitActivity : submitNote;
  const [state, action, pending] = useActionState(handler.bind(null, id ?? null), { errors: {} } as WorkState);
  const guard = useSubmitGuard(state, action);
  const val = (key: string) => String(state.values?.[key] ?? initial[key] ?? '');
  const [selectedAccountId, setSelectedAccountId] = useState(Number(lockAccountId ?? initial.accountId ?? 0));
  const [selectedOpportunityId, setSelectedOpportunityId] = useState(Number(lockOpportunityId ?? initial.opportunityId ?? 0));
  const [selectedProjectId, setSelectedProjectId] = useState(Number(lockProjectId ?? initial.projectId ?? 0));
  const [selectedContactIds, setSelectedContactIds] = useState(linkedContactIds);
  const relationSequence = useRef(0);
  const [knownAccounts, setKnownAccounts] = useState(accounts);
  const [knownOpportunities, setKnownOpportunities] = useState(opportunities);
  const [knownProjects, setKnownProjects] = useState(projects);
  const [knownContacts, setKnownContacts] = useState(contacts);
  const [followUpDate, setFollowUpDate] = useState(val('followUpDate'));
  useEffect(() => {
    if (!state.values || kind !== 'activity') return;
    setSelectedAccountId(Number(state.values.accountId || 0));
    setSelectedOpportunityId(Number(state.values.opportunityId || 0));
    setSelectedProjectId(Number(state.values.projectId || 0));
    setSelectedContactIds(state.values.contactIds ? state.values.contactIds.split(',').map(Number) : []);
    setFollowUpDate(state.values.followUpDate ?? '');
  }, [kind, state.values]);
  const select = (key: string, label: string, options: { value: string; label: string }[], empty = 'None') => <div><label className="label" htmlFor={key}>{label}</label><select className="field" id={key} name={key} defaultValue={val(key)}><option value="">{empty}</option>{options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select>{state.errors[key] && <p className="text-sm text-red-700">{state.errors[key]}</p>}</div>;
  const assignmentSelect = (key: 'assignedToId' | 'userId', label: string) => <div><label className="label" htmlFor={key}>{label}</label><select className="field" id={key} name={key} defaultValue={val(key)}><option value="">None</option>{currentUser && Number(initial[key]) === currentUser.id && <optgroup label="Current assignment"><option value={currentUser.id}>{currentUser.name} (no longer eligible)</option></optgroup>}{users.map(user => <option key={user.id} value={user.id}>{user.name}</option>)}</select>{state.errors[key] && <p className="text-sm text-red-700">{state.errors[key]}</p>}</div>;
  const historical = { opportunityId: Number(initial.opportunityId || 0), projectId: Number(initial.projectId || 0), contactIds: linkedContactIds };
  const originalAccountId = Number(initial.accountId || 0);
  const choices = activityChoices(selectedAccountId, originalAccountId, knownOpportunities, knownProjects, knownContacts, historical, { opportunityId: selectedOpportunityId, projectId: selectedProjectId });
  function changeAccount(accountId: number) {
    const sequence = ++relationSequence.current;
    const kept = retainedActivitySelections(accountId, originalAccountId, knownOpportunities, knownProjects, knownContacts, historical, { opportunityId: selectedOpportunityId, projectId: selectedProjectId, contactIds: selectedContactIds });
    setSelectedAccountId(accountId);
    setSelectedContactIds(kept.contactIds);
    if (!accountId) { setSelectedOpportunityId(0); setSelectedProjectId(0); return; }
    if (!selectedOpportunityId && !selectedProjectId) return;
    const params = new URLSearchParams({ accountId: String(accountId), opportunityId: String(selectedOpportunityId), projectId: String(selectedProjectId) });
    void fetch(`/api/entity-relations?${params}`).then(response => response.ok ? response.json() as Promise<{ opportunityValid: boolean; projectValid: boolean }> : null).then(result => {
      if (!result || relationSequence.current !== sequence) return;
      if (selectedOpportunityId && !result.opportunityValid) setSelectedOpportunityId(0);
      if (selectedProjectId && !result.projectValid) setSelectedProjectId(0);
    }).catch(() => {});
  }
  const found = (type: 'account'|'opportunity'|'project', item: PickerResult | null) => { if (!item) return; if (type === 'account') setKnownAccounts(old => old.some(row => row.id === item.id) ? old : [...old, item]); if (type === 'opportunity') setKnownOpportunities(old => old.some(row => row.id === item.id) ? old : [...old, { ...item, accountIds: item.accountIds ?? [], projectIds: item.projectIds ?? [] }]); if (type === 'project') setKnownProjects(old => old.some(row => row.id === item.id) ? old : [...old, { ...item, accountIds: item.accountIds ?? [], opportunityIds: item.opportunityIds ?? [] }]); };
  const accountChoice = selectedAccountId ? { id: selectedAccountId, name: knownAccounts.find(row => row.id === selectedAccountId)?.name ?? 'Current Account', context: null } : null;
  const opportunityChoice = selectedOpportunityId ? { id: selectedOpportunityId, name: knownOpportunities.find(row => row.id === selectedOpportunityId)?.name ?? 'Current Opportunity', context: null } : null;
  const projectChoice = selectedProjectId ? { id: selectedProjectId, name: knownProjects.find(row => row.id === selectedProjectId)?.name ?? 'Current Project', context: null } : null;
  return <>{kind==='task'&&id&&<SaveSuccessFromQuery recordName="Task"/>}<form action={action} onSubmit={guard} className="panel grid gap-4 p-6 sm:grid-cols-2">
    {!id && kind !== "note" && <p className="sm:col-span-2 text-sm text-slate-600">{kind === "activity" ? "Record work that already happened, such as a call, meeting, or email." : "Track work that still needs to be done."}</p>}
    {supportCase && <div className="sm:col-span-2 rounded-md border border-orange-200 bg-orange-50 p-3 text-sm"><strong>Support Case:</strong> {supportCase.caseNumber}{supportCase.contactName ? ` · ${supportCase.contactName}` : ""}<input type="hidden" name="supportCaseId" value={supportCase.id}/></div>}
    {createKey && !id && <input type="hidden" name="createKey" value={createKey}/>}
    {kind !== 'note' && <div className="sm:col-span-2"><label className="label" htmlFor="subject">Subject</label><input className="field" id="subject" name="subject" defaultValue={val('subject')} required maxLength={200}/>{state.errors.subject && <p className="text-sm text-red-700">{state.errors.subject}</p>}</div>}
    {kind === 'note' ? <div className="sm:col-span-2"><label className="label" htmlFor="body">Note</label><textarea className="field min-h-32" id="body" name="body" defaultValue={val('body')} required maxLength={10000}/>{state.errors.body && <p className="text-sm text-red-700">{state.errors.body}</p>}</div> : <div className="sm:col-span-2"><label className="label" htmlFor="description">Description</label><textarea className="field min-h-24" id="description" name="description" defaultValue={val('description')} maxLength={5000}/>{state.errors.description && <p className="text-sm text-red-700">{state.errors.description}</p>}</div>}
    {lockAccountId ? <input type="hidden" name="accountId" value={lockAccountId}/> : <EntityPicker type="account" label="Account" name="accountId" value={accountChoice} required={kind === 'activity'} onChange={item => { found('account', item); changeAccount(item?.id ?? 0); }} error={state.errors.accountId}/>}
    {lockOpportunityId ? <input type="hidden" name="opportunityId" value={lockOpportunityId}/> : <EntityPicker type="opportunity" label="Opportunity" name="opportunityId" value={opportunityChoice} filters={kind === 'activity' ? { accountId: selectedAccountId } : undefined} disabled={kind === 'activity' && !selectedAccountId} onChange={item => { relationSequence.current++; found('opportunity', item); setSelectedOpportunityId(item?.id ?? 0); if (kind === 'activity' && selectedProjectId && item && item.projectIds && item.projectIds.length < 20 && !item.projectIds.includes(selectedProjectId)) setSelectedProjectId(0); }} error={state.errors.opportunityId}/>}
    {lockProjectId ? <input type="hidden" name="projectId" value={lockProjectId}/> : <EntityPicker type="project" label="Project" name="projectId" value={projectChoice} filters={kind === 'activity' ? { accountId: selectedAccountId, opportunityId: selectedOpportunityId || undefined } : undefined} disabled={kind === 'activity' && !selectedAccountId} onChange={item => { relationSequence.current++; found('project', item); setSelectedProjectId(item?.id ?? 0); if (kind === 'activity' && selectedOpportunityId && item && item.opportunityIds && item.opportunityIds.length < 20 && !item.opportunityIds.includes(selectedOpportunityId)) setSelectedOpportunityId(0); }} error={state.errors.projectId}/>}
    {kind === 'activity' && <p className="sm:col-span-2 text-xs text-slate-500">Choose an Account first. Opportunities and Projects must belong to that Account; choosing either also limits the other to linked records. Active Contacts at the Account and eligible unassigned Contacts are available.</p>}
    {kind === 'task' && supportCase && <EntityPicker type="contact" label="Contact" name="contactId" initial={contacts.find(contact => contact.id === Number(val('contactId'))) ? { id: Number(val('contactId')), name: contacts.find(contact => contact.id === Number(val('contactId')))!.name, context: null } : null} filters={{ accountId: selectedAccountId }} disabled={!selectedAccountId}/>}
    {kind === 'task' && <>{assignmentSelect('assignedToId','Assignee')}{select('status','Status',['OPEN','IN_PROGRESS','COMPLETED','CANCELLED'].map(x => ({value:x,label:x.replace('_',' ')})),'Choose status')}{select('priority','Priority',['LOW','NORMAL','HIGH','URGENT'].map(x => ({value:x,label:x})),'Choose priority')}<div><label className="label" htmlFor="dueDate">Due date</label><input className="field" type="date" id="dueDate" name="dueDate" defaultValue={val('dueDate')}/></div></>}
    {kind === 'activity' && <>{select('type','Activity type',activityTypes.map(x => ({value:x.code,label:x.name})),'Choose type')}{assignmentSelect('userId','Responsible user')}{select('direction','Direction',[{value:'NA',label:'N/A'},{value:'INBOUND',label:'Inbound'},{value:'OUTBOUND',label:'Outbound'}],'Choose direction')}<div><label className="label" htmlFor="activityDate">Activity date and time {calendarTimeZone ? `(${calendarTimeZone})` : "(UTC)"}</label><input className="field" type="datetime-local" id="activityDate" name="activityDate" defaultValue={val('activityDate')} required/>{state.errors.activityDate && <p className="text-sm text-red-700">{state.errors.activityDate}</p>}</div><ActivityContactPicker contacts={choices.contacts} onFound={contact => setKnownContacts(old => old.some(row => row.id === contact.id) ? old : [...old, contact])} selectedIds={selectedContactIds} onChange={setSelectedContactIds} accountId={selectedAccountId} error={state.errors.contactIds}/><div className="sm:col-span-2"><label className="label" htmlFor="outcome">Outcome</label><textarea className="field" id="outcome" name="outcome" defaultValue={val('outcome')} maxLength={2000}/>{state.errors.outcome && <p className="text-sm text-red-700">{state.errors.outcome}</p>}</div><div className="sm:col-span-2"><label className="label" htmlFor="nextStep">Next step</label><textarea className="field" id="nextStep" name="nextStep" defaultValue={val('nextStep')} maxLength={2000}/>{state.errors.nextStep && <p className="text-sm text-red-700">{state.errors.nextStep}</p>}</div><div><label className="label" htmlFor="followUpDate">Follow-Up Date</label><input className="field" type="date" id="followUpDate" name="followUpDate" value={followUpDate} onChange={event=>setFollowUpDate(event.target.value)}/><p className="mt-1 text-xs text-slate-500">Record when this Activity should be followed up.</p>{state.errors.followUpDate && <p className="text-sm text-red-700">{state.errors.followUpDate}</p>}</div>{!id&&/^\d{4}-\d{2}-\d{2}$/.test(followUpDate)&&<label className="flex items-start gap-3 self-end pb-2 text-sm font-medium text-slate-700"><input type="checkbox" name="createFollowUpTask" value="true" defaultChecked={val('createFollowUpTask')==='true'} className="mt-0.5 accent-orange-700"/><span>Create follow-up task<span className="mt-1 block text-xs font-normal text-slate-500">Add an assigned Task for this date.</span></span></label>}{state.errors.createFollowUpTask&&<p className="text-sm text-red-700 sm:col-span-2">{state.errors.createFollowUpTask}</p>}</>}
    <div className="sm:col-span-2"><button type="submit" className="btn-primary" disabled={pending}>{pending ? 'Saving…' : id ? 'Save changes' : `Create ${kind}`}</button>{state.message && <p role="status" className="mt-2 text-sm text-red-700">{state.message}</p>}</div>
  </form>{id && kind !== 'activity' && <ArchiveWork kind={kind} id={id}/>}</>;
}
function ArchiveWork({kind,id}: {kind:'task'|'note';id:number}) { const [state,action,pending] = useActionState((kind === 'task' ? archiveTask : archiveNote).bind(null,id),{errors:{}} as WorkState); return <form action={action} className="mt-5"><button className="btn-secondary" disabled={pending}>{pending ? 'Archiving…' : `Archive ${kind}`}</button>{state.message && <span className="ml-3 text-sm">{state.message}</span>}</form>; }
export function ReactivateTask({id}:{id:number}) { const [state,action,pending]=useActionState(reactivateTask.bind(null,id),{errors:{}} as WorkState); return <form action={action}><button className="btn-primary" disabled={pending}>{pending ? 'Reactivating…' : 'Reactivate task'}</button>{state.message && <span role="status" className="ml-3 text-sm">{state.message}</span>}</form>; }
export function ReactivateNote({id}:{id:number}) { const [state,action,pending]=useActionState(reactivateNote.bind(null,id),{errors:{}} as WorkState); return <form action={action}><button className="btn-primary" disabled={pending}>{pending ? 'Reactivating…' : 'Reactivate note'}</button>{state.message && <span role="status" className="ml-3 text-sm">{state.message}</span>}</form>; }
