import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Content,PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { can } from '@/lib/authorization';
import { prisma } from '@/lib/prisma';
import { supportReport, supportCaseAge, type SupportReportFilters } from '@/lib/support-report';
import { supportStatusLabels,supportPriorityLabels } from '@/lib/support-cases';
import { supportFormOptions } from '@/lib/support-case-ui';
import { NAV_CATEGORIES } from '@/lib/navigation-categories';
import { formatDateTimeForUser } from '@/lib/display-format';

export const dynamic='force-dynamic';
const title=(value:string)=>supportStatusLabels[value as keyof typeof supportStatusLabels]??supportPriorityLabels[value as keyof typeof supportPriorityLabels]??value;
export default async function Page({searchParams}:{searchParams:Promise<SupportReportFilters>}){
  const actor=await currentUser();if(!can(actor,'support-cases.read')||!can(actor,'accounts.read'))notFound();
  const filters=await searchParams,[report,choices]=await Promise.all([supportReport(prisma,actor,filters),supportFormOptions(actor)]);
  const query=new URLSearchParams(Object.entries(filters).filter(([key,value])=>key!=='page'&&!!value) as [string,string][]);
  const href=(page:number)=>{const next=new URLSearchParams(query);next.set('page',String(page));return `/reports/support-cases?${next}`};
  const fields:[string,string,string][]=[['account','Account','Account name'],['contact','Contact','Contact name'],['product','Product / SKU','Part number'],['purchasedFrom','Purchased From Account','Linked Account name']];
  return <Content><PageHeader eyebrow={NAV_CATEGORIES.reports} title="Support Cases Report" description="Review case load, aging, follow-ups, and resolution." action={<Link className="btn-primary" href={`/reports/support-cases/export?${query}`}>Export Excel</Link>}/>
    <form method="get" className="filter-panel filter-grid filter-row mb-5" aria-label="Filter Support Cases report">
      <label className="label">Search<input className="field filter-control" name="q" defaultValue={filters.q??''} placeholder="Case, Account, Contact, subject, serial, Purchased From"/></label>
      <label className="label">Support Rep<select className="field filter-control" name="rep" defaultValue={filters.rep??''}><option value="">All reps</option>{choices.assignees.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      <label className="label">Status<select className="field filter-control" name="status" defaultValue={filters.status??''}><option value="">All statuses</option>{Object.entries(supportStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label className="label">Priority<select className="field filter-control" name="priority" defaultValue={filters.priority??''}><option value="">All priorities</option>{Object.entries(supportPriorityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label className="label">Category<select className="field filter-control" name="category" defaultValue={filters.category??''}><option value="">All categories</option>{choices.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
      {fields.map(([name,label,placeholder])=><label className="label" key={name}>{label}<input className="field filter-control" name={name} defaultValue={filters[name as keyof SupportReportFilters]??''} placeholder={placeholder}/></label>)}
      {([['openedFrom','Opened from'],['openedTo','Opened through'],['resolvedFrom','Resolved from'],['resolvedTo','Resolved through']] as const).map(([name,label])=><label className="label" key={name}>{label}<input className="field filter-control" type="date" name={name} defaultValue={filters[name]??''}/></label>)}
      <label className="label">Next Follow-up<select className="field filter-control" name="followUp" defaultValue={filters.followUp??''}>{[['','All'],['today','Due today'],['overdue','Overdue'],['upcoming','Upcoming'],['none','No follow-up date']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <label className="label">Archive<select className="field filter-control" name="archive" defaultValue={filters.archive??'active'}><option value="active">Current</option><option value="archived">Archived</option><option value="all">All</option></select></label>
      <label className="label">Sort<select className="field filter-control" name="sort" defaultValue={filters.sort??'newest'}>{[['newest','Newest opened'],['oldest','Oldest opened'],['priority','Priority'],['follow-up','Next follow-up'],['resolved','Recently resolved'],['number','Case Number']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
      <div className="filter-actions flex gap-2"><button className="btn-filter-primary">View report</button><Link className="btn-filter-secondary" href="/reports/support-cases">Clear</Link></div>
    </form>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Open Cases',report.summary.open],['High / Critical',report.summary.highCritical],['Overdue Follow-ups',report.summary.overdue],['Opened in period',report.summary.opened],['Resolved in period',report.summary.resolved],['Average age of open cases',report.summary.averageOpenDays===null?'—':`${report.summary.averageOpenDays} days`],['Average time to resolution',report.summary.averageResolutionDays===null?'—':`${report.summary.averageResolutionDays} days`]].map(([label,value])=><div className="panel p-4" key={label}><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}</div>
    <div className="mb-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{(['status','priority','category','product','rep','purchasedFrom'] as const).map(group=><section className="panel p-4" key={group}><h2 className="font-semibold">Cases by {({status:'Status',priority:'Priority',category:'Category',product:'Product / SKU',rep:'Support Rep',purchasedFrom:'Purchased From'} as const)[group]}</h2><ul className="mt-2 divide-y text-sm">{report.groups[group].map(item=><li className="flex justify-between gap-2 py-1" key={item.label}><span>{title(item.label)}</span><strong>{item.count}</strong></li>)}</ul>{!report.groups[group].length&&<p className="mt-2 text-sm text-slate-600">No cases.</p>}</section>)}</div>
    <section className="panel mb-5 p-4"><h2 className="font-semibold">Open case aging</h2><div className="mt-3 grid gap-2 sm:grid-cols-5">{report.aging.map(bucket=><div className="rounded border p-3 text-sm" key={bucket.label}><p className="text-slate-600">{bucket.label}</p><strong className="text-xl">{bucket.count}</strong></div>)}</div></section>
    <section className="panel overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-600"><tr>{['Case Number','Customer / End User','Contact','Subject','Status','Priority','Category','Support Rep','Product / SKU','Purchased From','Linked Purchased-From Account','Opened','Next Follow-up','Age'].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{report.rows.map(row=><tr key={row.id}><td className="px-3 py-2"><Link className="font-semibold text-orange-800 underline" href={`/support/cases/${row.id}`}>{row.caseNumber}</Link></td><td className="px-3 py-2">{row.customerNameText ?? row.account?.name ?? '—'}</td><td className="px-3 py-2">{row.contact?`${row.contact.firstName} ${row.contact.lastName}`:'—'}</td><td className="px-3 py-2">{row.subject}</td><td className="px-3 py-2">{supportStatusLabels[row.status]}</td><td className="px-3 py-2">{supportPriorityLabels[row.priority]}</td><td className="px-3 py-2">{row.category?.name??'—'}</td><td className="px-3 py-2">{row.assignedTo?`${row.assignedTo.firstName} ${row.assignedTo.lastName}`:'Unassigned'}</td><td className="px-3 py-2">{row.productSku?.partNumber??'—'}</td><td className="px-3 py-2">{row.purchaseSourceText??'—'}</td><td className="px-3 py-2">{row.purchasedFromAccount?.name??'Unresolved Purchased From'}</td><td className="px-3 py-2">{formatDateTimeForUser(row.openedAt,choices.zone)}</td><td className="px-3 py-2">{row.nextFollowUpAt?formatDateTimeForUser(row.nextFollowUpAt,choices.zone):'—'}</td><td className="px-3 py-2">{supportCaseAge(row,report.now)} days</td></tr>)}</tbody></table>{!report.rows.length&&<p className="p-6 text-sm text-slate-600">No Support Cases match these filters.</p>}</section>
    <nav className="mt-4 flex items-center justify-between text-sm"><span>{report.count} cases · Page {report.page} of {report.pages}</span><span className="flex gap-2">{report.page>1&&<Link className="btn-secondary" href={href(report.page-1)}>Previous</Link>}{report.page<report.pages&&<Link className="btn-secondary" href={href(report.page+1)}>Next</Link>}</span></nav>
  </Content>;
}
