'use server';
import { prisma } from '@/lib/prisma';
import { requireMutation } from '@/lib/current-user';
import { applyPriceExceptionImport, parseLegacyPriceExceptionWorkbook, planPriceExceptionImport } from '@/lib/price-exception-import';
import { revalidatePath } from 'next/cache';

async function workbook(form:FormData){const value=form.get('file');if(!value||typeof value==='string'||typeof value.arrayBuffer!=='function')return {error:'Choose the legacy .xlsx workbook.'};const file=value as File;if(!file.name.toLowerCase().endsWith('.xlsx'))return {error:'Price Exception legacy imports require an .xlsx workbook.'};if(file.size>4_000_000)return {error:'Choose an .xlsx file smaller than 4 MB.'};return {file,parsed:await parseLegacyPriceExceptionWorkbook(Buffer.from(await file.arrayBuffer()))};}
export async function previewPriceExceptions(form:FormData){await requireMutation('users.manage');const upload=await workbook(form);if(!upload.file||!upload.parsed)return {error:upload.error};const plan=await planPriceExceptionImport(prisma,upload.parsed,upload.file.name);return plan.errors.length&&!plan.items.length?{error:plan.errors.join(' '),plan}:{plan};}
export async function confirmPriceExceptions(form:FormData,digest:string){const actor=await requireMutation('users.manage');const upload=await workbook(form);if(!upload.file||!upload.parsed)return {ok:false as const,message:upload.error??'Upload could not be read.'};try{const counts=await applyPriceExceptionImport(prisma,upload.parsed,upload.file.name,digest,actor.id);revalidatePath('/price-exceptions');revalidatePath('/accounts');return {ok:true as const,counts};}catch(error){return {ok:false as const,message:error instanceof Error&&error.message.startsWith('Preview changed')?error.message:'Import failed. No records were applied. Preview again and review source errors.'};}}
