import Link from "next/link";
import { AccountTableRow } from "@/components/account-table-row";
import { Content, PageHeader } from "@/components/shell";
import { accountHref, accountOptions, accountView, listAccounts, type AccountFilters } from "@/lib/accounts";
import { roleLabels, statuses } from "@/lib/account-validation";
import { prisma } from "@/lib/prisma";
import { getLabels } from "@/lib/configuration";
import { currentUser } from "@/lib/current-user";
import { assertPermission } from "@/lib/authorization";
export const dynamic = "force-dynamic";
export default async function AccountsPage({ searchParams }: { searchParams: Promise<AccountFilters> }) {
  const filters = await searchParams;
  const actor = await currentUser();
  assertPermission(actor, "accounts.read");
  const view = accountView(filters);
  const [{ accounts, count, page, pages }, options, labels] = await Promise.all([listAccounts(prisma, filters, actor.id), accountOptions(prisma), getLabels(prisma)]);
  const linkFor = (target: number) => accountHref({ ...filters, view }, { page: String(target) });
  return <Content><PageHeader eyebrow="CRM records" title="Accounts" description="Organizations and relationships in the CRM." action={<Link href="/accounts/new" className="btn-primary">New account</Link>}/>
    <nav aria-label="Account views" className="mb-4 flex gap-1 border-b border-slate-200">{([ ["all", "All Accounts"], ["my", "My Accounts"] ] as const).map(([value, label]) => <Link key={value} href={accountHref(filters, { view: value })} aria-current={view === value ? "page" : undefined} className={`border-b-2 px-4 py-2.5 text-sm font-semibold ${view === value ? "border-orange-600 text-orange-800" : "border-transparent text-slate-600 hover:text-slate-900"}`}>{label}</Link>)}</nav>
    <form className="panel mb-3 flex w-fit max-w-full flex-wrap items-end gap-x-1.5 gap-y-1.5 p-1.5" method="get" aria-label="Filter accounts">
      <input type="hidden" name="view" value={view}/>
      <div className="accounts-filter-field"><label className="mb-0.5 block text-xs font-semibold text-slate-700" htmlFor="q">Search accounts</label><input className="field accounts-filter-control min-w-0 text-sm" id="q" name="q" defaultValue={filters.q ?? ""} placeholder="Account name"/></div>
      <div className="accounts-filter-field"><label className="mb-0.5 block text-xs font-semibold text-slate-700" htmlFor="status">Status</label><select className="field accounts-filter-control min-w-0 text-sm" id="status" name="status" defaultValue={filters.status ?? ""}><option value="">All statuses</option>{statuses.map((s) => <option value={s} key={s}>{s}</option>)}</select></div>
      <div className="accounts-filter-field"><label className="mb-0.5 block text-xs font-semibold text-slate-700" htmlFor="role">Business role</label><select className="field accounts-filter-control min-w-0 text-sm" id="role" name="role" defaultValue={filters.role ?? ""}><option value="">All roles</option>{Object.entries(roleLabels).map(([code, label]) => <option key={code} value={code}>{labels[code as keyof typeof labels] ?? label}</option>)}</select></div>
      <div className="accounts-filter-field"><label className="mb-0.5 block text-xs font-semibold text-slate-700" htmlFor="territory">Territory</label><select className="field accounts-filter-control min-w-0 text-sm" id="territory" name="territory" defaultValue={filters.territory ?? ""}><option value="">All territories</option>{options.territories.map((o) => <option key={o.code} value={o.code}>{o.name}</option>)}</select></div>
      <div className="accounts-filter-field"><label className="mb-0.5 block text-xs font-semibold text-slate-700" htmlFor="industry">Industry</label><select className="field accounts-filter-control min-w-0 text-sm" id="industry" name="industry" defaultValue={filters.industry ?? ""}><option value="">All industries</option>{options.industries.map((o) => <option key={o.code} value={o.code}>{o.name}</option>)}</select></div>
      <div className="accounts-filter-field"><label className="mb-0.5 block text-xs font-semibold text-slate-700" htmlFor="strategic">Strategic account</label><select className="field accounts-filter-control min-w-0 text-sm" id="strategic" name="strategic" defaultValue={filters.strategic ?? ""}><option value="">All accounts</option><option value="yes">Strategic only</option><option value="no">Non-strategic</option></select></div>
      <button className="btn-primary accounts-filter-action self-end whitespace-nowrap" type="submit">Apply filters</button><Link className="btn-secondary accounts-filter-action self-end whitespace-nowrap" href={`/accounts?view=${view}`}>Clear</Link>
    </form>
    <div className="panel overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-100 text-xs font-semibold uppercase tracking-wide text-slate-600"><tr><th className="px-4 py-3">Account</th><th className="px-4 py-3">Business roles</th><th className="px-4 py-3">Territory</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Contacts</th></tr></thead><tbody className="divide-y divide-slate-100">{accounts.map((a) => <AccountTableRow key={a.id} id={a.id} name={a.name}><td className="px-4 py-2.5"><Link className="rounded-sm font-semibold text-slate-950 hover:text-orange-700 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-orange-600" href={`/accounts/${a.id}`}>{a.name}</Link><div className="mt-0.5 text-xs text-slate-500">{a.industryCategory?.name ?? "No industry"}{a.strategicAccount ? ` · ${labels.STRATEGIC_ACCOUNT}` : ""}</div></td><td className="px-4 py-2.5 text-slate-600">{a.businessRoles.map((r) => labels[r.role]).join(", ") || "—"}</td><td className="px-4 py-2.5 text-slate-600">{a.territoryCategory?.name ?? "—"}</td><td className="px-4 py-2.5 text-slate-600">{a.owner ? `${a.owner.firstName} ${a.owner.lastName}` : "Unassigned"}</td><td className="px-4 py-2.5"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${a.status === "ACTIVE" ? "bg-green-50 text-green-700" : a.status === "INACTIVE" ? "bg-amber-50 text-amber-800" : "bg-slate-100 text-slate-600"}`}>{a.status}</span></td><td className="px-4 py-2.5 text-right tabular-nums text-slate-600">{a._count.contacts}</td></AccountTableRow>)}</tbody></table>{accounts.length === 0 && <div className="px-5 py-12 text-center text-sm text-slate-500">No accounts match these filters.</div>}</div>
    <div className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>{count} account{count === 1 ? "" : "s"} · Page {page} of {pages}</span><div className="flex gap-2">{page > 1 && <Link className="btn-secondary" href={linkFor(page - 1)}>Previous</Link>}{page < pages && <Link className="btn-secondary" href={linkFor(page + 1)}>Next</Link>}</div></div>
  </Content>;
}
