'use server';
import { revalidatePath } from 'next/cache';
import { requireMutation } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { parseDemoCsv, planDemoImport, applyDemoImport, mapDemoSourceAccount, type DemoChoices } from '@/lib/demo-import';
import { createPeReviewAccount } from '@/lib/price-exception-account-create';

async function upload(form:FormData){const file=form.get('file');if(!(file instanceof File)||!file.name.toLowerCase().endsWith('.csv')||file.size>2_000_000)return {error:'Choose a UTF-8 Demo CSV smaller than 2 MB.'};return {file,parsed:parseDemoCsv(await file.text())};}
async function admin(){const actor=await requireMutation('users.manage');if(actor.role!=='ADMIN')throw new Error('Administrator access required.');return actor;}
export async function previewDemo(form:FormData,choices:DemoChoices={}){await admin();const input=await upload(form);if(!input.file||!input.parsed)return {error:input.error};try{return {plan:await planDemoImport(prisma,input.parsed,input.file.name,choices)};}catch(error){return {error:error instanceof Error?error.message:'Preview failed.'};}}
export async function reviewDemo(form:FormData,prior:DemoChoices,next:DemoChoices,digest:string){await admin();const input=await upload(form);if(!input.file||!input.parsed)return {error:input.error};try{const old=await planDemoImport(prisma,input.parsed,input.file.name,prior);if(old.digest!==digest)throw new Error('Preview changed. Preview again.');const changed=Object.keys(next).find(id=>next[id]?.accountId!==prior[id]?.accountId&&next[id]?.accountId!==undefined);const expanded=changed?mapDemoSourceAccount(old,next,changed,next[changed].accountId!):next;return {plan:await planDemoImport(prisma,input.parsed,input.file.name,expanded),choices:expanded};}catch(error){return {error:error instanceof Error?error.message:'Review failed.'};}}
export async function applyDemo(form:FormData,digest:string,confirmed:boolean,choices:DemoChoices,updates:string[]){const actor=await admin();const input=await upload(form);if(!input.file||!input.parsed)return {error:input.error};try{const result=await applyDemoImport(prisma,input.parsed,input.file.name,digest,confirmed,actor.id,choices,updates);revalidatePath('/demos');return {result};}catch(error){return {error:error instanceof Error?error.message:'Apply failed.'};}}
export async function createDemoAccount(fileForm:FormData,accountForm:FormData,requestId:string,choices:DemoChoices,digest:string,confirmed:boolean,acknowledgeDuplicate:boolean,reviewedToken?:string){const actor=await admin();await requireMutation('accounts.write');const input=await upload(fileForm);if(!input.file||!input.parsed)return {kind:'error' as const,message:input.error};try{const old=await planDemoImport(prisma,input.parsed,input.file.name,choices);if(old.digest!==digest)throw new Error('Preview changed. Preview again.');const group=old.groups.find(item=>item.requestId===requestId);if(!group||!group.account.issue||!group.header.VAR.trim())throw new Error('This Account no longer needs creation.');if(confirmed&&!reviewedToken)throw new Error('Review Account creation first.');const response=await createPeReviewAccount(prisma,actor,accountForm,confirmed,acknowledgeDuplicate,reviewedToken);if(response.kind!=='created')return response;const refreshed=await planDemoImport(prisma,input.parsed,input.file.name,choices);const next=mapDemoSourceAccount(refreshed,choices,requestId,response.account.id);revalidatePath('/accounts');return {kind:'created' as const,account:response.account,choices:next,plan:await planDemoImport(prisma,input.parsed,input.file.name,next)};}catch(error){return {kind:'error' as const,message:error instanceof Error?error.message:'Account creation failed.'};}}
