'use client';
import { useEffect, useRef, useState } from 'react';
import { ImportSearchPicker } from '@/components/import-search-picker';
import { OdmDetailsFields } from '@/components/product-odm-fields';
import type { DemoChoices, DemoPlan } from '@/lib/demo-import';
import { createDemoSku, inspectDemoSku } from './actions';

type Options=Extract<Awaited<ReturnType<typeof inspectDemoSku>>,{kind:'review'}>['options'];
export function DemoSkuCreate({fileForm,requestId,line,choices,plan,onClose,onCreated}:{fileForm:()=>FormData;requestId:string;line:number;choices:DemoChoices;plan:DemoPlan;onClose:()=>void;onCreated:(next:{plan:DemoPlan;choices:DemoChoices;skuId:number})=>void}){
  const item=plan.groups.find(group=>group.requestId===requestId)?.items.find(item=>item.line===line);
  const [options,setOptions]=useState<Options|null>(null),[review,setReview]=useState<Options|null>(null);
  const [mode,setMode]=useState<'existing'|'new'>('existing'),[productId,setProductId]=useState<number|null>(null);
  const [name,setName]=useState(''),[partNumber,setPartNumber]=useState(item?.sourceSku??''),[source,setSource]=useState('');
  const [acknowledged,setAcknowledged]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const formRef=useRef<HTMLFormElement>(null);
  useEffect(()=>{let alive=true;void inspectDemoSku(fileForm(),requestId,line,choices,plan.digest).then(result=>{if(!alive)return;if(result.kind==='review')setOptions(result.options);else setError(result.message);});return()=>{alive=false};},[fileForm,requestId,line,choices,plan.digest]);
  async function reviewProduct(){if(busy||!name.trim())return;setBusy(true);setError('');try{const result=await inspectDemoSku(fileForm(),requestId,line,choices,plan.digest,name,partNumber);if(result.kind==='review'){setReview(result.options);setAcknowledged(false);}else setError(result.message);}catch{setError('Product review failed.')}finally{setBusy(false)}}
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!formRef.current||busy)return;setBusy(true);setError('');try{const form=new FormData(formRef.current);const result=await createDemoSku(fileForm(),form,requestId,line,choices,plan.digest,mode==='new'?review?.reviewToken??'':'',acknowledged);if(result.kind==='created')onCreated(result);else setError(result.message);}catch{setError('SKU creation failed.')}finally{setBusy(false)}}
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-900/50 p-4" role="dialog" aria-modal="true" aria-label="Create catalog SKU"><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded bg-white p-5"><h2 className="text-lg font-semibold">Add catalog SKU</h2><p className="mt-1 text-sm text-slate-600">Source SKU: {item?.sourceSku}. This creates a catalog record now; Demo import still needs separate confirmation.</p>{error&&<p className="mt-3 rounded bg-red-50 p-2 text-sm text-red-800" role="alert">{error}</p>}
    <form ref={formRef} onSubmit={event=>void create(event)} className="mt-4 space-y-3 text-sm"><label className="block">Product choice<select className="field mt-1 w-full" name="mode" value={mode} onChange={event=>{setMode(event.target.value as 'existing'|'new');setReview(null)}}><option value="existing">Add SKU to existing Product</option><option value="new">Create Product + SKU</option></select></label>
      {mode==='existing'?<><ImportSearchPicker label="Existing Product" emptyLabel="Select a Product" value={productId} items={(options?.products??[]).map(product=>({id:product.id,name:`${product.name} · ${product.sku}`}))} disabled={busy} onChange={setProductId}/><input type="hidden" name="productId" value={productId??''}/>{!!options?.candidates.length&&<div className="rounded bg-amber-50 p-2"><b>Likely Product families:</b> {options.candidates.map(candidate=>`${candidate.name} (${candidate.sku})`).join(', ')}</div>}</>:<><label className="block">Product model/family name<input className="field mt-1 w-full" name="name" required maxLength={200} value={name} onChange={event=>{setName(event.target.value);setReview(null)}}/></label><label className="block">Product Category<select className="field mt-1 w-full" name="categoryId"><option value="">Uncategorized</option>{options?.categories.map(category=><option value={category.id} key={category.id}>{category.name}</option>)}</select></label><button type="button" className="btn-secondary" disabled={busy||!name.trim()} onClick={()=>void reviewProduct()}>Review Product matches</button>{review&&<div className="rounded border border-amber-200 bg-amber-50 p-3"><b>{review.candidates.length?'Likely existing Products':'No likely Product matches'}</b>{review.candidates.map(candidate=><p key={candidate.id}>{candidate.name} · {candidate.sku} <button type="button" className="text-orange-800 underline" onClick={()=>{setMode('existing');setProductId(candidate.id);setReview(null)}}>Add SKU here</button></p>)}{review.candidates.length>0&&<label className="mt-2 flex gap-2"><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/>I reviewed these Products and still need a new Product.</label>}</div>}</>}
      <label className="block">SKU / Part Number<input className="field mt-1 w-full" name="partNumber" required maxLength={100} value={partNumber} onChange={event=>{setPartNumber(event.target.value);setReview(null)}}/></label><label className="block">Catalog Source<select className="field mt-1 w-full" name="catalogSourceChoice" required value={source} onChange={event=>setSource(event.target.value)}><option value="">Choose classification</option><option value="UNCLASSIFIED">Unclassified</option><option value="PRICE_LIST">Price List</option><option value="PE_LIST">PE List</option><option value="ODM">ODM / Custom SKU</option></select></label><label className="block">Description (optional)<input className="field mt-1 w-full" name="description" maxLength={2000}/></label>{source==='ODM'&&<OdmDetailsFields/>}<input type="hidden" name="active" value="true"/>
      <div className="flex justify-end gap-2"><button type="button" className="btn-secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="btn-primary" disabled={busy||!options||!partNumber.trim()||!source||mode==='existing'&&!productId||mode==='new'&&(!review||review.candidates.length>0&&!acknowledged)}>Create catalog SKU</button></div></form></div></div>;
}
