import { operationalTaskWhere, operationalActivityWhere, operationalOpportunityWhere } from '@/lib/operational-where';
import Link from 'next/link';
import { Content, PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { getLabels, getSettings } from '@/lib/configuration';
import { prisma } from '@/lib/prisma';
import { daysSince, engagementAccountWhere, engagementState, hasNoActivityInDays, latestAccountActivityOrder, lookbackStart, repAccountSummary, taskRollup } from '@/lib/engagement';
import { dayBounds } from '@/lib/work';
import { notFound } from 'next/navigation';
import type { Prisma } from '@prisma/client';
import { canViewBuiltInReport } from '@/lib/reporting';
export const dynamic = 'force-dynamic';
type Filters = { ownerId?: string; territory?: string; businessRole?: string; industry?: string; strategic?: string; minDays?: string; hasOpenTask?: string; hasOverdueTask?: string; hasOpenOpportunity?: string };
export default async function EngagementReport({ searchParams }: { searchParams: Promise<Filters> }) {
  const actor = await currentUser();
  if (!canViewBuiltInReport(actor,'ACCOUNT_ENGAGEMENT')) notFound();
  const f = await searchParams, [settings, labels] = await Promise.all([getSettings(prisma), getLabels(prisma)]), now = new Date(), today = dayBounds(now).start;
  const where: Prisma.AccountWhereInput = engagementAccountWhere(actor);
  if (actor.role !== 'SALES' && f.ownerId && Number.isSafeInteger(Number(f.ownerId))) where.ownerId = Number(f.ownerId);
  if (f.territory) where.territory = f.territory;
  if (f.industry) where.industry = f.industry;
  if (f.businessRole && ['END_USER','DISTRIBUTOR','VAR','ISV','OEM','PARTNER'].includes(f.businessRole)) where.businessRoles = { some: { role: f.businessRole as 'END_USER' } };
  if (f.strategic === 'yes' || f.strategic === 'no') where.strategicAccount = f.strategic === 'yes';
  const lookbackFrom = lookbackStart(settings.ACTIVITY_LOOKBACK_DAYS, now);
  const [accounts, reps, territories, industries, owners] = await Promise.all([
    prisma.account.findMany({ where, include: { owner: true, activities: { where: operationalActivityWhere, include: { activityType: true, user: true }, orderBy: latestAccountActivityOrder(), take: 1 }, tasks: { where: { AND: [operationalTaskWhere], status: { in: ['OPEN','IN_PROGRESS'] } }, select: { status: true, dueDate: true, archivedAt: true } }, opportunityMemberships: { where: { opportunity: { AND: [operationalOpportunityWhere], stage: { isClosed: false } } }, select: { opportunityId: true } } }, orderBy: { name: 'asc' } }),
    prisma.user.findMany({ where: { active: true, archivedAt: null, role: { in: ['SALES','SALES_MANAGER'] }, ...(actor.role === 'SALES' ? { id: actor.id } : {}) }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }),
    prisma.territory.findMany({ orderBy: { name: 'asc' } }), prisma.industry.findMany({ orderBy: { name: 'asc' } }), prisma.user.findMany({ where: { active: true, archivedAt: null, ...(actor.role === 'SALES' ? { id: actor.id } : {}) }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }),
  ]);
  const rows = accounts.map(a => { const last = a.activities[0] ?? null, days = daysSince(last?.activityDate ?? null, now), tasks = taskRollup(a.tasks, today); return { account: a, last, days, tasks, openOpportunity: a.opportunityMemberships.length > 0, state: engagementState(last?.activityDate ?? null, settings.STALE_ACCOUNT_WARNING_DAYS, now) }; }).filter(row => {
    const min = f.minDays ? Number(f.minDays) : null;
    return (min === null || (Number.isSafeInteger(min) && min >= 0 && hasNoActivityInDays(row.last?.activityDate ?? null,min,now))) && (f.hasOpenTask !== 'yes' || row.tasks.open > 0) && (f.hasOpenTask !== 'no' || row.tasks.open === 0) && (f.hasOverdueTask !== 'yes' || row.tasks.overdue > 0) && (f.hasOverdueTask !== 'no' || row.tasks.overdue === 0) && (f.hasOpenOpportunity !== 'yes' || row.openOpportunity) && (f.hasOpenOpportunity !== 'no' || !row.openOpportunity);
  });
  const repIds = reps.map(r => r.id);
  const [overdueTasks, recentActivities] = await Promise.all([
    prisma.task.groupBy({ by: ['assignedToId'], where: { AND: [operationalTaskWhere], status: { in: ['OPEN','IN_PROGRESS'] }, dueDate: { lt: today }, assignedToId: { in: repIds } }, _count: { _all: true } }),
    prisma.activity.groupBy({ by: ['userId'], where: { AND: [operationalActivityWhere], activityDate: { gte: lookbackFrom }, userId: { in: repIds } }, _count: { _all: true } }),
  ]);
  const accountCounts = await prisma.account.findMany({ where: { archivedAt: null, status: 'ACTIVE', ownerId: { in: repIds } }, select: { ownerId: true, activities: { where: operationalActivityWhere, orderBy: { activityDate: 'desc' }, take: 1, select: { activityDate: true } } } });
  return <Content><PageHeader eyebrow="Sales reporting" title="Account engagement" description={`Stale after ${settings.STALE_ACCOUNT_WARNING_DAYS} days · rep activities in the last ${settings.ACTIVITY_LOOKBACK_DAYS} days`}/>
    <form className="panel mb-5 grid gap-3 p-5 sm:grid-cols-3 lg:grid-cols-5"><label className="text-sm">Account owner<select className="field" name="ownerId" defaultValue={f.ownerId ?? ''} disabled={actor.role === 'SALES'}><option value="">All owners</option>{owners.map(r=><option key={r.id} value={r.id}>{r.firstName} {r.lastName}</option>)}</select></label><label className="text-sm">Territory<select className="field" name="territory" defaultValue={f.territory ?? ''}><option value="">All</option>{territories.map(t=><option key={t.code} value={t.code}>{t.name}</option>)}</select></label><label className="text-sm">Business role<select className="field" name="businessRole" defaultValue={f.businessRole ?? ''}><option value="">All</option>{(['END_USER','DISTRIBUTOR','VAR','ISV','OEM','PARTNER'] as const).map(x=><option key={x} value={x}>{labels[x]}</option>)}</select></label><label className="text-sm">Industry<select className="field" name="industry" defaultValue={f.industry ?? ''}><option value="">All</option>{industries.map(i=><option key={i.code} value={i.code}>{i.name}</option>)}</select></label><label className="text-sm">Strategic<select className="field" name="strategic" defaultValue={f.strategic ?? ''}><option value="">All</option><option value="yes">Yes</option><option value="no">No</option></select></label><label className="text-sm">At least days since activity<input className="field" type="number" min="0" name="minDays" defaultValue={f.minDays ?? ''}/></label>{(['hasOpenTask','hasOverdueTask','hasOpenOpportunity'] as const).map(key=><label className="text-sm" key={key}>{key === 'hasOpenTask' ? 'Open task' : key === 'hasOverdueTask' ? 'Overdue task' : 'Open opportunity'}<select className="field" name={key} defaultValue={f[key] ?? ''}><option value="">Any</option><option value="yes">Yes</option><option value="no">No</option></select></label>)}<div className="flex items-end"><button className="btn-primary">Apply filters</button></div></form>
    <section className="panel mb-6 overflow-x-auto"><h2 className="p-5 text-lg font-semibold">Accounts ({rows.length})</h2><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Account','Owner','Last Activity','Performed by','Type','Days','Status','Open tasks','Overdue','Open opportunity','Strategic'].map(x=><th key={x} className="px-3 py-2">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(({account,last,days,state,tasks,openOpportunity})=><tr key={account.id}><td className="px-3 py-2"><Link className="text-orange-800" href={`/accounts/${account.id}`}>{account.name}</Link></td><td className="px-3 py-2">{account.owner ? `${account.owner.firstName} ${account.owner.lastName}` : 'Unassigned'}</td><td className="px-3 py-2">{last?.activityDate.toISOString().slice(0,16).replace('T',' ') ?? 'Never'}</td><td className="px-3 py-2">{last?.user ? `${last.user.firstName} ${last.user.lastName}` : '—'}</td><td className="px-3 py-2">{last?.activityType.name ?? '—'}</td><td className="px-3 py-2">{days ?? '—'}</td><td className="px-3 py-2">{state}</td><td className="px-3 py-2">{tasks.open}</td><td className="px-3 py-2">{tasks.overdue}</td><td className="px-3 py-2">{openOpportunity ? 'Yes' : 'No'}</td><td className="px-3 py-2">{account.strategicAccount ? 'Yes' : 'No'}</td></tr>)}</tbody></table></section>
    <section className="panel overflow-x-auto"><h2 className="p-5 text-lg font-semibold">Sales activity by rep</h2><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Rep','Accounts owned','Accounts with no activity within threshold','Overdue tasks','Activities in lookback'].map(x=><th className="px-3 py-2" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{reps.map(rep=>{const owned=repAccountSummary(accountCounts.filter(a=>a.ownerId===rep.id),settings.STALE_ACCOUNT_WARNING_DAYS,now); return <tr key={rep.id}><td className="px-3 py-2">{rep.firstName} {rep.lastName}</td><td className="px-3 py-2">{owned.owned}</td><td className="px-3 py-2">{owned.withoutRecentActivity}</td><td className="px-3 py-2">{overdueTasks.find(x=>x.assignedToId===rep.id)?._count._all ?? 0}</td><td className="px-3 py-2">{recentActivities.find(x=>x.userId===rep.id)?._count._all ?? 0}</td></tr>;})}</tbody></table></section></Content>;
}
