'use client';
import { useState, useTransition } from 'react';
import { ImportSearchPicker } from '@/components/import-search-picker';
import { correctReference, createCleanupAccount } from './actions';
import type { MaintenanceField } from '@/lib/price-exception-maintenance';

export type EditorRow={id:number;updatedAt:string;archived:boolean;assignedSalesRepUserId:number|null;roles:{field:'distributorAccountId'|'varAccountId'|'endUserAccountId';label:string;source:string|null;current:string|null;id:number|null}[];lines:{id:number;sourceSku:string|null;productSkuId:number|null;linkedSku:string|null}[]};
type Choice={id:number;name:string};
type Options={industries:{code:string;name:string}[];territories:{code:string;name:string}[]};
export function CleanupEditor({row,accounts,users,skus,accountOptions}:{row:EditorRow;accounts:Choice[];users:Choice[];skus:Choice[];accountOptions:Options}){
  const [field,setField]=useState<MaintenanceField>('distributorAccountId');
  const [lineId,setLineId]=useState<number|null>(null);
  const [target,setTarget]=useState<number|null>(null);
  const [creating,setCreating]=useState(false);
  const [name,setName]=useState('');const [role,setRole]=useState('DISTRIBUTOR');const [territory,setTerritory]=useState('');const [industry,setIndustry]=useState('');
  const [review,setReview]=useState<{matches:Choice[]}|null>(null);const [ack,setAck]=useState(false);
  const [errors,setErrors]=useState<Record<string,string>>({});const [message,setMessage]=useState('');const [created,setCreated]=useState<Choice|null>(null);
  const [busy,start]=useTransition();
  const party=row.roles.find(item=>item.field===field);
  const choices=field==='productSkuId'?skus:field==='assignedSalesRepUserId'?users:[...accounts,...(created?[created]:[])];
  const original=field==='productSkuId'?row.lines.find(line=>line.id===lineId)?.productSkuId:field==='assignedSalesRepUserId'?row.assignedSalesRepUserId:party?.id;
  function changeField(value:MaintenanceField){setField(value);setTarget(null);setLineId(null);setMessage('');}
  function openCreate(){setCreating(true);setName(party?.source??'');setRole(field==='varAccountId'?'VAR':field==='endUserAccountId'?'END_USER':'DISTRIBUTOR');setReview(null);setAck(false);setErrors({});}
  function create(confirmed:boolean){const form=new FormData();form.set('name',name);form.set('status','ACTIVE');form.append('roles',role);form.set('territory',territory);form.set('industry',industry);start(async()=>{const result=await createCleanupAccount(form,confirmed,ack);if(result.kind==='created'){setCreated(result.account);setTarget(result.account.id);setCreating(false);setMessage(`Account ${result.account.name} created. Save the Account link to apply it to this PE.`);}else if(result.kind==='review'){setReview(result);setAck(false);}else if(result.kind==='validation')setErrors(result.errors);else setMessage(result.message);});}
  function save(){if(!target||target===original)return;start(async()=>{const result=await correctReference(row.id,field,target,row.updatedAt,lineId??undefined);if(result.ok)window.location.reload();else setMessage(result.message);});}
  return <section className="mt-3 rounded border border-orange-200 bg-orange-50/30 p-4 text-sm"><h3 className="font-semibold">Correct CRM relationships</h3><p className="mt-1 text-xs text-slate-600">Choose a record and save explicitly. Imported source values and pricing history stay intact.</p>{row.archived?<p className="mt-2 text-amber-800">Archived Price Exceptions are review only.</p>:<div className="mt-3 grid gap-3 md:grid-cols-3"><label className="label">Correction<select className="field mt-1" value={field} onChange={event=>changeField(event.target.value as MaintenanceField)}>{row.roles.map(item=><option key={item.field} value={item.field}>{item.label}</option>)}<option value="assignedSalesRepUserId">Salesperson / owner</option><option value="productSkuId">SKU mapping</option></select></label>{field==='productSkuId'&&<label className="label">Pricing line<select className="field mt-1" value={lineId??''} onChange={event=>{setLineId(Number(event.target.value)||null);setTarget(null)}}><option value="">Choose line…</option>{row.lines.map(line=><option key={line.id} value={line.id}>{line.sourceSku??'(blank source SKU)'} → {line.linkedSku??'Unresolved'} (#{line.id})</option>)}</select></label>}<div className="min-w-0 md:col-span-2"><p className="label">{field==='productSkuId'?'Active SKU':field==='assignedSalesRepUserId'?'Active salesperson':'Active Account'}</p><ImportSearchPicker label={field==='productSkuId'?'active SKU':field==='assignedSalesRepUserId'?'active salesperson':'active Account'} items={choices} value={target} onChange={setTarget} emptyLabel="Choose correction…" disabled={busy||field==='productSkuId'&&!lineId}/></div>{party&&<p className="md:col-span-3 text-xs">Original source: <strong>{party.source??'—'}</strong> · Current CRM Account: <strong>{party.current??'Unlinked'}</strong></p>}<div className="md:col-span-3 flex flex-wrap items-center gap-3">{party&&<button type="button" className="btn-secondary" onClick={openCreate}>Create Account…</button>}<button type="button" className="btn-primary" disabled={busy||!target||target===original||field==='productSkuId'&&!lineId} onClick={save}>Save correction</button></div></div>}{message&&<p className="mt-2 text-amber-800" role="status">{message}</p>}
    {creating&&<div role="dialog" aria-modal="true" aria-label="Create Account" className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-3"><div className="w-full max-w-xl rounded bg-white p-5 shadow-xl"><h3 className="text-lg font-semibold">Create Account for {party?.label}</h3><p className="text-sm text-slate-600">Source: {party?.source??'—'}. Creation adds the Account to CRM now; linking it to the PE requires Save correction.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2">Account Name<input className="field mt-1 w-full" maxLength={200} value={name} onChange={event=>{setName(event.target.value);setReview(null)}}/>{errors.name&&<span className="text-red-700">{errors.name}</span>}</label><label>Account Type / role<select className="field mt-1 w-full" value={role} onChange={event=>setRole(event.target.value)}><option value="DISTRIBUTOR">Distributor</option><option value="VAR">VAR / Reseller</option><option value="END_USER">End User</option><option value="ISV">ISV</option><option value="OEM">OEM</option><option value="PARTNER">Partner</option></select></label><label>Status<input className="field mt-1 w-full" value="Active" disabled/></label><label>Territory<select className="field mt-1 w-full" value={territory} onChange={event=>setTerritory(event.target.value)}><option value="">None selected</option>{accountOptions.territories.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select>{errors.territory&&<span className="text-red-700">{errors.territory}</span>}</label><label>Industry<select className="field mt-1 w-full" value={industry} onChange={event=>setIndustry(event.target.value)}><option value="">None selected</option>{accountOptions.industries.map(item=><option key={item.code} value={item.code}>{item.name}</option>)}</select>{errors.industry&&<span className="text-red-700">{errors.industry}</span>}</label></div>{review&&<div className="mt-3 rounded border border-amber-300 bg-amber-50 p-3"><p className="font-semibold">{review.matches.length?'Likely duplicate Accounts found':'No likely duplicate Accounts found'}</p>{review.matches.map(match=><div key={match.id}>{match.name} · #{match.id} <button type="button" className="text-orange-800 underline" onClick={()=>{setCreated(match);setTarget(match.id);setCreating(false)}}>Use existing</button></div>)}{review.matches.length>0&&<label className="mt-2 flex gap-2"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/>I reviewed these matches and still want a new Account.</label>}</div>}<div className="mt-4 flex justify-end gap-2"><button className="btn-secondary" type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="btn-primary" type="button" disabled={busy||!name.trim()||!!review&&review.matches.length>0&&!ack} onClick={()=>create(!!review)}>{review?'Confirm Create Account':'Review Account creation'}</button></div></div></div>}
  </section>;
}
