import Link from "next/link";
import { notFound } from "next/navigation";
import { TableScroll } from "@/components/table-scroll";
import { Content, PageHeader } from "@/components/shell";
import { currentUser } from "@/lib/current-user";
import { audienceContactInclude, audienceSummary, canExportAudience, canManageAudience, canViewAudience, resolveAudienceContactIds, validateAudienceConfig, validEmail } from "@/lib/marketing-audiences";
import { marketingPreferenceLabels } from "@/lib/contacts";
import { prisma } from "@/lib/prisma";
import { clearAudienceSelection, duplicateAudience, includeContact, selectAllMatching, setAudienceArchived, setContactSelection } from "../actions";
import { SaveSuccess } from "@/components/save-success";
import { saveFeedbackMessage } from "@/lib/save-feedback";
export const dynamic="force-dynamic";
const PAGE_SIZE=50;
export default async function AudiencePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{page?:string;saved?:string}>}){
  const id=Number((await params).id),actor=await currentUser();if(!Number.isSafeInteger(id)||id<=0)notFound();
  const audience=await prisma.marketingAudience.findUnique({where:{id},include:{owner:true}});if(!audience||!canViewAudience(actor,audience))notFound();
  let config;try{config=validateAudienceConfig(audience.filterConfig);}catch(error){return <Content><PageHeader eyebrow="Marketing Audiences" title={audience.name} action={<Link className="btn-secondary" href="/marketing/audiences">All audiences</Link>}/><div role="alert" className="panel border-red-200 p-6 text-red-800"><strong>These saved filters cannot run safely.</strong><p className="mt-2 text-sm">{error instanceof Error?error.message:"The configuration is invalid."}</p>{canManageAudience(actor,audience)&&<Link className="btn-secondary mt-4" href={`/marketing/audiences/${id}/edit`}>Review filters</Link>}</div></Content>}
  const resolved=await resolveAudienceContactIds(prisma,audience),summary=await audienceSummary(prisma,resolved.selected,resolved.matched.length),matched=new Set(resolved.matched),selected=new Set(resolved.selected),override=new Map(resolved.overrides.map(x=>[x.contactId,x.kind]));
  const query=await searchParams,candidateIds=[...new Set([...resolved.matched,...resolved.overrides.map(x=>x.contactId)])].sort((a,b)=>a-b),pages=Math.max(1,Math.ceil(candidateIds.length/PAGE_SIZE)),requested=Number(query.page),page=Number.isSafeInteger(requested)&&requested>0?Math.min(requested,pages):1,ids=candidateIds.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const contacts=await prisma.contact.findMany({where:{id:{in:ids}},include:audienceContactInclude,orderBy:[{lastName:"asc"},{firstName:"asc"}]});
  const manage=canManageAudience(actor,audience)&&!audience.archivedAt,exportable=canExportAudience(actor,audience)&&!audience.archivedAt;
  const unresolved=config.tradeShowId?await prisma.tradeShowLead.count({where:{tradeShowId:config.tradeShowId,contactId:null}}):null;
  const metric=[['Matches Criteria',summary.matched],['Final Selected',summary.selected],['Opted In',summary.optedIn],['Unknown',summary.unknown],['Opted Out',summary.optedOut],['Missing Email',summary.missingEmail],['Marketing Ready',summary.marketingReady]] as const;
  return <Content>
    <PageHeader eyebrow="Marketing Audiences" title={audience.name} description={`${audience.visibility==="PERSONAL"?"Personal":"Shared"} · owned by ${audience.owner.firstName} ${audience.owner.lastName}`} action={<div className="flex flex-wrap gap-2"><Link className="btn-secondary" href="/marketing/audiences">All audiences</Link>{manage&&<Link className="btn-secondary" href={`/marketing/audiences/${id}/edit`}>Edit</Link>}{manage&&<form action={duplicateAudience}><input type="hidden" name="audienceId" value={id}/><button className="btn-secondary">Duplicate</button></form>}{manage&&<form action={setAudienceArchived}><input type="hidden" name="audienceId" value={id}/><input type="hidden" name="archived" value="true"/><button className="btn-secondary">Archive</button></form>}</div>}/>
    {saveFeedbackMessage(query.saved, 'Audience') && <SaveSuccess message={saveFeedbackMessage(query.saved, 'Audience')!}/>}
    {audience.description&&<p className="mb-5 text-sm text-slate-600">{audience.description}</p>}
    {audience.archivedAt&&<div className="mb-5 rounded border border-slate-300 bg-slate-50 p-3 text-sm">This audience is archived. Its live preview remains available, but changes and exports are disabled.</div>}
    <section className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-7" aria-label="Audience summary">{metric.map(([label,value])=><div className="panel p-3" key={label}><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</section>
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded border border-orange-200 bg-orange-50/60 p-3 text-sm"><div><strong>Audience membership updates automatically using current SalesHub data.</strong><span className="mt-1 block text-slate-600">{resolved.overrides.filter(x=>x.kind==="INCLUDE").length} manually included · {resolved.overrides.filter(x=>x.kind==="EXCLUDE").length} manually excluded</span>{unresolved!==null&&unresolved>0&&<span className="mt-2 block text-slate-700">{unresolved} Trade Show leads are not linked to Contacts and are not included in this audience. <Link className="font-semibold text-orange-800 underline" href={`/trade-shows/${config.tradeShowId}/contact-resolution?returnTo=${encodeURIComponent(`/marketing/audiences/${id}`)}`}>Review Leads</Link></span>}</div>{manage&&<div className="flex flex-wrap gap-2"><form action={selectAllMatching}><input type="hidden" name="audienceId" value={id}/><button className="btn-secondary">Select All Matching</button></form><form action={clearAudienceSelection}><input type="hidden" name="audienceId" value={id}/><button className="btn-secondary">Clear Selection</button></form></div>}</div>
    {(manage||exportable)&&<div className="panel mb-5 flex flex-wrap items-end gap-3 p-4">{manage&&<form action={includeContact} className="flex flex-wrap items-end gap-2"><input type="hidden" name="audienceId" value={id}/><div><label className="label" htmlFor="contactId">Manually include Contact ID</label><input className="field w-52" type="number" min="1" id="contactId" name="contactId" required/></div><button className="btn-secondary">Include Contact</button></form>}{exportable&&<div className="ml-auto flex flex-wrap gap-4"><div><a className="btn-secondary" href={`/marketing/audiences/${id}/export`}>Export Selected</a><span className="mt-1 block max-w-52 text-xs text-slate-500">Final selected Contacts for internal review or use.</span></div><div><a className="btn-primary" href={`/marketing/audiences/${id}/export?ready=1`}>Export Marketing-Ready</a><span className="mt-1 block max-w-56 text-xs text-slate-500">Only Opted In Contacts with usable email addresses.</span></div></div>}</div>}
    <div className="panel"><TableScroll label="Audience contacts"><table className="w-full min-w-[880px] text-left text-sm"><thead className="sticky top-0 border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Account</th><th className="px-4 py-3">Contact Info</th><th className="px-4 py-3">Marketing</th><th className="px-4 py-3">Source / Selection</th></tr></thead><tbody>{contacts.map(c=>{const isSelected=selected.has(c.id),state=matched.has(c.id)?override.get(c.id)==="EXCLUDE"?"Manually excluded":"Matches audience criteria":override.get(c.id)==="INCLUDE"?"Manually included":"Outside audience criteria",lead=c.tradeShowLeads[0];return <tr className={`border-b odd:bg-white even:bg-slate-50/60 hover:bg-orange-50/50 ${!isSelected?"opacity-60":""}`} key={c.id}><td className="px-4 py-3"><Link className="font-semibold text-orange-800 underline" href={`/contacts/${c.id}`}>{c.firstName} {c.lastName}</Link><span className="block text-xs text-slate-500">{c.title??"No title"} · #{c.id}</span></td><td className="px-4 py-3">{c.account?.name??"Unassigned"}<span className="block text-xs text-slate-500">{c.account?.businessRoles.map(x=>x.role.replaceAll("_"," ")).join(", ")||c.account?.industryCategory?.name||"—"}</span></td><td className="px-4 py-3">{c.email??"No email"}<span className="block text-xs text-slate-500">{c.phone??"No phone"}</span></td><td className="px-4 py-3"><span className={`rounded px-2 py-1 text-xs font-semibold ${c.marketingPreference==="OPTED_IN"?"bg-emerald-50 text-emerald-800":c.marketingPreference==="OPTED_OUT"?"bg-rose-50 text-rose-800":"bg-slate-100 text-slate-600"}`}>{marketingPreferenceLabels[c.marketingPreference]}</span><span className="mt-1 block text-xs text-slate-500">{c.marketingPreference==="OPTED_IN"&&validEmail(c.email)?"Marketing Ready":"Not delivery-ready"}</span></td><td className="px-4 py-3">{lead?<span>{lead.tradeShow.name}<span className="block text-xs text-slate-500">{lead.routing.replaceAll("_"," ")}</span></span>:<span className="text-slate-500">No Trade Show context</span>}<div className="mt-2 flex items-center gap-2"><span className="text-xs font-medium">{state}</span>{manage&&<form action={setContactSelection}><input type="hidden" name="audienceId" value={id}/><input type="hidden" name="contactId" value={c.id}/><input type="hidden" name="selected" value={isSelected?"false":"true"}/><button className="text-xs font-semibold text-orange-800 underline">{isSelected?"Deselect":"Select"}</button></form>}</div></td></tr>})}</tbody></table></TableScroll>{!contacts.length&&<p className="p-8 text-center text-sm text-slate-500">No Contacts match this audience.</p>}</div>
    <div className="mt-4 flex items-center justify-between text-sm text-slate-600"><span>{candidateIds.length} preview records · Page {page} of {pages}</span><div className="flex gap-2">{page>1&&<Link className="btn-secondary" href={`/marketing/audiences/${id}?page=${page-1}`}>Previous</Link>}{page<pages&&<Link className="btn-secondary" href={`/marketing/audiences/${id}?page=${page+1}`}>Next</Link>}</div></div>
  </Content>;
}
