import Link from 'next/link';
import { Content, PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { canManageAttribution, campaignStatuses } from '@/lib/marketing-attribution';
import { prisma } from '@/lib/prisma';
import { saveCampaign } from '@/app/marketing/attribution/actions';
import { notFound } from 'next/navigation';

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; year?: string; archived?: string }> }) {
  const actor = await currentUser(); if (!canManageAttribution(actor)) notFound();
  const filters = await searchParams, q = (filters.q ?? '').trim().slice(0, 120), year = Number(filters.year);
  const campaigns = await prisma.marketingCampaign.findMany({ where: { ...(filters.archived === 'true' ? { archivedAt: { not: null } } : { archivedAt: null }), ...(q ? { name: { contains: q, mode: 'insensitive' } } : {}), ...(campaignStatuses.includes(filters.status as never) ? { status: filters.status } : {}), ...(Number.isInteger(year) && year >= 1900 && year <= 2200 ? { year } : {}) }, include: { tradeShow: { select: { id: true, name: true } }, _count: { select: { influences: true } } }, orderBy: [{ year: 'desc' }, { name: 'asc' }] });
  return <Content><PageHeader eyebrow="Marketing" title="Campaigns" description="Marketing initiatives and their recorded touches." action={<Link className="btn-secondary" href="/marketing/lead-sources">Lead Sources</Link>}/>
    <form className="panel mb-5 flex flex-wrap gap-2 p-4"><input className="field" name="q" defaultValue={q} placeholder="Search Campaigns"/><select className="field" name="status" defaultValue={filters.status ?? ''}><option value="">All statuses</option>{campaignStatuses.map(status => <option key={status}>{status}</option>)}</select><input className="field w-28" name="year" type="number" placeholder="Year" defaultValue={filters.year ?? ''}/><label className="flex items-center gap-1 text-sm"><input name="archived" value="true" type="checkbox" defaultChecked={filters.archived === 'true'}/>Archived</label><button className="btn-secondary">Filter</button></form>
    <div className="panel divide-y">{campaigns.map(campaign => <div key={campaign.id} className="flex flex-wrap items-center justify-between gap-2 p-4 text-sm"><div><Link className="font-medium text-orange-800 underline" href={`/marketing/campaigns/${campaign.id}`}>{campaign.name}</Link><div className="text-slate-500">{campaign.year ?? 'No year'} · {campaign.status} · {campaign._count.influences} touches{campaign.tradeShow ? ` · ${campaign.tradeShow.name}` : ''}</div></div></div>)}{!campaigns.length && <p className="p-4 text-sm text-slate-500">No Campaigns match.</p>}</div>
    <form action={saveCampaign} className="panel mt-5 grid gap-3 p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 text-lg font-semibold">Create Campaign</h2><label className="text-sm">Name<input className="field mt-1 block w-full" name="name" required maxLength={160}/></label><label className="text-sm">Year<input className="field mt-1 block w-full" name="year" type="number" min={1900} max={2200}/></label><label className="text-sm">Category<input className="field mt-1 block w-full" name="category" maxLength={120}/></label><label className="text-sm">Status<select className="field mt-1 block w-full" name="status">{campaignStatuses.map(status => <option key={status}>{status}</option>)}</select></label><label className="text-sm">Start date<input className="field mt-1 block w-full" name="startDate" type="date"/></label><label className="text-sm">End date<input className="field mt-1 block w-full" name="endDate" type="date"/></label><label className="text-sm sm:col-span-2">Description<textarea className="field mt-1 block w-full" name="description" maxLength={10000}/></label><button className="btn-primary justify-self-start">Create Campaign</button></form>
  </Content>;
}
