import Link from 'next/link';
import { NAV_CATEGORIES } from '@/lib/navigation-categories';
import { SupportCasePriority, SupportCaseStatus } from '@prisma/client';
import { Content, PageHeader } from '@/components/shell';
import { can } from '@/lib/authorization';
import { requirePermission } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { listSupportCases, supportPriorityLabels, supportStatusLabels } from '@/lib/support-cases';
import { supportFormOptions } from '@/lib/support-case-ui';
import { supportAge } from '@/lib/support-case-display';
import { formatDateTimeForUser } from '@/lib/display-format';
export const dynamic = 'force-dynamic';
type Params = Record<string, string | string[] | undefined>;
const one = (v: string | string[] | undefined) => typeof v === 'string' ? v : '';
const positive = (v: string) => /^\d+$/.test(v) && Number(v) > 0 && Number.isSafeInteger(Number(v)) ? Number(v) : undefined;
function dateBound(value: string, end = false) { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return undefined; const date = new Date(`${value}T00:00:00Z`); if (Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== value) return undefined; return end ? new Date(date.getTime() + 86400000) : date; }
export default async function SupportCasesPage({ searchParams }: { searchParams: Promise<Params> }) {
  const actor = await requirePermission('support-cases.read'); const raw = await searchParams;
  const selected = Object.fromEntries(Object.entries(raw).map(([key, value]) => [key, one(value)])) as Record<string, string>;
  const options = { page: positive(selected.page), archive: ['active', 'archived', 'all'].includes(selected.archive) ? selected.archive as 'active' | 'archived' | 'all' : 'active', assignedToId: positive(selected.assignedToId), status: Object.values(SupportCaseStatus).includes(selected.status as SupportCaseStatus) ? selected.status as SupportCaseStatus : undefined, priority: Object.values(SupportCasePriority).includes(selected.priority as SupportCasePriority) ? selected.priority as SupportCasePriority : undefined, categoryId: positive(selected.categoryId), account: selected.account, product: selected.product, openedFrom: dateBound(selected.openedFrom), openedTo: dateBound(selected.openedTo, true), search: selected.q, sort: ['current', 'newest', 'oldest', 'priority', 'follow-up', 'number', 'updated'].includes(selected.sort) ? selected.sort as 'current' | 'newest' | 'oldest' | 'priority' | 'follow-up' | 'number' | 'updated' : 'current' };
  const [result, choices] = await Promise.all([listSupportCases(prisma, actor, options), supportFormOptions(actor)]);
  const href = (page: number) => { const p = new URLSearchParams(); Object.entries(selected).forEach(([key, value]) => { if (key !== 'page' && value) p.set(key, value); }); p.set('page', String(page)); return `/support/cases?${p}`; };
  const filtered = Object.entries(selected).some(([key, value]) => key !== 'page' && value && value !== 'active' && value !== 'current');
  const zone = choices.zone;
  return <Content><PageHeader eyebrow={NAV_CATEGORIES.support} title="Support Cases" description="Track and resolve customer issues." action={can(actor, 'support-cases.write') ? <Link className="btn-primary" href="/support/cases/new">New case</Link> : undefined}/>
    <form method="get" className="filter-panel filter-grid filter-row mb-4" aria-label="Filter Support Cases">
      <label className="label">Search<input className="field filter-control" name="q" defaultValue={selected.q} placeholder="Case, contact, subject, serial"/></label>
      <label className="label">Support Rep<select className="field filter-control" name="assignedToId" defaultValue={selected.assignedToId}><option value="">All reps</option>{choices.assignees.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
      <label className="label">Status<select className="field filter-control" name="status" defaultValue={selected.status}><option value="">All statuses</option>{Object.entries(supportStatusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label className="label">Priority<select className="field filter-control" name="priority" defaultValue={selected.priority}><option value="">All priorities</option>{Object.entries(supportPriorityLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label>
      <label className="label">Account<input className="field filter-control" name="account" defaultValue={selected.account} placeholder="Account name"/></label>
      <label className="label">Category<select className="field filter-control" name="categoryId" defaultValue={selected.categoryId}><option value="">All categories</option>{choices.categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
      <label className="label">Product / SKU<input className="field filter-control" name="product" defaultValue={selected.product} placeholder="Part number"/></label>
      <label className="label">Opened from<input className="field filter-control" type="date" name="openedFrom" defaultValue={selected.openedFrom}/></label>
      <label className="label">Opened through<input className="field filter-control" type="date" name="openedTo" defaultValue={selected.openedTo}/></label>
      <label className="label">Archive<select className="field filter-control" name="archive" defaultValue={options.archive}><option value="active">Current</option><option value="archived">Archived</option><option value="all">All</option></select></label>
      <label className="label">Sort<select className="field filter-control" name="sort" defaultValue={options.sort}><option value="current">Current statuses first</option><option value="newest">Newest opened</option><option value="oldest">Oldest opened</option><option value="priority">Priority</option><option value="follow-up">Next follow-up</option><option value="number">Case Number</option><option value="updated">Recently updated</option></select></label>
      <div className="filter-actions flex items-end gap-2"><button className="btn-filter-primary" type="submit">Apply</button><Link className="btn-filter-secondary" href="/support/cases">Clear</Link></div>
    </form>
    <div className="grid gap-3 lg:hidden">{result.cases.map(row => { const overdue = !!row.nextFollowUpAt && row.nextFollowUpAt < new Date() && !['RESOLVED','CLOSED'].includes(row.status); return <article key={row.id} className="panel min-w-0 p-4 text-sm">
      <div className="flex flex-wrap items-start justify-between gap-2"><Link className="inline-flex min-h-11 items-center font-semibold text-orange-800 underline" href={`/support/cases/${row.id}`}>{row.caseNumber}</Link><span className={row.priority === 'CRITICAL' ? 'font-semibold text-red-800' : row.priority === 'HIGH' ? 'font-semibold text-amber-800' : 'text-slate-700'}>{supportPriorityLabels[row.priority]}</span></div>
      <p className="break-words font-semibold text-slate-950">{row.subject}</p><p className="mt-1 break-words text-slate-700">{row.customerNameText ?? row.account?.name ?? '—'}</p>
      <dl className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs"><div><dt className="text-slate-500">Status</dt><dd className="font-medium">{supportStatusLabels[row.status]}</dd></div><div><dt className="text-slate-500">Assigned Rep</dt><dd className="break-words font-medium">{row.assignedTo ? `${row.assignedTo.firstName} ${row.assignedTo.lastName}` : 'Unassigned'}</dd></div></dl>
      {overdue && <p className="mt-2 font-semibold text-red-800">Follow-up overdue</p>}{row.archivedAt && <p className="mt-2 text-xs text-slate-500">Archived</p>}
    </article>; })}{result.cases.length === 0 && <div className="panel p-8 text-center text-sm text-slate-600">{filtered ? 'No Support Cases match these filters.' : 'No Support Cases'}</div>}</div>
    <div className="panel hidden overflow-x-auto lg:block"><table className="w-full min-w-[1350px] text-left text-sm"><thead className="border-b border-slate-200 bg-slate-100 text-xs uppercase tracking-wide text-slate-600"><tr>{['Case Number','Customer / End User','Contact','Subject','Status','Priority','Category','Assigned To','Product / SKU','Serial Number','Opened','Next Follow-up','Age'].map(h => <th className="px-3 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{result.cases.map(row => { const overdue = !!row.nextFollowUpAt && row.nextFollowUpAt < new Date() && !['RESOLVED','CLOSED'].includes(row.status); return <tr key={row.id} className="align-top"><td className="px-3 py-3"><Link className="font-semibold text-orange-800 hover:underline" href={`/support/cases/${row.id}`}>{row.caseNumber}</Link>{row.archivedAt && <span className="block text-xs text-slate-500">Archived</span>}</td><td className="px-3 py-3">{row.customerNameText ?? row.account?.name ?? '—'}</td><td className="px-3 py-3">{row.contact ? `${row.contact.firstName} ${row.contact.lastName}` : '—'}</td><td className="px-3 py-3">{row.subject}</td><td className="px-3 py-3">{supportStatusLabels[row.status]}</td><td className="px-3 py-3"><span className={row.priority === 'CRITICAL' ? 'font-semibold text-red-800' : row.priority === 'HIGH' ? 'font-semibold text-amber-800' : ''}>{supportPriorityLabels[row.priority]}</span></td><td className="px-3 py-3">{row.category?.name ?? '—'}</td><td className="px-3 py-3">{row.assignedTo ? `${row.assignedTo.firstName} ${row.assignedTo.lastName}` : 'Unassigned'}</td><td className="px-3 py-3">{row.productSku?.partNumber ?? '—'}</td><td className="px-3 py-3">{row.serialNumber ?? '—'}</td><td className="px-3 py-3 whitespace-nowrap">{formatDateTimeForUser(row.openedAt, zone)}</td><td className="px-3 py-3 whitespace-nowrap">{row.nextFollowUpAt ? <>{formatDateTimeForUser(row.nextFollowUpAt, zone)}{overdue && <strong className="block text-red-800">Overdue</strong>}</> : '—'}</td><td className="px-3 py-3 whitespace-nowrap">{supportAge(row.openedAt, row.status, row.resolvedAt, row.closedAt)}</td></tr>; })}</tbody></table>{result.cases.length === 0 && <div className="p-10 text-center"><h2 className="font-semibold">{filtered ? 'No Support Cases match these filters.' : 'No Support Cases'}</h2>{!filtered && <p className="mt-1 text-sm text-slate-600">Support Cases will appear here as customer issues are opened.</p>}</div>}</div>
    <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-sm text-slate-600"><span>{result.count} cases · Page {result.page} of {result.pages}</span><div className="flex gap-2">{result.page > 1 && <Link className="btn-secondary" href={href(result.page - 1)}>Previous</Link>}{result.page < result.pages && <Link className="btn-secondary" href={href(result.page + 1)}>Next</Link>}</div></div>
  </Content>;
}
