import Link from 'next/link';
import { Content, PageHeader } from '@/components/shell';
import { prisma } from '@/lib/prisma';
import { taskWhere, taskTiming, taskStatuses, taskPriorities, type TaskFilters } from '@/lib/work';
import { workOptions } from '@/lib/work-options';
import { pageNumber } from '@/lib/crm-validation';
import { recordVisibility } from '@/lib/record-visibility';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<TaskFilters & {page?:string}>}) { const f=await searchParams; const where=taskWhere(f); const count=await prisma.task.count({where}); const {page,pages}=pageNumber(f.page,count); const [tasks,options]=await Promise.all([prisma.task.findMany({where,include:{account:true,opportunity:true,assignedTo:true},orderBy:[{dueDate:'asc'},{id:'desc'}],skip:(page-1)*20,take:20}),workOptions()]); const linkFor=(target:number)=>{const q=new URLSearchParams();Object.entries(f).forEach(([key,value])=>{if(value&&key!=='page')q.set(key,value);});q.set('page',String(target));return `/tasks?${q}`;};
  const sel=(key:keyof TaskFilters,label:string,items:{value:string;label:string}[]) => <label className="text-sm">{label}<select className="field" name={key} defaultValue={f[key]??''}><option value="">All</option>{items.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label>;
  const opts=(items:{id:number;name:string}[])=>items.map(x=>({value:String(x.id),label:x.name}));
  return <Content><PageHeader title="Tasks" eyebrow="CRM records" action={<Link className="btn-primary" href="/tasks/new">New task</Link>}/><form method="get" className="panel mb-5 grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm">Search<input className="field" name="q" defaultValue={f.q??''} placeholder="Subject or description"/></label><label className="text-sm">Record visibility<select className="field" name="visibility" defaultValue={recordVisibility(f.visibility)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All</option></select></label>{sel('status','Status',taskStatuses.map(x=>({value:x,label:x.replace('_',' ')})))}{sel('priority','Priority',taskPriorities.map(x=>({value:x,label:x})))}{sel('assignedToId','Assignee',opts(options.users))}{sel('accountId','Account',opts(options.accounts))}{sel('opportunityId','Opportunity',opts(options.opportunities))}<label className="text-sm">Due from<input className="field" name="dueFrom" type="date" defaultValue={f.dueFrom??''}/></label><label className="text-sm">Due through<input className="field" name="dueTo" type="date" defaultValue={f.dueTo??''}/></label><div className="flex items-end gap-2"><button className="btn-primary">Apply</button><Link className="btn-secondary" href="/tasks">Clear</Link></div></form><div className="panel overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b bg-slate-50"><tr>{['Task','State','Status','Priority','Assignee','Account','Opportunity','Due'].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y">{tasks.map(t=><tr key={t.id}><td className="p-4"><Link className="text-orange-800" href={`/tasks/${t.id}/edit`}>{t.subject}</Link></td><td className="p-4">{t.archivedAt ? <span className="rounded bg-slate-100 px-2 py-1 text-xs font-semibold">Archived</span> : 'Active'}</td><td className="p-4">{t.status}</td><td className="p-4">{t.priority}</td><td className="p-4">{t.assignedTo?`${t.assignedTo.firstName} ${t.assignedTo.lastName}`:'—'}</td><td className="p-4">{t.account?<Link href={`/accounts/${t.accountId}`} className="text-orange-800">{t.account.name}</Link>:'—'}</td><td className="p-4">{t.opportunity?<Link href={`/opportunities/${t.opportunityId}`} className="text-orange-800">{t.opportunity.name}</Link>:'—'}</td><td className="p-4">{t.dueDate?.toISOString().slice(0,10)??'—'} {!t.archivedAt&&taskTiming(t)&&<strong className="text-red-700">{taskTiming(t)}</strong>}</td></tr>)}</tbody></table>{!tasks.length&&<p className="p-6 text-sm text-slate-500">No tasks match these filters.</p>}</div><div className="mt-4 flex justify-between text-sm"><span>{count} tasks · Page {page} of {pages}</span><div className="flex gap-2">{page>1&&<Link className="btn-secondary" href={linkFor(page-1)}>Previous</Link>}{page<pages&&<Link className="btn-secondary" href={linkFor(page+1)}>Next</Link>}</div></div></Content>;
}
