import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module from 'node:module';
import path from 'node:path';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);
const require=Module.createRequire(fileURLToPath(import.meta.url));
const {demoSummary,addDemoDuration,daysDeployed,opportunityResult}=require(path.join(root,'lib/demo-operations.ts'));
const d=value=>new Date(`${value}T12:00:00Z`);
const unit=(ordinal,serialNumber=null,deployedAt=d('2026-09-01'),returnedAt=null)=>({id:ordinal,ordinal,serialNumber,status:returnedAt?'RETURNED':deployedAt?'DEPLOYED':'APPROVED',deployedAt,returnedAt,inventoryLocation:null});
const request=(units,extra={})=>({shippedAt:d('2026-09-01'),durationValue:1,durationUnit:'month',expectedReturnOverrideAt:null,items:[{quantity:units.length,units}],...extra});
test('logical quantity and partial returns determine open inventory independently of request status',()=>{
  const two=request([unit(1,'A',d('2026-09-01'),d('2026-09-20')),unit(2,'B')]);
  assert.deepEqual([demoSummary(two,d('2026-10-02')).total,demoSummary(two,d('2026-10-02')).deployed,demoSummary(two,d('2026-10-02')).returned,demoSummary(two,d('2026-10-02')).outstanding],[2,2,1,1]);
  assert.equal(demoSummary(two).open,true);
  assert.equal(demoSummary(request([unit(1,'A',d('2026-09-01'),d('2026-09-20'))]),d('2026-10-02')).open,false);
  assert.equal(demoSummary(request([unit(1,null,null)]),d('2026-10-02')).open,false);
  assert.equal(demoSummary(request([unit(1,null)]),d('2026-10-02')).open,true);
});
test('calendar duration, override, overdue and days deployed',()=>{
  assert.equal(addDemoDuration(d('2026-01-31'),1,'month').toISOString().slice(0,10),'2026-02-28');
  assert.equal(addDemoDuration(d('2026-09-01'),2,'week').toISOString().slice(0,10),'2026-09-15');
  const item=request([unit(1)],{expectedReturnOverrideAt:d('2026-11-01')});
  assert.equal(demoSummary(item,d('2026-10-02')).calculated.toISOString().slice(0,10),'2026-10-01');
  assert.equal(demoSummary(item,d('2026-10-02')).overdue,false);
  assert.equal(demoSummary(request([unit(1)]),d('2026-10-02')).overdue,true);
  assert.equal(demoSummary(request([unit(1,null,d('2026-09-01'),d('2026-09-20'))]),d('2026-10-02')).overdue,false);
  assert.equal(daysDeployed(unit(1),d('2026-09-10')),9);
  assert.equal(daysDeployed(unit(1,null,d('2026-09-01'),d('2026-09-20')),d('2026-10-02')),19);
});
test('opportunity and Project outcomes create attention without returning inventory',()=>{
  const open={stage:{isClosed:false,isWon:false}},won={stage:{isClosed:true,isWon:true}},lost={stage:{isClosed:true,isWon:false}};
  assert.deepEqual([opportunityResult(open),opportunityResult(won),opportunityResult(lost),opportunityResult(null)],['Open','Won','Lost','—']);
  const current=[unit(1)];const today=d('2026-09-10');
  assert.equal(demoSummary(request(current,{opportunity:won}),today).open,true);
  assert.equal(demoSummary(request(current,{opportunity:won}),today).recoveryAttention,false);
  assert.equal(demoSummary(request(current,{opportunity:lost}),today).recoveryAttention,true);
  assert.equal(demoSummary(request(current,{project:{status:'ACTIVE'}}),today).recoveryAttention,false);
  assert.equal(demoSummary(request(current,{project:{status:'CANCELLED'}}),today).recoveryAttention,true);
  assert.equal(demoSummary(request(current,{project:{status:'COMPLETED'}}),today).recoveryAttention,true);
  assert.equal(demoSummary(request(current),d('2026-10-02')).recoveryAttention,true);
});
test('cancelled request remains historical while physical deployment drives open and recovery metrics',()=>{
  const today=d('2026-09-10');
  const unshipped=demoSummary(request([unit(1,null,null)],{status:'CANCELLED',shippedAt:null}),today);
  assert.deepEqual([unshipped.deployed,unshipped.outstanding,unshipped.open,unshipped.overdue,unshipped.recoveryAttention],[0,0,false,false,false]);
  const outstanding=demoSummary(request([unit(1)],{status:'CANCELLED'}),today);
  assert.deepEqual([outstanding.deployed,outstanding.outstanding,outstanding.open,outstanding.overdue,outstanding.recoveryAttention],[1,1,true,false,true]);
  const overdue=demoSummary(request([unit(1)],{status:'CANCELLED'}),d('2026-10-02'));
  assert.deepEqual([overdue.open,overdue.overdue,overdue.recoveryAttention],[true,true,true]);
  const returned=demoSummary(request([unit(1,null,d('2026-09-01'),d('2026-09-05'))],{status:'CANCELLED'}),d('2026-10-02'));
  assert.deepEqual([returned.deployed,returned.returned,returned.outstanding,returned.open,returned.overdue,returned.recoveryAttention],[1,1,0,false,false,false]);
  const {matchesDemoReportRequest,matchesDemoReportUnit}=require(path.join(root,'lib/demo-operations.ts'));
  const units=[unit(1),unit(2,null,null)];
  const item={quantity:2,retiredAt:null,productSkuId:null,productSku:null,units};
  const cancelled={...request(units,{status:'CANCELLED'}),items:[item],accountId:1,requestedById:7,projectId:null,opportunityId:null};
  const summary=demoSummary(cancelled,today);
  assert.equal(matchesDemoReportRequest(cancelled,summary,{demoStatus:'CANCELLED',recovery:'yes'}),true);
  assert.equal(matchesDemoReportRequest(cancelled,summary,{demoStatus:'SHIPPED'}),false);
  assert.equal(matchesDemoReportUnit(item,units[0],{state:'open'}),true);
  assert.equal(matchesDemoReportUnit(item,units[1],{state:'open'}),false);
});
test('report filters include account-only open units and distinguish partial returns',()=>{
  const {matchesDemoReportRequest,matchesDemoReportUnit}=require(path.join(root,'lib/demo-operations.ts'));
  const units=[unit(1,'A',d('2026-09-01'),d('2026-09-20')),unit(2,null)];
  const item={quantity:2,retiredAt:null,productSkuId:20,productSku:{product:{id:10}},units};
  const demo={...request(units),items:[item],accountId:1,requestedById:7,projectId:null,opportunityId:null,status:'SHIPPED'};
  const summary=demoSummary(demo,d('2026-10-02'));
  assert.equal(matchesDemoReportRequest(demo,summary,{accountId:'1',overdue:'yes',recovery:'yes',demoStatus:'SHIPPED'}),true);
  assert.equal(matchesDemoReportRequest(demo,summary,{accountId:'2'}),false);
  assert.equal(matchesDemoReportRequest(demo,summary,{opportunityResult:'Won'}),false);
  assert.equal(matchesDemoReportUnit(item,units[0],{state:'returned',productId:'10',skuId:'20'}),true);
  assert.equal(matchesDemoReportUnit(item,units[1],{state:'returned'}),false);
  assert.equal(matchesDemoReportUnit(item,units[1],{state:'open',deployedFrom:'2026-09-01',deployedTo:'2026-09-02'}),true);
  assert.equal(matchesDemoReportUnit(item,units[0],{state:'open'}),false);
});
