import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module from 'node:module';
import path from 'node:path';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);
const originalLoad=Module._load;
Module._load=function(request,parent,isMain){if(request==='./accounts'&&parent?.filename.endsWith('demo-backfill.ts'))return {normalizeAccountName:value=>value.trim().toLowerCase().replace(/\s+/g,' ')};return originalLoad.call(this,request,parent,isMain)};
const require=Module.createRequire(fileURLToPath(import.meta.url));
const {backfillExistingRosaDemo,ExistingDemoError}=require(path.join(root,'lib/demo-backfill.ts'));
const {demoSummary}=require(path.join(root,'lib/demo-operations.ts'));
const actor={id:10,role:'ADMIN',active:true,archivedAt:null};
const requestId='560fbee9-9b3b-48a9-990a-720adc67291c';
function form(changes={}) {const data=new FormData();for(const [key,value] of Object.entries({requestId,demoNumber:'',status:'SHIPPED',accountId:'1',sourceAccount:'Acme',requestedAt:'2026-09-01',requestedBy:'Rosa User',reviewedAt:'2026-09-02',reviewedBy:'Rosa Reviewer',shippedAt:'2026-09-03',shippedBy:'Rosa Shipper',durationValue:'1',durationUnit:'week',sku0:'SKU-1',quantity0:'2',serials0:'A;B',tracking0:'1Z123',reason:'Missed import',...changes}))data.append(key,value);return data;}
function db(existingId=null){const state={requests:[],revisions:[],items:[],units:[]};let nextUnit=1;const client={state,demoRequest:{findUnique:async()=>existingId?{id:existingId}:null,findFirst:async()=>null,create:async({data})=>{const record={id:1,...data};state.requests.push(record);return record}},account:{findMany:async()=>[{id:1,name:'Acme'}]},productSku:{findMany:async()=>[{id:5,partNumber:'SKU-1'}]},user:{findMany:async()=>[]},demoSourceRevision:{create:async({data})=>state.revisions.push(data)},demoItem:{create:async({data})=>{const item={id:1,...data};state.items.push(item);return item}},demoUnit:{findMany:async()=>[...state.units],create:async({data})=>{const unit={id:nextUnit++,...data,serialNumber:null,deployedAt:null,returnedAt:null,inventoryLocation:null};state.units.push(unit);return unit},update:async({where,data})=>{Object.assign(state.units.find(unit=>unit.id===where.id),data)}},$transaction:async(fn)=>fn(client)};return client;}
test('only Admin can backfill; Rosa Request ID is required and never synthesized',async()=>{const client=db();for(const role of ['SALES','SALES_MANAGER','READ_ONLY'])await assert.rejects(backfillExistingRosaDemo(client,{...actor,role},form()),/Administrator/);await assert.rejects(backfillExistingRosaDemo(client,actor,form({requestId:''})),/Rosa Request ID/);assert.equal(client.state.requests.length,0);});
test('existing source Request ID directs reconciliation to same Demo',async()=>{await assert.rejects(backfillExistingRosaDemo(db(42),actor,form()),error=>error instanceof ExistingDemoError&&error.id===42);});
test('Admin backfill preserves source, provenance, units and report calculations with optional Demo Number',async()=>{const client=db();const saved=await backfillExistingRosaDemo(client,actor,form());assert.equal(saved.sourceRequestId,requestId);assert.equal(saved.demoNumber,null);assert.equal(saved.sourceMethod,'MANUAL_ROSA_BACKFILL');assert.equal(saved.accountId,1);assert.equal(client.state.revisions[0].recordedById,actor.id);assert.equal(client.state.revisions[0].sourceFileName,'Manual Rosa backfill');assert.equal(client.state.revisions[0].sourceRows.header.reason,'Missed import');assert.equal(client.state.items[0].sourceLineKey,'SKU-1:1');assert.equal(saved.sourceHeader.VAR,'Acme');assert.equal(client.state.units.length,2);const summary=demoSummary({...saved,expectedReturnOverrideAt:null,items:[{quantity:2,retiredAt:null,units:client.state.units}]},new Date('2026-09-20'));assert.equal(summary.outstanding,2);assert.equal(summary.overdue,true);assert.equal(summary.recoveryAttention,true);});
test('duplicate Demo Number and invalid lifecycle or serial count are rejected',async()=>{const client=db();client.demoRequest.findFirst=async()=>({id:8});await assert.rejects(backfillExistingRosaDemo(client,actor,form({demoNumber:'D-1'})),/Demo Number/);await assert.rejects(backfillExistingRosaDemo(db(),actor,form({shippedAt:''})),/shipment date/);await assert.rejects(backfillExistingRosaDemo(db(),actor,form({serials0:'A;B;C'})),/Serials/);});
test('creation entry points are absent from Account, Project, and Opportunity',()=>{for(const file of ['app/accounts/[id]/page.tsx','app/projects/[id]/page.tsx','app/opportunities/[id]/page.tsx']){const source=fs.readFileSync(path.join(root,file),'utf8');assert.doesNotMatch(source,/\/demos\/new|>Add Demo<|>Create Demo</);if(file.includes('accounts/'))assert.match(source,/No Demo Requests have been imported for this Account\./);else assert.match(source,/Choose an existing Demo/);}assert.equal(fs.existsSync(path.join(root,'app/demos/new/page.tsx')),false);assert.doesNotMatch(fs.readFileSync(path.join(root,'app/demos/actions.ts'),'utf8'),/export async function createDemoRequest/);});
