import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import Module from 'node:module';import path from 'node:path';import ts from 'typescript';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);const require=Module.createRequire(fileURLToPath(import.meta.url));
const {classifyPriceException,duplicatePeCodes,previewPriceExceptionCleanup,applyPriceExceptionCleanup,validateCleanupRequest}=require(path.join(root,'lib/price-exception-cleanup.ts'));
const admin={id:91,role:'ADMIN',active:true},today=new Date('2026-09-25T00:00:00Z');
const row=(values={})=>({id:1,peCode:'PE-1',sourceType:'LEGACY_WORKBOOK',status:'ACTIVE',archivedAt:null,assignedSalesRepUserId:null,effectiveDate:null,expirationDate:new Date('2026-09-24T00:00:00Z'),distributorAccountId:null,varAccountId:null,endUserAccountId:null,distributorSourceName:'Customer',varSourceName:null,endUserSourceName:null,distributorAccount:null,varAccount:null,endUserAccount:null,lines:[{productSkuId:null,sourceSku:'SKU'}],...values});
test('audit groups owner, account, SKU, date, archive, and duplicate issues independently',()=>{const issues=classifyPriceException(row(),new Set(['pe-1']),today);for(const issue of ['missingOwner','missingAccount','expired','activePastExpiration','missingSku','legacyUnassigned','possibleDuplicate','inconsistentStatus'])assert.ok(issues.includes(issue),issue);assert.deepEqual([...duplicatePeCodes([{peCode:' PE-1 '},{peCode:'pe-1'},{peCode:'PE-2'}])],['pe-1']);assert.ok(classifyPriceException(row({distributorAccountId:7,distributorAccount:{status:'INACTIVE',archivedAt:null},lines:[{productSkuId:4,sourceSku:'SKU'}],assignedSalesRepUserId:2,status:'EXPIRED'}),new Set(),today).includes('inactiveAccount'));assert.ok(classifyPriceException(row({distributorAccountId:7,distributorAccount:{status:'ACTIVE',archivedAt:new Date()}}),new Set(),today).includes('inactiveAccount'));assert.ok(classifyPriceException(row({status:'ARCHIVED',archivedAt:new Date()}),new Set(),today).includes('archived'));assert.ok(classifyPriceException(row({status:'EXPIRED',expirationDate:new Date('2026-10-01T00:00:00Z')}),new Set(),today).includes('inconsistentStatus'))});
test('bulk request requires admin and valid selection',()=>{for(const role of ['SALES','SALES_MANAGER','MARKETING_MANAGER','READ_ONLY'])assert.throws(()=>validateCleanupRequest({...admin,role},{ids:[1],action:'expire'}),/Access denied|Administrator/);assert.throws(()=>validateCleanupRequest(admin,{ids:[],action:'expire'}),/Select/);assert.deepEqual(validateCleanupRequest(admin,{ids:[2,1,2],action:'expire'}).ids,[1,2])});
function fakeDb(initial){const records=initial.map(record=>({...record}));const tx={user:{findUnique:async()=>({firstName:'Sales',lastName:'Rep',role:'SALES',active:true,archivedAt:null})},account:{findUnique:async()=>({name:'Acme',status:'ACTIVE',archivedAt:null})},priceException:{findMany:async({where})=>records.filter(record=>where.id.in.includes(record.id)).sort((a,b)=>a.id-b.id).map(record=>({...record})),updateMany:async({where,data})=>{const record=records.find(item=>item.id===where.id&&item.updatedAt.getTime()===where.updatedAt.getTime());if(!record)return {count:0};Object.assign(record,data,{updatedAt:new Date(record.updatedAt.getTime()+1)});return {count:1}}}};return {...tx,records,$transaction:async callback=>callback(tx)}}
const selectedRecord=(id=1)=>({id,peCode:`PE-${id}`,status:'ACTIVE',archivedAt:null,expirationDate:new Date('2026-09-24T00:00:00Z'),assignedSalesRepUserId:null,distributorAccountId:null,varAccountId:null,endUserAccountId:null,updatedAt:new Date('2026-09-20T00:00:00Z'),lines:[{id:19,approvedUnitPrice:'12.00',sourceMetadata:{original:'yes'}}],opportunitySnapshots:[{priceExceptionUnitPrice:'12.00'}]});
test('preview gives exact selected count, before/after, and confirmation is mandatory',async()=>{const db=fakeDb([selectedRecord(1),selectedRecord(2)]),request={ids:[1],action:'assignOwner',targetId:8};const plan=await previewPriceExceptionCleanup(db,admin,request);assert.equal(plan.changes.length,1);assert.deepEqual(plan.changes[0],{id:1,code:'PE-1',before:'Unassigned',after:'Sales Rep'});await assert.rejects(applyPriceExceptionCleanup(db,admin,request,'',1,false),/Preview and explicit confirmation required/);await assert.rejects(applyPriceExceptionCleanup(db,admin,request,plan.fingerprint,1,false),/Preview and explicit confirmation required/);await assert.rejects(applyPriceExceptionCleanup(db,admin,request,plan.fingerprint,2,true),/Selection or records changed/);assert.equal(db.records[0].assignedSalesRepUserId,null);assert.equal(await applyPriceExceptionCleanup(db,admin,request,plan.fingerprint,1,true),1);assert.equal(db.records[0].assignedSalesRepUserId,8);assert.equal(db.records[1].assignedSalesRepUserId,null);assert.deepEqual(db.records[0].lines,selectedRecord().lines);assert.deepEqual(db.records[0].opportunitySnapshots,selectedRecord().opportunitySnapshots)});
test('stale preview and ineligible selection cannot apply',async()=>{const db=fakeDb([selectedRecord()]),request={ids:[1],action:'linkDistributor',targetId:7};const plan=await previewPriceExceptionCleanup(db,admin,request);db.records[0].updatedAt=new Date('2026-09-21T00:00:00Z');await assert.rejects(applyPriceExceptionCleanup(db,admin,request,plan.fingerprint,1,true),/Selection or records changed/);db.records[0].distributorAccountId=5;await assert.rejects(previewPriceExceptionCleanup(db,admin,request),/not eligible/)});
test('Account tabs retain their order and remove Orders and Inventory',()=>{const account=fs.readFileSync(path.join(root,'app/accounts/[id]/page.tsx'),'utf8');assert.match(account,/const tabs = \["Overview", "Contacts", "Opportunities", "Projects", "Activity", "Tasks", "Notes", "Documents"\]/);assert.doesNotMatch(account,/tab === "Orders"|tab === "Inventory"/)});
