import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import Module from 'node:module';import path from 'node:path';import ts from 'typescript';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);const require=Module.createRequire(fileURLToPath(import.meta.url));
const {parseLegacyPriceExceptionWorkbook,planPriceExceptionImport,parseLegacyDate,normalizeAccountName}=require(path.join(root,'lib/price-exception-import.ts'));const {priceExceptionWhere,accountPriceExceptionRoles}=require(path.join(root,'lib/price-exceptions.ts'));const {can,routeAccess}=require(path.join(root,'lib/authorization.ts'));
const workbook=fs.readFileSync(path.join(root,'../reference-data/Distributor Price Exceptions 02052020 - Copy.xlsx'));
const row=(overrides={})=>({sheet:'Active Disty PEs',rowNumber:2,status:'ACTIVE',distributor:'Blue Star',varName:'Reseller',rep:'Rep',endUser:'Customer',code:'PE-1',oldCode:null,expirationDate:'2026-12-31',sku:'SRP-S300LOSK',price:'200',quantity:'100',comments:null,competitor:null,rawValues:[],...overrides});
const parsed=(rows,skippedRows=0)=>({rows,skippedRows,errors:[]});
const db=({accounts=[],skus=[],existing=[]}={})=>({account:{findMany:async()=>accounts},productSku:{findMany:async()=>skus},priceException:{findMany:async()=>existing}});

test('real legacy adapter reads Active and Expired layouts, including shifted historical rows',async()=>{const result=await parseLegacyPriceExceptionWorkbook(workbook);assert.deepEqual(result.errors,[]);assert.ok(result.rows.some(r=>r.status==='ACTIVE'));assert.ok(result.rows.some(r=>r.status==='EXPIRED'));const shifted=result.rows.find(r=>r.code==='SPR04242024');assert.equal(shifted.sku,'XL5-40CTWG');assert.equal(Number(shifted.price),423);assert.equal(Number(shifted.quantity),250);assert.ok(result.skippedRows>0)});
test('normal PE rows group while quantity breaks and duplicate SKU lines are preserved',async()=>{const plan=await planPriceExceptionImport(db({skus:[{id:9,normalizedPartNumber:'SRP-S300LOSK'}]}),parsed([row(),row({rowNumber:3,quantity:'1000',price:'180'})]),'legacy.xlsx');assert.equal(plan.counts.headers,1);assert.equal(plan.counts.lines,2);assert.equal(plan.items[0].lines[0].productSkuId,9);assert.deepEqual(plan.items[0].lines.map(x=>x.sourceQuantityRaw),['100','1000']);assert.deepEqual(plan.items[0].lines.map(x=>x.price),['200.00','180.00']);assert.equal(new Set(plan.items[0].lines.map(x=>x.sourceLineKey)).size,2)});
test('SK$Override and blank codes use row-level identity instead of unsafe aggregation',async()=>{const rows=[row({code:'SK$Override',sku:'A',price:'1'}),row({rowNumber:3,code:'SK$Override',sku:'B',price:'2'}),row({rowNumber:4,code:null,sku:'C',price:'3'})];const plan=await planPriceExceptionImport(db(),parsed(rows),'legacy.xlsx');assert.equal(plan.counts.headers,3);assert.equal(new Set(plan.items.map(x=>x.sourceKey)).size,3)});
test('account matching is role-specific, exact-normalized, unresolved-safe, and ambiguity-safe',async()=>{const accounts=[{id:1,name:'Blue & Star'},{id:2,name:'Reseller'},{id:3,name:'reseller'}];const plan=await planPriceExceptionImport(db({accounts}),parsed([row({distributor:' blue and star ',varName:'Reseller',endUser:'Missing'})]),'legacy.xlsx');const item=plan.items[0];assert.equal(normalizeAccountName('Blue & Star'),'blue and star');assert.equal(item.distributorAccountId,1);assert.equal(item.varAccountId,undefined);assert.equal(item.endUserAccountId,undefined);assert.equal(plan.counts.resolvedAccounts,1);assert.equal(plan.counts.unresolvedAccounts,2)});
test('unresolved SKU imports, USD default is explicit, dates parse, and re-preview identifies update',async()=>{const first=await planPriceExceptionImport(db(),parsed([row({expirationDate:'6302023',sku:'UNKNOWN'})]),'legacy.xlsx');assert.equal(first.items[0].lines[0].unresolvedSku,true);assert.equal(first.items[0].lines[0].currency,'USD');assert.equal(first.items[0].lines[0].currencyDefaulted,true);assert.equal(first.items[0].expirationDate,'2023-06-30');assert.equal(parseLegacyDate('45291'),'2023-12-31');assert.equal(parseLegacyDate('12/31/0226'),null);assert.equal(parseLegacyDate('+020206-12-01T00:00:00.000Z'),null);const second=await planPriceExceptionImport(db({existing:[{id:44,sourceKey:first.items[0].sourceKey,archivedAt:new Date()}]}),parsed([row({expirationDate:'6302023',sku:'UNKNOWN',price:'190'})]),'legacy.xlsx');assert.equal(second.items[0].change,'UPDATE');assert.equal(second.items[0].existingId,44);assert.equal(second.items[0].archived,true);assert.equal(second.counts.newPriceExceptions,0);assert.equal(second.counts.existingToUpdate,1)});
test('malformed legacy values remain auditable without blocking valid finalized records',async()=>{const plan=await planPriceExceptionImport(db(),parsed([row({price:'not money',quantity:'unknown',expirationDate:'not a date'})],2),'legacy.xlsx');assert.equal(plan.counts.errors,0);assert.equal(plan.counts.skippedRows,2);assert.ok(plan.digest);assert.equal(plan.errors.length,0);assert.equal(plan.items[0].lines[0].price,null);assert.equal(plan.items[0].lines[0].sourceQuantity,null);assert.match(plan.items[0].messages.join(' '),/preserved as raw source text/)});
test('schema permits unresolved parties/SKUs, duplicate display codes, and multiple lines',()=>{const schema=fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8');assert.match(schema,/peCode\s+String\?/);assert.match(schema,/distributorAccountId\s+Int\?/);assert.match(schema,/productSkuId\s+Int\?/);assert.match(schema,/@@unique\(\[sourceType, sourceKey\]\)/);assert.match(schema,/@@unique\(\[priceExceptionId, sourceLineKey\]\)/);assert.doesNotMatch(schema,/@@unique\(\[priceExceptionId, productSkuId\]\)/)});
test('list filters, account role de-duplication, and authorization follow CRM conventions',()=>{assert.deepEqual(accountPriceExceptionRoles({distributorAccountId:7,varAccountId:7,endUserAccountId:null},7),['Distributor/OEM','VAR/ISV']);const where=priceExceptionWhere({q:'PE-1',status:'ACTIVE',unresolved:'yes'});assert.ok(where.AND.length>=3);for(const role of ['ADMIN','SALES_MANAGER','SALES','MARKETING_MANAGER','READ_ONLY'])assert.equal(can({id:1,role,active:true},'pricing.read'),true);assert.equal(routeAccess('/price-exceptions',{id:1,role:'READ_ONLY',active:true}),'allowed');assert.equal(routeAccess('/administration/imports/price-exceptions',{id:1,role:'SALES_MANAGER',active:true}),'denied')});
