import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import Module from 'node:module';import path from 'node:path';import ts from 'typescript';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,filename);const require=Module.createRequire(fileURLToPath(import.meta.url));
const {parseLegacyPriceExceptionWorkbook,planPriceExceptionImport,parseLegacyDate,normalizeAccountName}=require(path.join(root,'lib/price-exception-import.ts'));const {priceExceptionWhere,accountPriceExceptionRoles,accountPriceExceptionWhere}=require(path.join(root,'lib/price-exceptions.ts'));const {parsePriceExceptionAccountPatch,PriceExceptionAccountValidationError,updatePriceExceptionAccountLinks}=require(path.join(root,'lib/price-exception-resolution.ts'));const {can,routeAccess}=require(path.join(root,'lib/authorization.ts'));
const workbook=fs.readFileSync(path.join(root,'../reference-data/Distributor Price Exceptions 02052020 - Copy.xlsx'));
const row=(overrides={})=>({sheet:'Active Disty PEs',rowNumber:2,status:'ACTIVE',distributor:'Blue Star',varName:'Reseller',rep:'Rep',endUser:'Customer',code:'PE-1',oldCode:null,expirationDate:'2026-12-31',sku:'SRP-S300LOSK',price:'200',quantity:'100',comments:null,competitor:null,rawValues:[],...overrides});
const parsed=(rows,skippedRows=0)=>({rows,skippedRows,errors:[]});
const db=({accounts=[],skus=[],existing=[]}={})=>({account:{findMany:async()=>accounts},productSku:{findMany:async()=>skus},priceException:{findMany:async()=>existing}});

test('real legacy adapter reads Active and Expired layouts, including shifted historical rows',async()=>{const result=await parseLegacyPriceExceptionWorkbook(workbook);assert.deepEqual(result.errors,[]);assert.ok(result.rows.some(r=>r.status==='ACTIVE'));assert.ok(result.rows.some(r=>r.status==='EXPIRED'));const shifted=result.rows.find(r=>r.code==='SPR04242024');assert.equal(shifted.sku,'XL5-40CTWG');assert.equal(Number(shifted.price),423);assert.equal(Number(shifted.quantity),250);assert.ok(result.skippedRows>0)});
test('normal PE rows group while quantity breaks and duplicate SKU lines are preserved',async()=>{const plan=await planPriceExceptionImport(db({skus:[{id:9,normalizedPartNumber:'SRP-S300LOSK'}]}),parsed([row(),row({rowNumber:3,quantity:'1000',price:'180'})]),'legacy.xlsx');assert.equal(plan.counts.headers,1);assert.equal(plan.counts.lines,2);assert.equal(plan.items[0].lines[0].productSkuId,9);assert.deepEqual(plan.items[0].lines.map(x=>x.sourceQuantityRaw),['100','1000']);assert.deepEqual(plan.items[0].lines.map(x=>x.price),['200.00','180.00']);assert.equal(new Set(plan.items[0].lines.map(x=>x.sourceLineKey)).size,2)});
test('SK$Override and blank codes use row-level identity instead of unsafe aggregation',async()=>{const rows=[row({code:'SK$Override',sku:'A',price:'1'}),row({rowNumber:3,code:'SK$Override',sku:'B',price:'2'}),row({rowNumber:4,code:null,sku:'C',price:'3'})];const plan=await planPriceExceptionImport(db(),parsed(rows),'legacy.xlsx');assert.equal(plan.counts.headers,3);assert.equal(new Set(plan.items.map(x=>x.sourceKey)).size,3)});
test('account matching is role-specific, exact-normalized, unresolved-safe, and ambiguity-safe',async()=>{const accounts=[{id:1,name:'Blue & Star'},{id:2,name:'Reseller'},{id:3,name:'reseller'}];const plan=await planPriceExceptionImport(db({accounts}),parsed([row({distributor:' blue and star ',varName:'Reseller',endUser:'Missing'})]),'legacy.xlsx');const item=plan.items[0];assert.equal(normalizeAccountName('Blue & Star'),'blue and star');assert.equal(item.distributorAccountId,1);assert.equal(item.varAccountId,undefined);assert.equal(item.endUserAccountId,undefined);assert.equal(plan.counts.resolvedAccounts,1);assert.equal(plan.counts.unresolvedAccounts,2)});
test('unresolved SKU imports, USD default is explicit, dates parse, and re-preview identifies update',async()=>{const first=await planPriceExceptionImport(db(),parsed([row({expirationDate:'6302023',sku:'UNKNOWN'})]),'legacy.xlsx');assert.equal(first.items[0].lines[0].unresolvedSku,true);assert.equal(first.items[0].lines[0].currency,'USD');assert.equal(first.items[0].lines[0].currencyDefaulted,true);assert.equal(first.items[0].expirationDate,'2023-06-30');assert.equal(parseLegacyDate('45291'),'2023-12-31');assert.equal(parseLegacyDate('12/31/0226'),null);assert.equal(parseLegacyDate('+020206-12-01T00:00:00.000Z'),null);const second=await planPriceExceptionImport(db({existing:[{id:44,sourceKey:first.items[0].sourceKey,archivedAt:new Date()}]}),parsed([row({expirationDate:'6302023',sku:'UNKNOWN',price:'190'})]),'legacy.xlsx');assert.equal(second.items[0].change,'UPDATE');assert.equal(second.items[0].existingId,44);assert.equal(second.items[0].archived,true);assert.equal(second.counts.newPriceExceptions,0);assert.equal(second.counts.existingToUpdate,1)});
test('malformed legacy values remain auditable without blocking valid finalized records',async()=>{const plan=await planPriceExceptionImport(db(),parsed([row({price:'not money',quantity:'unknown',expirationDate:'not a date'})],2),'legacy.xlsx');assert.equal(plan.counts.errors,0);assert.equal(plan.counts.skippedRows,2);assert.ok(plan.digest);assert.equal(plan.errors.length,0);assert.equal(plan.items[0].lines[0].price,null);assert.equal(plan.items[0].lines[0].sourceQuantity,null);assert.match(plan.items[0].messages.join(' '),/preserved as raw source text/)});
test('schema permits unresolved parties/SKUs, duplicate display codes, and multiple lines',()=>{const schema=fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8');assert.match(schema,/peCode\s+String\?/);assert.match(schema,/distributorAccountId\s+Int\?/);assert.match(schema,/productSkuId\s+Int\?/);assert.match(schema,/@@unique\(\[sourceType, sourceKey\]\)/);assert.match(schema,/@@unique\(\[priceExceptionId, sourceLineKey\]\)/);assert.doesNotMatch(schema,/@@unique\(\[priceExceptionId, productSkuId\]\)/)});
test('list filters, account role de-duplication, and authorization follow CRM conventions',()=>{assert.deepEqual(accountPriceExceptionRoles({distributorAccountId:7,varAccountId:7,endUserAccountId:null},7),['Distributor/OEM','VAR/ISV']);const where=priceExceptionWhere({q:'PE-1',status:'ACTIVE',unresolved:'yes'});assert.ok(where.AND.length>=3);for(const role of ['ADMIN','SALES_MANAGER','SALES','MARKETING_MANAGER','READ_ONLY'])assert.equal(can({id:1,role,active:true},'pricing.read'),true);assert.equal(routeAccess('/price-exceptions',{id:1,role:'READ_ONLY',active:true}),'allowed');assert.equal(routeAccess('/administration/imports/price-exceptions',{id:1,role:'SALES_MANAGER',active:true}),'denied')});

const actor=(role='ADMIN')=>({id:91,role,active:true});
function resolutionDb({accounts=[{id:1},{id:2},{id:3}],priceException={id:44,distributorAccountId:null,varAccountId:null,endUserAccountId:null,distributorSourceName:'Bstar',varSourceName:'Levata source',endUserSourceName:'IPOURIT'}}={}){
  const record={...priceException};return {record,account:{findMany:async({where})=>accounts.filter(account=>where.id.in.includes(account.id)).map(({id})=>({id}))},priceException:{findUnique:async({where})=>where.id===record.id?{distributorAccountId:record.distributorAccountId,varAccountId:record.varAccountId,endUserAccountId:record.endUserAccountId}:null,update:async({data})=>Object.assign(record,data)}};
}
test('Admin independently resolves distributor, VAR/ISV, and End User without changing raw source names',async()=>{const client=resolutionDb();for(const [field,id] of [['distributorAccountId',1],['varAccountId',2],['endUserAccountId',3]])await updatePriceExceptionAccountLinks(client,44,actor(),{[field]:id});assert.equal(client.record.distributorSourceName,'Bstar');assert.equal(client.record.varSourceName,'Levata source');assert.equal(client.record.endUserSourceName,'IPOURIT');assert.deepEqual([client.record.distributorAccountId,client.record.varAccountId,client.record.endUserAccountId],[1,2,3])});
test('clearing a mapping removes that Account context while partial updates preserve other roles',async()=>{const client=resolutionDb({priceException:{id:44,distributorAccountId:1,varAccountId:2,endUserAccountId:3,distributorSourceName:'Bstar'}});assert.deepEqual(accountPriceExceptionRoles(client.record,2),['VAR/ISV']);await updatePriceExceptionAccountLinks(client,44,actor(),{varAccountId:null});assert.deepEqual([client.record.distributorAccountId,client.record.varAccountId,client.record.endUserAccountId],[1,null,3]);assert.deepEqual(accountPriceExceptionRoles(client.record,2),[]);assert.equal(client.record.distributorSourceName,'Bstar')});
test('non-Admin resolution is denied and invalid or missing Account IDs are rejected',async()=>{for(const role of ['SALES_MANAGER','SALES','MARKETING_MANAGER','READ_ONLY'])await assert.rejects(updatePriceExceptionAccountLinks(resolutionDb(),44,actor(role),{distributorAccountId:1}),/Access denied/);await assert.rejects(updatePriceExceptionAccountLinks(resolutionDb(),44,actor(),{endUserAccountId:999}),error=>error instanceof PriceExceptionAccountValidationError&&error.errors.endUserAccountId==='The selected Account no longer exists.');const form=new FormData();form.set('distributorAccountId','not-an-id');assert.equal(parsePriceExceptionAccountPatch(form).errors.distributorAccountId,'Choose a valid existing Account.')});
test('archived or inactive current Accounts remain valid historical links',async()=>{const client=resolutionDb({accounts:[{id:8,status:'ARCHIVED',archivedAt:new Date()}]});await updatePriceExceptionAccountLinks(client,44,actor(),{distributorAccountId:8});assert.equal(client.record.distributorAccountId,8)});
test('Account PE context uses one OR query row and combines roles without duplicate PE rows',()=>{assert.deepEqual(accountPriceExceptionWhere(7),{OR:[{distributorAccountId:7},{varAccountId:7},{endUserAccountId:7}]});assert.deepEqual(accountPriceExceptionRoles({distributorAccountId:7,varAccountId:7,endUserAccountId:7},7),['Distributor/OEM','VAR/ISV','End User'])});
test('re-import preserves existing manual links and still fills null links from exact automatic matches',async()=>{const source=parsed([row({distributor:'Bstar',varName:'Exact VAR',endUser:'Exact End'})]);const first=await planPriceExceptionImport(db(),source,'legacy.xlsx');const existing={id:44,sourceKey:first.items[0].sourceKey,archivedAt:null,distributorAccountId:71,varAccountId:null,endUserAccountId:73};const repeated=await planPriceExceptionImport(db({accounts:[{id:10,name:'Exact VAR'},{id:11,name:'Exact End'},{id:12,name:'Bstar'}],existing:[existing]}),source,'legacy.xlsx');assert.equal(repeated.items[0].distributorAccountId,71);assert.equal(repeated.items[0].varAccountId,10);assert.equal(repeated.items[0].endUserAccountId,73)});
test('detail UI keeps source and linked Account distinct and exposes resolution only through Admin authorization',()=>{const detail=fs.readFileSync(path.join(root,'app/price-exceptions/[id]/page.tsx'),'utf8');const search=fs.readFileSync(path.join(root,'app/price-exceptions/account-search/route.ts'),'utf8');assert.match(detail,/Source:/);assert.match(detail,/Linked Account:/);assert.match(detail,/can\(actor,'users\.manage'\)/);assert.match(search,/requirePermission\('users\.manage'\)/);assert.match(search,/status:'ACTIVE',archivedAt:null/)});
