import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module from 'node:module';
import path from 'node:path';
import ts from 'typescript';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,filename);
const require=Module.createRequire(fileURLToPath(import.meta.url));
const {parseImportXlsx}=require(path.join(root,'lib/import-xlsx.ts'));
const {parseImportCsv}=require(path.join(root,'lib/import-csv.ts'));
const {planProductImport,productImportHeaders}=require(path.join(root,'lib/product-import.ts'));
const {mapProductWorkbookSheet}=require(path.join(root,'lib/product-workbook.ts'));
const workbookPath=path.resolve(root,'../reference-data/BIXOLON_Price_List.xlsx');
const emptyDb={product:{findMany:async()=>[]}};

test('real workbook maps STANDARD, MSRP, and channel tiers separately', {skip:!fs.existsSync(workbookPath)}, async()=>{
  const file=fs.readFileSync(workbookPath);
  const adapter=(sheet,rows)=>mapProductWorkbookSheet(sheet,rows,'USD');
  const first=await parseImportXlsx(file);
  assert.ok(first.sheets.includes('POS printers'));
  assert.ok(first.sheets.includes('TT ribbon  (2)'));
  const pos=await parseImportXlsx(file,'POS printers',adapter);
  assert.equal(pos.error,undefined);
  const rows=parseImportCsv(pos.csv,productImportHeaders).rows;
  assert.equal(rows.length,132);
  assert.deepEqual(rows[0].values,{model:'SRP-275IIIAOSG',part_number:'SRP-275IIIAOSG',description:rows[0].values.description,standard_price:'144.10',msrp_price:'299.20',reseller_price:'',distributor_price:'',currency:'USD',price_unit:'EACH',active:''});
  assert.match((await parseImportXlsx(file,'TT ribbon ',adapter)).error,/older TT ribbon/);
  const ribbon=await parseImportXlsx(file,'TT ribbon  (2)',adapter);
  const ribbonRows=parseImportCsv(ribbon.csv,productImportHeaders).rows;
  assert.equal(ribbonRows.length,96);
  assert.equal(ribbonRows[0].values.model,'BR-WX11');
  assert.equal(ribbonRows[0].values.part_number,'BR-WX110-11-300');
  assert.equal(ribbonRows[0].values.standard_price,'');
  assert.equal(ribbonRows[0].values.msrp_price,'159.91');
  assert.equal(ribbonRows[0].values.distributor_price,'79.95');
  assert.equal(ribbonRows[0].values.price_unit,'CASE');
  const label=await parseImportXlsx(file,'Label printers',adapter);
  const labelRow=parseImportCsv(label.csv,productImportHeaders).rows[0].values;
  assert.equal(labelRow.standard_price,'');
  assert.equal(labelRow.msrp_price,'646.80');
  assert.equal(labelRow.reseller_price,'317.00');
  assert.equal(labelRow.distributor_price,'266.00');
  const paper=await parseImportXlsx(file,'Linerless paper',adapter);
  const paperRows=parseImportCsv(paper.csv,productImportHeaders).rows;
  assert.equal(paperRows.length,7);
  assert.equal(paperRows[0].values.price_unit,'BOX');
  assert.equal(paperRows[6].values.price_unit,'ROLL');
});
test('Mobile printers keeps only the later Bluetooth 4.1 + BLE SKU row', {skip:!fs.existsSync(workbookPath)}, async()=>{
  const file=fs.readFileSync(workbookPath);
  const mobile=await parseImportXlsx(file,'Mobile printers',(sheet,rows)=>mapProductWorkbookSheet(sheet,rows,'USD'));
  const parsed=parseImportCsv(mobile.csv,productImportHeaders);
  const matches=parsed.rows.filter(row=>row.values.part_number==='SPP-R200IIIiK');
  assert.equal(matches.length,1);
  assert.equal(matches[0].line,7);
  assert.match(matches[0].values.description,/Bluetooth V4\.1.*BLE/);
  assert.equal(matches[0].values.standard_price,'218.90');
  assert.equal(matches[0].values.msrp_price,'368.50');
  assert.doesNotMatch(matches[0].values.description,/Bluetooth V3\.0/);
  assert.ok(!parsed.rows.some(row=>row.values.part_number==='SPP-R200IIIplusiK'));
  const plan=await planProductImport(emptyDb,mobile.csv);
  assert.equal(plan.counts.errors,0);
  assert.equal(plan.counts.newSkus,21);
});
test('obsolete Mobile SKU cannot be silently selected if its replacement is missing',()=>{
  const rows=[[],['MODEL NAME','DESCRIPTION','','MSRP','STANDARD'],[],['SPP-R200IIIiK','Bluetooth V3.0 +EDR','','368.5','218.9']];
  assert.match(mapProductWorkbookSheet('Mobile printers',rows,'USD').error,/expected later Bluetooth 4\.1/);
});
test('workbook mapping requires explicit currency and rejects history tab',()=>{
  assert.match(mapProductWorkbookSheet('POS printers',[],'').error,/currency/);
  assert.match(mapProductWorkbookSheet('Cover',[],'USD').error,/change history/);
  assert.deepEqual(mapProductWorkbookSheet('Catalog',[['model','part_number'],['X','Y']],'').rows,[['model','part_number'],['X','Y']]);
});
