import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import Module from 'node:module';
import path from 'node:path';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
Module._extensions['.ts']=(mod,file)=>mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file);
const require=Module.createRequire(fileURLToPath(import.meta.url));
const XLSX=require('xlsx');
const { supportReportWhere,supportReportOrder,supportToday,supportCaseAge,supportReport }=require(path.join(root,'lib/support-report.ts'));
const { supportDashboard }=require(path.join(root,'lib/support-dashboard.ts'));
const { syncSupportNotifications,notifySupportEvent,evaluateSupportNotifications }=require(path.join(root,'lib/support-notifications.ts'));
const { supportReportWorkbook }=require(path.join(root,'lib/support-report-workbook.ts'));
const { notificationCategories }=require(path.join(root,'lib/notifications.ts'));
const { canUseDashboardWidget,systemDashboardDefaults }=require(path.join(root,'lib/dashboard.ts'));
const { routeAccess }=require(path.join(root,'lib/authorization.ts'));
const actor=(role,id=7)=>({id,role,active:true,archivedAt:null});
const now=new Date('2026-10-08T16:00:00Z');

test('Support report filters retain case permissions, search, dates, and DB sort',()=>{
  const where=supportReportWhere(actor('SUPPORT'),{rep:'7',status:'OPEN',priority:'HIGH',account:'Acme',contact:'Jane',category:'3',product:'XD5',purchasedFrom:'CDW',openedFrom:'2026-10-01',openedTo:'2026-10-08',resolvedFrom:'2026-09-01',followUp:'overdue',q:'CDW-G'},now);
  assert.ok(where.AND.some(part=>part.archivedAt===null));
  for(const field of ['assignedToId','status','priority','categoryId','openedAt','resolvedAt','nextFollowUpAt','purchaseSourceText']) assert.match(JSON.stringify(where),new RegExp(field));
  assert.equal(supportReportOrder('oldest')[0].openedAt,'asc');
  assert.equal(supportReportOrder('number')[0].caseNumber,'asc');
  assert.equal(routeAccess('/reports/support-cases',actor('SUPPORT')),'allowed');
  assert.equal(routeAccess('/reports/support-cases',actor('SALES')),'allowed');
  assert.equal(routeAccess('/reports/support-cases',actor('MARKETING_MANAGER')),'allowed');
  assert.equal(routeAccess('/reports/support-cases',actor('SUPPORT',7)),'allowed');
});
test('Support Dashboard defaults and bounded aggregate queries',async()=>{
  assert.deepEqual(systemDashboardDefaults.SUPPORT.items.map(x=>x.key),['SUPPORT_MY_OPEN','SUPPORT_PRIORITY','SUPPORT_OVERDUE','SUPPORT_OLDEST']);
  assert.equal(systemDashboardDefaults.SALES.items.some(x=>x.key.startsWith('SUPPORT_')),false);
  assert.equal(canUseDashboardWidget(actor('ADMIN'),'SUPPORT_OLDEST'),true);
  assert.equal(canUseDashboardWidget(actor('MARKETING_MANAGER'),'SUPPORT_OLDEST'),false);
  const calls=[];
  const db={supportCase:{groupBy:async args=>(calls.push(args),args.by[0]==='status'?[{status:'OPEN',_count:{_all:2}}]:[{priority:'HIGH',_count:{_all:1}}]),count:async args=>(calls.push(args),3),findMany:async args=>(calls.push(args),[])}};
  const result=await supportDashboard(db,actor('SUPPORT'),now);
  assert.equal(result.mine.total,2);assert.equal(result.high,1);assert.equal(result.overdueCount,3);
  assert.equal(calls.filter(x=>x.take).length,3);assert.ok(calls.filter(x=>x.take).every(x=>x.take===5));
  assert.ok(calls.some(x=>x.where.assignedToId===7));
});
test('one-touch Resolved and Closed cases stay out of active dashboard and overdue queries',async()=>{
  const calls=[];
  const db={supportCase:{groupBy:async args=>(calls.push(args),[]),count:async args=>(calls.push(args),0),findMany:async args=>(calls.push(args),[])}};
  const result=await supportDashboard(db,actor('SUPPORT'),now);
  assert.equal(result.mine.total,0);
  assert.equal(result.overdueCount,0);
  for(const query of calls){
    const statuses=query.where.status.in;
    assert.ok(statuses.includes('NEW')&&statuses.includes('OPEN'));
    assert.ok(!statuses.includes('RESOLVED')&&!statuses.includes('CLOSED'));
  }
});
test('overdue notification dedupes and resolves on date, assignee, and closure',async()=>{
  const notifications=[];
  const row={id:11,caseNumber:'BXS-2026-000011',assignedToId:7,status:'OPEN',archivedAt:null,nextFollowUpAt:new Date('2026-10-07T12:00:00Z')};
  const db={supportCase:{findUnique:async()=>row},user:{findFirst:async({where})=>where.id===7?{id:7}:null},notification:{findMany:async()=>notifications.filter(x=>!x.resolvedAt).map(x=>({id:x.id,sourceKey:x.sourceKey})),updateMany:async({where,data})=>{for(const x of notifications)if(where.id.in.includes(x.id))x.resolvedAt=data.resolvedAt;return {count:where.id.in.length}},createMany:async({data})=>{if(notifications.some(x=>x.sourceKey===data[0].sourceKey))return {count:0};notifications.push({...data[0],id:notifications.length+1,resolvedAt:null});return {count:1}}}};
  assert.deepEqual(await syncSupportNotifications(db,11,now),{created:1,resolved:0});
  assert.deepEqual(await syncSupportNotifications(db,11,now),{created:0,resolved:0});
  row.assignedToId=null;assert.deepEqual(await syncSupportNotifications(db,11,now),{created:0,resolved:1});
  row.assignedToId=7;row.nextFollowUpAt=supportToday(now).start;assert.deepEqual(await syncSupportNotifications(db,11,now),{created:0,resolved:0});
  row.nextFollowUpAt=new Date('2026-10-06T12:00:00Z');assert.deepEqual(await syncSupportNotifications(db,11,now),{created:1,resolved:0});
  row.status='RESOLVED';assert.deepEqual(await syncSupportNotifications(db,11,now),{created:0,resolved:1});
  await notifySupportEvent(db,11,7,40,'ASSIGNED',row.caseNumber);assert.equal(notifications.at(-1).title,'Support Case assigned to you');
  await notifySupportEvent(db,11,7,41,'CRITICAL',row.caseNumber);assert.equal(notifications.at(-1).severity,'CRITICAL');
  await notifySupportEvent(db,11,null,42,'ASSIGNED',row.caseNumber);assert.equal(notifications.length,4);
  row.status='OPEN';row.nextFollowUpAt=new Date('2026-10-05T12:00:00Z');assert.equal((await syncSupportNotifications(db,11,now)).created,1);
  row.status='CLOSED';assert.equal((await syncSupportNotifications(db,11,now)).resolved,1);
  row.status='OPEN';row.nextFollowUpAt=new Date('2026-10-04T12:00:00Z');assert.equal((await syncSupportNotifications(db,11,now)).created,1);
  row.archivedAt=now;assert.equal((await syncSupportNotifications(db,11,now)).resolved,1);
  assert.ok(notificationCategories.includes('support'));
});
test('scheduled evaluator includes Support counts without broadcasting unassigned cases',async()=>{
  const db={supportCase:{findMany:async({where})=>where.id.gt===0?[{id:1},{id:2}]:[],findUnique:async({where})=>({id:where.id,caseNumber:`BXS-2026-00000${where.id}`,assignedToId:null,status:'OPEN',archivedAt:null,nextFollowUpAt:new Date('2026-10-07T10:00:00Z')})},notification:{findMany:async()=>[]}};
  const result=await evaluateSupportNotifications(db,now);
  assert.deepEqual(result,{evaluated:2,created:0,resolved:0});
});
test('Excel keeps business identifiers, Purchased From, and typed cells',()=>{
  const row={id:11,caseNumber:'BXS-2026-000011',account:{name:'Acme'},contact:null,subject:'Printer issue',status:'OPEN',priority:'HIGH',category:null,assignedTo:null,productSku:null,serialNumber:'ABC',purchaseSourceText:'CDW-G',purchasedFromAccount:{name:'CDW'},source:'PHONE',openedAt:new Date('2026-10-01T12:00:00Z'),nextFollowUpAt:null,resolvedAt:null,closedAt:null,archivedAt:null};
  const report={now,rows:[row],summary:{open:1,highCritical:1,overdue:0,opened:1,resolved:0,averageOpenDays:7,averageResolutionDays:null},groups:{status:[{label:'OPEN',count:1}],priority:[{label:'HIGH',count:1}],category:[]}};
  const book=supportReportWorkbook(report,{q:'CDW-G'},'Support Rep');const sheet=book.Sheets['Support Cases'];
  assert.equal(sheet.A2.v,row.caseNumber);assert.equal(sheet.K2.v,'CDW-G');assert.equal(sheet.L2.v,'CDW');assert.equal(sheet.N2.t,'d');assert.equal(sheet.R2.t,'n');
  assert.equal(Object.values(sheet).some(cell=>cell?.v==='Internal ID'),false);
  assert.equal(sheet.A1.v,'Case Number');
  const empty=supportReportWorkbook({...report,rows:[]},{},'Support Rep');
  const serialized=XLSX.write(empty,{type:'buffer',bookType:'xlsx'});
  assert.match(XLSX.read(serialized,{type:'buffer'}).Sheets['Support Cases'].A2.v,/No Support Cases/);
  assert.equal(supportCaseAge(row,now),7);
});
test('report pagination and export apply the same scoped database where',async()=>{
  const calls=[];
  const row={id:11,caseNumber:'BXS-2026-000011',account:{name:'Acme'},contact:null,category:null,assignedTo:null,productSku:null,purchasedFromAccount:null,subject:'Printer',status:'OPEN',priority:'NORMAL',source:'PHONE',openedAt:new Date('2026-10-01T12:00:00Z'),resolvedAt:null,closedAt:null,nextFollowUpAt:null,archivedAt:null,purchaseSourceText:'CDW-G',serialNumber:null};
  const db={supportCase:{count:async args=>(calls.push(['count',args]),1),groupBy:async args=>(calls.push(['group',args]),[]),findFirst:async args=>(calls.push(['first',args]),null),findMany:async args=>(calls.push(['rows',args]),[row])},supportCaseCategory:{findMany:async()=>[]},productSku:{findMany:async()=>[]},user:{findMany:async()=>[]},account:{findMany:async()=>[]},$queryRaw:async()=>[{openAge:'7.2',resolutionAge:null}]};
  const filters={q:'CDW-G',priority:'NORMAL',sort:'oldest',page:'2'};
  const page=await supportReport(db,actor('SALES'),filters,{now});
  const pageQuery=calls.find(([kind,args])=>kind==='rows'&&args.include)[1];
  assert.equal(pageQuery.take,25);assert.equal(pageQuery.skip,0);assert.equal(pageQuery.orderBy[0].openedAt,'asc');
  assert.equal(page.summary.averageOpenDays,7.2);
  calls.length=0;
  const exported=await supportReport(db,actor('SALES'),filters,{all:true,now});
  const exportQuery=calls.find(([kind,args])=>kind==='rows'&&args.include)[1];
  assert.deepEqual(exportQuery.where,pageQuery.where);assert.equal(exportQuery.take,undefined);assert.equal(exported.rows[0].caseNumber,row.caseNumber);
});
test('one-touch resolution is counted in period and has a nonnegative duration for report and export',async()=>{
  const calls=[];
  const openedAt=new Date('2026-10-08T15:00:00Z');
  const row={id:12,caseNumber:'BXS-2026-000012',account:{name:'Acme'},contact:null,category:null,assignedTo:null,productSku:null,purchasedFromAccount:null,subject:'Fixed during intake',status:'RESOLVED',priority:'NORMAL',source:'PHONE',openedAt,resolvedAt:openedAt,closedAt:null,nextFollowUpAt:null,archivedAt:null,purchaseSourceText:null,serialNumber:null};
  const db={supportCase:{count:async args=>(calls.push(args),args.where?.AND?.some(x=>x.resolvedAt)?1:args.where?.AND?.some(x=>x.openedAt)?1:0),groupBy:async()=>[],findFirst:async()=>null,findMany:async()=>[row]},supportCaseCategory:{findMany:async()=>[]},productSku:{findMany:async()=>[]},user:{findMany:async()=>[]},account:{findMany:async()=>[]},$queryRaw:async()=>[{openAge:null,resolutionAge:'0'}]};
  const report=await supportReport(db,actor('SUPPORT'),{}, {all:true,now});
  assert.equal(report.summary.opened,1);
  assert.equal(report.summary.resolved,1);
  assert.equal(report.summary.averageResolutionDays,0);
  assert.equal(supportCaseAge(row,now),0);
  const sheet=supportReportWorkbook(report,{},'Support Rep').Sheets['Support Cases'];
  assert.equal(sheet.A2.v,row.caseNumber);
  assert.equal(sheet.N2.t,'d');
  assert.equal(sheet.P2.t,'d');
  assert.equal(sheet.S2.v,0);
});
