import {test} from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import fs from 'node:fs';import Module from 'node:module';import path from 'node:path';import ts from 'typescript';import {fileURLToPath} from 'node:url';import {buildFixture,fixtureDefinitions} from './fixtures/trade-show/generate.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');Module._extensions['.ts']=(mod,filename)=>mod._compile(ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText,filename);const require=Module.createRequire(import.meta.url);const parser=require(path.join(root,'lib/trade-show-import-parser.ts'));const importer=require(path.join(root,'lib/trade-show-import.ts'));const mappingManager=require(path.join(root,'lib/trade-show-import-mappings.ts'));const XLSX=require('xlsx');const {zipSync,strToU8}=require('fflate');
const refs='/opt/bixolon-crm/reference-data';const files={NRA:'leads-NRA261-2026-05-19.xls',NRF:'leads-NRF261-2026-01-14.xls',MODEX:'XPressLeadsMODX0426_2663118_C669ADFB76C9468_BIXOLON.xls'};const read=name=>fs.readFileSync(path.join(refs,files[name]));const parse=name=>parser.parseTradeShowWorkbook(read(name),files[name],42,'America/New_York');
const workbookWithColumns=(count,bookType='biff8')=>{const headers=['Captured Date','FirstName','LastName','Company',...Array.from({length:count-4},(_,i)=>`Extra ${i+1}`)];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([headers,['1/1/26 1:00 PM','A','B','C']]),'ExportExtensionsFlatFile1');return XLSX.write(book,{type:'buffer',bookType});};
const fixturePath=profile=>path.join(root,'tests/fixtures/trade-show',fixtureDefinitions[profile].filename);
const fixtureBuffer=(profile,extension)=>extension==='xlsx'?fs.readFileSync(fixturePath(profile)):buildFixture(profile,'biff8');
const parseFixture=(profile,extension)=>parser.parseTradeShowWorkbook(fixtureBuffer(profile,extension),`fixture.${extension}`,42,'America/New_York');
const sourceKeyDigest=parsed=>crypto.createHash('sha256').update(JSON.stringify(parsed.rows.map(row=>row.sourceKey))).digest('hex');
test('real NRA, NRF and MODEX .xls profiles detect with unchanged rows, raw fields and source keys',()=>{const nra=parse('NRA'),nrf=parse('NRF'),modex=parse('MODEX');assert.deepEqual([nra.format,nrf.format,modex.format],['NRA_NRF','NRA_NRF','XPRESSLEADS_MODEX']);assert.deepEqual([nra.rows.length,nrf.rows.length,modex.rows.length],[75,91,127]);assert.deepEqual([sourceKeyDigest(nra),sourceKeyDigest(nrf),sourceKeyDigest(modex)],['97fe9309577c005ae79b31c5e5133f3b4a6e59d1250506928ba4075e84c28574','3555ccc1ff78a847e4ed6e6ce9bde9ca5b3071e13a5add7ed74dd00403c9c7f6','4c7ece4214dcab03f1b5ea37581a8917905fbe2348eb382606b53a132139b9bc']);assert.ok('Badge Id' in nra.rows[0].rawSourceData);assert.ok('Lead Origin' in nra.rows[0].rawSourceData);assert.ok('Primary job function' in nrf.rows[0].rawSourceData);assert.ok('DeviceLabel' in modex.rows[0].rawSourceData);assert.equal(modex.rows.some(r=>r.phone?.endsWith('.0')||r.postalCode?.endsWith('.0')),false);assert.equal(nra.rows.filter(r=>r.warnings.some(w=>w.includes('placeholder'))).length,1);});
test('generated NRA/NRF and MODEX fixtures accept both .xls and .xlsx with identical normalized rows',()=>{for(const [profile,format] of [['nra_nrf','NRA_NRF'],['modex','XPRESSLEADS_MODEX']]){const xls=parseFixture(profile,'xls'),xlsx=parseFixture(profile,'xlsx');assert.equal(xls.format,format);assert.equal(xlsx.format,format);assert.deepEqual(xlsx.rows,xls.rows);assert.ok(xlsx.rows.every((row,index)=>row.sourceKey===xls.rows[index].sourceKey));assert.ok(xlsx.rows[0].capturedAt);assert.ok('Badge Id' in xlsx.rows[0].rawSourceData);assert.ok('Lead Origin' in xlsx.rows[0].rawSourceData);assert.ok(profile==='modex'?'DeviceLabel' in xlsx.rows[0].rawSourceData:Object.keys(xlsx.rows[0].rawSourceData).some(key=>key.startsWith('Survey:')));assert.ok(xlsx.rows[1].warnings.some(warning=>warning.includes('placeholder')));}});
test('temporary .xlsx conversions of all real workbooks preserve every parsed row and source key',()=>{for(const name of ['NRA','NRF','MODEX']){const source=read(name),xls=parse(name);const workbook=XLSX.read(source,{type:'buffer',cellDates:false,cellFormula:false,cellHTML:false,cellStyles:false,bookDeps:false,bookVBA:false,bookFiles:false});const converted=XLSX.write(workbook,{type:'buffer',bookType:'xlsx'});const xlsx=parser.parseTradeShowWorkbook(converted,`${files[name]}x`,42,'America/New_York');assert.equal(xlsx.format,xls.format);assert.equal(xlsx.sheet,xls.sheet);assert.deepEqual(xlsx.rows,xls.rows);}});
test('column limit accepts exactly 100 source columns and rejects 101 in both containers',()=>{for(const [extension,bookType] of [['xls','biff8'],['xlsx','xlsx']]){const accepted=parser.parseTradeShowWorkbook(workbookWithColumns(100,bookType),`hundred.${extension}`,1,'UTC');assert.equal(Object.keys(accepted.rows[0].rawSourceData).length,100);assert.throws(()=>parser.parseTradeShowWorkbook(workbookWithColumns(101,bookType),`hundred-one.${extension}`,1,'UTC'),/exceeds 100 source columns/);}});
test('unknown safe layouts fall through to column mapping for both .xls and .xlsx',()=>{const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['Unknown'],['x']]),'Sheet1');for(const [extension,bookType] of [['xls','biff8'],['xlsx','xlsx']])assert.throws(()=>parser.parseTradeShowWorkbook(XLSX.write(book,{type:'buffer',bookType}),`bad.${extension}`,1,'UTC'),/Column Mapping Required/);});
test('format mismatches, arbitrary ZIPs, text, HTML, corruption, encryption, macros and unsupported extensions reject',()=>{const xls=fixtureBuffer('nra_nrf','xls'),xlsx=fixtureBuffer('nra_nrf','xlsx');assert.throws(()=>parser.parseTradeShowWorkbook(xls,'renamed.xlsx',1,'UTC'),/encrypted|legacy \.xls content/i);assert.throws(()=>parser.parseTradeShowWorkbook(xlsx,'renamed.xls',1,'UTC'),/binary \.xls/);const arbitrary=Buffer.from(zipSync({'hello.txt':strToU8('hello')}));assert.throws(()=>parser.parseTradeShowWorkbook(arbitrary,'plain.xlsx',1,'UTC'),/workbook package/);for(const content of ['plain text','<html><table><tr><td>fake</td></tr></table></html>'])for(const extension of ['xls','xlsx'])assert.throws(()=>parser.parseTradeShowWorkbook(Buffer.from(content),`fake.${extension}`,1,'UTC'),/corrupt/);assert.throws(()=>parser.parseTradeShowWorkbook(xlsx.subarray(0,xlsx.length-20),'corrupt.xlsx',1,'UTC'),/corrupt/);const encrypted=Buffer.from(xlsx),central=encrypted.indexOf(Buffer.from([0x50,0x4b,0x01,0x02]));encrypted.writeUInt16LE(encrypted.readUInt16LE(central+8)|1,central+8);assert.throws(()=>parser.parseTradeShowWorkbook(encrypted,'encrypted.xlsx',1,'UTC'),/Encrypted or password-protected/);const macro=Buffer.from(zipSync({'[Content_Types].xml':strToU8('x'),'_rels/.rels':strToU8('x'),'xl/workbook.xml':strToU8('x'),'xl/_rels/workbook.xml.rels':strToU8('x'),'xl/worksheets/sheet1.xml':strToU8('x'),'xl/vbaProject.bin':strToU8('x')}));assert.throws(()=>parser.parseTradeShowWorkbook(macro,'macro.xlsx',1,'UTC'),/Macro-enabled/);assert.throws(()=>parser.parseTradeShowWorkbook(xlsx,'macro.xlsm',1,'UTC'),/supported \.xls or \.xlsx/);assert.throws(()=>parser.parseTradeShowWorkbook(xlsx,'data.csv',1,'UTC'),/supported \.xls or \.xlsx/);});
test('compressed .xlsx content cannot expand beyond the safe import bound',()=>{const oversized=Buffer.from(zipSync({'xl/worksheets/sheet1.xml':new Uint8Array(20_000_001)}));assert.ok(oversized.length<parser.MAX_TRADE_SHOW_FILE_BYTES);assert.throws(()=>parser.parseTradeShowWorkbook(oversized,'oversized.xlsx',1,'UTC'),/expands beyond the safe import limit/);});
test('row and file limits remain enforced',()=>{const many=[['Captured Date','FirstName','LastName','Company'],...Array.from({length:1001},()=>['1/1/26 1:00 PM','A','B','C'])];const largeBook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(largeBook,XLSX.utils.aoa_to_sheet(many),'ExportExtensionsFlatFile1');for(const [extension,bookType] of [['xls','biff8'],['xlsx','xlsx']])assert.throws(()=>parser.parseTradeShowWorkbook(XLSX.write(largeBook,{type:'buffer',bookType}),`many.${extension}`,1,'UTC'),/1000/);assert.throws(()=>parser.parseTradeShowWorkbook(Buffer.alloc(parser.MAX_TRADE_SHOW_FILE_BYTES+1),'large.xlsx',1,'UTC'),/2 MB/);});
test('timezone parsing uses named zone, omits the missing warning when set, and safely handles DST gaps and folds',()=>{const present=parser.parseCaptureTime('1/13/26 3:04 PM','America/New_York');assert.equal(present.iso,'2026-01-13T20:04:00.000Z');assert.equal(present.warning,undefined);assert.match(parser.parseCaptureTime('3/8/26 2:30 AM','America/New_York').warning,/does not exist/);assert.match(parser.parseCaptureTime('11/1/26 1:30 AM','America/New_York').warning,/ambiguous/);assert.match(parser.parseCaptureTime('1/1/26 1:00 PM',null).warning,/missing/);});
test('source key is stable, changes with scan time/show, and ignores Badge ID',()=>{const row=parse('NRA').rows[0],same={...row,rawSourceData:{...row.rawSourceData,'Badge Id':'different'}};assert.equal(parser.sourceKeyV1(42,row),parser.sourceKeyV1(42,same));assert.equal(parser.sourceKeyV1(42,row),row.sourceKey);assert.notEqual(parser.sourceKeyV1(43,row),row.sourceKey);assert.notEqual(parser.sourceKeyV1(42,{...row,capturedSource:row.capturedSource+' later'}),row.sourceKey);assert.equal(parse('NRA').rows.length,new Set(parse('NRA').rows.map(r=>r.sourceKey)).size);});
test('placeholder identity is excluded while raw value and useful row survive',()=>{const row=parse('NRA').rows.find(r=>r.warnings.some(w=>w.includes('placeholder')));assert.ok(row);assert.ok(Object.values(row.rawSourceData).some(v=>/^\([^)]+\)$/.test(v)));assert.equal(row.invalid,false);for(const value of [row.email,row.phone,row.title])assert.ok(!value||!/^\(/.test(value));});
test('preview behavior is identical across generated .xls and .xlsx fixtures',async()=>{const actor={id:7,role:'MARKETING_MANAGER',active:true,archivedAt:null};const accounts=[{id:1,name:'Example Retail',website:'https://example.test'},{id:2,name:'Example Logistics',website:'https://example-logistics.test'}],contacts=[{id:5,firstName:'Existing',lastName:'Contact',email:'alice@example.test',accountId:1,account:{name:'Example Retail'}},{id:6,firstName:'Existing',lastName:'Logistics',email:'morgan@example.test',accountId:2,account:{name:'Example Logistics'}}];const client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},tradeShowLead:{findMany:async()=>[]},account:{findMany:async()=>accounts},contact:{findMany:async()=>contacts},user:{findMany:async()=>[]},tradeShowImport:{count:async()=>0}};for(const profile of ['nra_nrf','modex']){const xls=await importer.previewTradeShowImport(client,42,fixtureBuffer(profile,'xls'),`${profile}.xls`,actor),xlsx=await importer.previewTradeShowImport(client,42,fixtureBuffer(profile,'xlsx'),`${profile}.xlsx`,actor);assert.deepEqual(xlsx.rows,xls.rows);assert.deepEqual(xlsx.summary,xls.summary);assert.equal(xlsx.summary.duplicateEmailGroups,1);assert.equal(xlsx.summary.placeholderRows,1);assert.ok(xlsx.rows.every(row=>row.matches.accountSuggestion));assert.ok(xlsx.rows.every(row=>row.matches.contactSuggestion));assert.ok(xlsx.rows.every(row=>row.warnings.some(warning=>warning.includes('scans share this email'))));}});
test('exact Contact and Account suggestions are strong; ambiguity and website domain stay explicit',()=>{const row={email:'person@example.com',sourceCompany:'Example Incorporated',sourceCompanyWebsite:'www.example.com'};const accounts=[{id:1,name:'Example Incorporated',website:null},{id:2,name:'Other',website:'https://example.com'}],contacts=[{id:5,firstName:'A',lastName:'B',email:'PERSON@example.com',accountId:1}];let m=importer.suggestMatches(row,accounts,contacts);assert.equal(m.contactSuggestion,5);assert.equal(m.accountSuggestion,1);m=importer.suggestMatches({...row,sourceCompany:'Unknown'},accounts,[...contacts,{...contacts[0],id:6}]);assert.equal(m.contactSuggestion,null);assert.equal(m.accountSuggestion,2);assert.equal(m.contactMatches.length,2);});
test('transactional confirmation validates reps, creates history and leads, and does not mutate CRM records',async()=>{const buffer=read('NRA'),parsed=parse('NRA');let history,updatedHistory,leadCreates=0,accountWrites=0,contactWrites=0,opportunityWrites=0;const tx={user:{findMany:async()=>[{id:9}]},account:{findMany:async()=>[],update:async()=>accountWrites++},contact:{findMany:async()=>[],update:async()=>contactWrites++},opportunity:{update:async()=>opportunityWrites++},tradeShowImport:{create:async({data})=>(history={id:3,...data}),update:async({data})=>updatedHistory=data},tradeShowLead:{findUnique:async()=>null,create:async()=>{leadCreates++},update:async()=>{throw Error('unexpected refresh')}}};const client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},$transaction:async callback=>callback(tx)};const choices=parsed.rows.map(r=>({sourceKey:r.sourceKey,repId:null,accountId:null,contactId:null,refresh:false}));const result=await importer.confirmTradeShowImport(client,42,buffer,files.NRA,{id:7,role:'MARKETING_MANAGER',active:true,archivedAt:null},parsed.sha256,9,choices);assert.deepEqual(result,{created:75,existing:0,skipped:0,importId:3});assert.equal(history.rowCount,75);assert.equal(updatedHistory.createdCount,75);assert.equal(leadCreates,75);assert.equal(accountWrites+contactWrites+opportunityWrites,0);await assert.rejects(importer.confirmTradeShowImport(client,42,buffer,files.NRA,{id:7,role:'SALES',active:true,archivedAt:null},parsed.sha256,9,choices),/Access denied/);});
test('default rep permits row override, rejects inactive rep, and existing source stays protected without refresh',async()=>{const buffer=read('NRA'),parsed=parse('NRA'),choices=parsed.rows.map((r,i)=>({sourceKey:r.sourceKey,repId:i===0?10:null,accountId:null,contactId:null,refresh:false}));let reps=[{id:9},{id:10}],updates=0,assignments=[];const tx={user:{findMany:async()=>reps},account:{findMany:async()=>[]},contact:{findMany:async()=>[]},tradeShowImport:{create:async()=>({id:3}),update:async()=>{}},tradeShowLead:{findUnique:async({where})=>where.tradeShowId_sourceKey.sourceKey===parsed.rows[0].sourceKey?{id:1,rawSourceData:{changed:true}}:null,create:async({data})=>assignments.push(data.assignedSalesRepUserId),update:async()=>updates++}};const client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},$transaction:async callback=>callback(tx)};await importer.confirmTradeShowImport(client,42,buffer,files.NRA,{id:1,role:'ADMIN',active:true},parsed.sha256,9,choices);assert.equal(updates,0);assert.ok(assignments.every(id=>id===9));choices[1].repId=11;reps=[{id:9}];await assert.rejects(importer.confirmTradeShowImport(client,42,buffer,files.NRA,{id:1,role:'ADMIN',active:true},parsed.sha256,9,choices),/active Sales reps/);});
test('review tables use synchronized scroll and bounded wrapping for realistic long values',()=>{const workflow=fs.readFileSync(path.join(root,'app/trade-shows/[id]/import/workflow.tsx'),'utf8'),detail=fs.readFileSync(path.join(root,'app/trade-shows/[id]/page.tsx'),'utf8');for(const source of [workflow,detail]){assert.match(source,/TableScroll/);assert.match(source,/table-fixed/);assert.match(source,/break-words/);}assert.match(workflow,/whitespace-pre-wrap/);assert.match(workflow,/text-sm/);const long={email:'averylongmailboxname.for.trade.show.followup@an-extraordinarily-long-corporate-domain.example',sourceCompany:'A Very Long International Company Name Holdings and Distribution Incorporated',sourceCompanyWebsite:'https://an-extraordinarily-long-corporate-domain.example'};const match=importer.suggestMatches(long,[{id:1,name:long.sourceCompany,website:long.sourceCompanyWebsite}],[]);assert.equal(match.accountSuggestion,1);});
test('upload copy and server extension gate advertise only .xls and .xlsx Trade Show exports',()=>{const workflow=fs.readFileSync(path.join(root,'app/trade-shows/[id]/import/workflow.tsx'),'utf8'),actions=fs.readFileSync(path.join(root,'app/trade-shows/[id]/import/actions.ts'),'utf8');assert.match(workflow,/Trade Show lead exports only \(\.xls or \.xlsx\)/);assert.match(workflow,/Choose Excel file/);assert.match(workflow,/\.xls,\.xlsx,application\/vnd\.ms-excel,application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet/);assert.match(actions,/\\\.\(\?:xls\|xlsx\)\$/);assert.doesNotMatch(workflow,/generic Excel/i);});
test('confirmation requires rep only for Sales routing and preserves review state on errors',()=>{const workflow=fs.readFileSync(path.join(root,'app/trade-shows/[id]/import/workflow.tsx'),'utf8');assert.match(workflow,/defaultRouting==='BIXOLON_SALES'&&!defaultRep/);assert.match(workflow,/Select a Default Sales Rep before importing these leads\./);assert.match(workflow,/Select a Partner Account before importing these leads\./);assert.match(workflow,/if \(response\.error\) setConfirmError\(response\.error\)/);assert.match(workflow,/role="alert"[^>]*>\{confirmError\}<\/p>/);assert.match(workflow,/\.\.\.prior\[itemIndex\]/);});
test('SheetJS read remains restricted to the first sheet with parser hardening disabled features',()=>{const source=fs.readFileSync(path.join(root,'lib/trade-show-import-parser.ts'),'utf8');for(const option of ['cellFormula:false','cellHTML:false','cellStyles:false','sheetStubs:false','bookDeps:false','bookVBA:false','bookFiles:false'])assert.ok(source.includes(option),`${option} must remain disabled`);assert.ok(source.includes('sheets:0'));});
test('preview is read-only, ignores JSON key order, and identifies protected source changes',async()=>{const parsed=parse('NRA'),ordered=parsed.rows[0].rawSourceData,reordered=Object.fromEntries(Object.entries(ordered).reverse());let writes=0,changed=false;const client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null}),update:async()=>writes++},tradeShowLead:{findMany:async()=>[{sourceKey:parsed.rows[0].sourceKey,rawSourceData:changed?{...reordered,Notes:'changed'}:reordered}],create:async()=>writes++},account:{findMany:async()=>[],update:async()=>writes++},contact:{findMany:async()=>[],update:async()=>writes++},user:{findMany:async()=>[{id:9,firstName:'Sales',lastName:'Rep'}]},tradeShowImport:{count:async()=>0,create:async()=>writes++}};let plan=await importer.previewTradeShowImport(client,42,read('NRA'),files.NRA,{id:7,role:'MARKETING_MANAGER',active:true,archivedAt:null});assert.equal(plan.rows[0].state,'ALREADY_IMPORTED');changed=true;plan=await importer.previewTradeShowImport(client,42,read('NRA'),files.NRA,{id:7,role:'MARKETING_MANAGER',active:true,archivedAt:null});assert.equal(plan.rows[0].state,'SOURCE_CHANGED');assert.equal(writes,0);});

const customFiles={FSTEC:'FSTEC.xlsx',RETAILNOW:'Leads_Report_RetailNOW.xlsx'};
const customRead=name=>fs.readFileSync(path.join(refs,customFiles[name]));
const fstecMapping={version:1,columns:[
  ['First Name','firstName'],['Last Name','lastName'],['Email Address','email'],['Company Name','sourceCompany'],['Title','title'],
  ['Created Date and Time US/Eastern','capturedAt'],['Work Phone Number','phone'],['Lead Access Code',null],['Notes','sourceNotes'],
].map(([sourceHeader,destination])=>({sourceHeader,destination}))};
const retailMapping={version:1,columns:[
  ['Booth Staff (App User)',null],['Lead First Name','firstName'],['Lead Last Name','lastName'],['Pronouns',null],['Title','title'],['Organization','sourceCompany'],['Email Address','email'],['Work Phone',null],['Cell Phone','phone'],
  ['Address 1',null],['Address 2','addressLine1'],['Address 3','addressLine2'],['City','city'],['State','stateProvince'],['Zip/Postal Code','postalCode'],['Country','country'],['Rating',null],['Notes','sourceNotes'],['Tags',null],
].map(([sourceHeader,destination])=>({sourceHeader,destination}))};
const actor={id:7,role:'MARKETING_MANAGER',active:true,archivedAt:null};
function previewClient(saved=[]){return {tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},tradeShowImportMapping:{findMany:async()=>saved},tradeShowLead:{findMany:async()=>[]},account:{findMany:async()=>[]},contact:{findMany:async()=>[]},user:{findMany:async()=>[]},tradeShowImport:{count:async()=>0}};}

test('real FSTEC workbook uses custom mapping, preserves source-only data, parses timestamps, and keeps stable source keys',()=>{
  const buffer=customRead('FSTEC'),inspection=parser.inspectTradeShowWorkbook(buffer,customFiles.FSTEC);
  assert.equal(inspection.builtInFormat,null);assert.equal(inspection.sheet,'Leads Per Booth Staff');assert.equal(inspection.rows.length,15);
  const parsed=parser.parseTradeShowWorkbook(buffer,customFiles.FSTEC,42,'America/New_York',fstecMapping);
  assert.equal(parsed.format,'CUSTOM_MAPPING');assert.equal(parsed.rows.length,15);assert.equal(parsed.rows[0].capturedAt,'2025-09-15T19:39:00.000Z');assert.ok(parsed.rows.every(row=>row.identityStrategy==='CAPTURE_TIME'));
  assert.equal(parsed.rows[0].sourceNotes.includes('restaurants in Canada'),true);assert.equal(parsed.rows[0].rawSourceData['Lead Access Code'],'n-qvtic0j');assert.equal(parsed.rows[0].sourceLeadId,null);
  const converted=XLSX.write(XLSX.read(buffer,{type:'buffer'}),{type:'buffer',bookType:'biff8'}),xls=parser.parseTradeShowWorkbook(converted,'FSTEC.xls',42,'America/New_York',fstecMapping);
  assert.deepEqual(xls.rows.map(row=>row.sourceKey),parsed.rows.map(row=>row.sourceKey));assert.equal(parser.inspectTradeShowWorkbook(converted,'FSTEC.xls').headerFingerprint,inspection.headerFingerprint);
});

test('real RetailNOW falls to mapping and exposes vendor-only columns without inferring staff identity',async()=>{
  const inspected=parser.inspectTradeShowWorkbook(customRead('RETAILNOW'),customFiles.RETAILNOW);assert.equal(inspected.builtInFormat,null);assert.equal(inspected.sheet,'Leads Report');assert.equal(inspected.rows.length,13);
  for(const header of ['Booth Staff (App User)','Work Phone','Cell Phone','Rating','Notes','Tags'])assert.ok(inspected.headers.includes(header));
  assert.equal(parser.MAPPING_DESTINATIONS.some(([value])=>value==='assignedSalesRepUserId'),false);assert.doesNotThrow(()=>parser.validateMapping(inspected.headers,retailMapping));
  const parsed=parser.parseTradeShowWorkbook(customRead('RETAILNOW'),customFiles.RETAILNOW,42,'America/New_York',retailMapping);assert.equal(parsed.rows.length,13);assert.ok(parsed.rows.every(row=>row.identityStrategy==='ATTENDEE_FIELDS'&&row.capturedAt===null));assert.ok(parsed.rows.every(row=>'Booth Staff (App User)' in row.rawSourceData&&'Rating' in row.rawSourceData&&'Tags' in row.rawSourceData));
  const converted=XLSX.write(XLSX.read(customRead('RETAILNOW'),{type:'buffer'}),{type:'buffer',bookType:'biff8'}),xls=parser.parseTradeShowWorkbook(converted,'RetailNOW.xls',42,'America/New_York',retailMapping);assert.deepEqual(xls.rows.map(row=>row.sourceKey),parsed.rows.map(row=>row.sourceKey));
  const plan=await importer.previewTradeShowImport(previewClient(),42,customRead('RETAILNOW'),customFiles.RETAILNOW,actor,{definition:retailMapping,id:null,name:null});assert.equal(plan.summary.total,13);assert.equal(plan.summary.invalid,0);assert.equal(plan.summary.fallbackIdentityRows,13);assert.ok(plan.rows.every(row=>row.warnings.some(warning=>warning.includes('attendee\'s identifying fields'))));
});

test('custom mapping requires attendee fields and contactability while rejecting duplicate destinations',()=>{
  const headers=parser.inspectTradeShowWorkbook(customRead('FSTEC'),customFiles.FSTEC).headers;
  const incomplete={version:1,columns:headers.map(sourceHeader=>({sourceHeader,destination:sourceHeader==='First Name'?'firstName':null}))};
  assert.throws(()=>parser.validateMapping(headers,incomplete),/Last Name, Company, Email or Phone/);
  const duplicate={version:1,columns:fstecMapping.columns.map(column=>column.sourceHeader==='Work Phone Number'?{...column,destination:'email'}:column)};
  assert.throws(()=>parser.validateMapping(headers,duplicate),/Email.*only be mapped once/);
});

test('header fingerprints ignore order and container while changed or missing mapped headers require review',()=>{
  const buffer=customRead('FSTEC'),inspected=parser.inspectTradeShowWorkbook(buffer,customFiles.FSTEC),workbook=XLSX.read(buffer,{type:'buffer'}),sheet=workbook.Sheets[workbook.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,defval:''});
  const reversed=aoa.map(row=>[...row].reverse()),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(reversed),'Renamed');
  const reordered=parser.inspectTradeShowWorkbook(XLSX.write(book,{type:'buffer',bookType:'xlsx'}),'reordered.xlsx');assert.equal(reordered.headerFingerprint,inspected.headerFingerprint);
  assert.equal(parser.mappingCompatibility([...inspected.headers,'New Survey Question'],fstecMapping),'COMPATIBLE');
  assert.equal(parser.mappingCompatibility(inspected.headers.filter(header=>header!=='Created Date and Time US/Eastern'),fstecMapping),'MISSING_HEADERS');
});

function customWorkbook(headers,rows,bookType='xlsx'){const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([headers,...rows]),'Leads');return XLSX.write(book,{type:'buffer',bookType});}
const strongHeaders=['First','Last','Company','Email','Phone','Scan ID','Notes','Tags'];
const strongMapping={version:1,columns:strongHeaders.map(sourceHeader=>({sourceHeader,destination:({First:'firstName',Last:'lastName',Company:'sourceCompany',Email:'email',Phone:'phone','Scan ID':'sourceLeadId',Notes:'sourceNotes'}[sourceHeader]??null)}))};
const fallbackMapping={version:1,columns:strongMapping.columns.map(column=>column.sourceHeader==='Scan ID'?{...column,destination:null}:column)};

test('deliberately mapped Source Lead ID is a strong stable key without a captured timestamp',()=>{
  const first=customWorkbook(strongHeaders,[['Jamie','Doe','Example Co','jamie@example.com','(555) 111-2222','scan-100','first note','hot']]),changed=customWorkbook(strongHeaders,[['Changed','Person','Other Co','other@example.com','999','scan-100','changed note','cold']]);
  const a=parser.parseTradeShowWorkbook(first,'source-id.xlsx',42,'America/New_York',strongMapping).rows[0],b=parser.parseTradeShowWorkbook(changed,'changed.xlsx',42,'America/New_York',strongMapping).rows[0];
  assert.equal(a.identityStrategy,'SOURCE_LEAD_ID');assert.equal(a.capturedAt,null);assert.equal(a.sourceKey,b.sourceKey);assert.match(a.sourceKey,/^v1:source-id:/);
  assert.notEqual(a.sourceKey,parser.parseTradeShowWorkbook(first,'source-id.xlsx',43,'America/New_York',strongMapping).rows[0].sourceKey);
});

test('fallback attendee key is stable across repeats, note/tag changes, column order and Excel containers',()=>{
  const row=[' Jamie ','Doe','Example Co','JAMIE@example.com','(555) 111-2222','','first note','hot'],xlsx=customWorkbook(strongHeaders,[row]),changed=customWorkbook(strongHeaders,[[...row.slice(0,6),'different note','cold']]);
  const expected=parser.parseTradeShowWorkbook(xlsx,'fallback.xlsx',42,'America/New_York',fallbackMapping).rows[0];
  assert.equal(expected.identityStrategy,'ATTENDEE_FIELDS');assert.equal(expected.capturedAt,null);assert.equal(parser.parseTradeShowWorkbook(changed,'changed.xlsx',42,'America/New_York',fallbackMapping).rows[0].sourceKey,expected.sourceKey);
  const reversedHeaders=[...strongHeaders].reverse(),reversedRow=[...row].reverse(),reversedMapping={version:1,columns:[...fallbackMapping.columns].reverse()};
  assert.equal(parser.parseTradeShowWorkbook(customWorkbook(reversedHeaders,[reversedRow]),'reordered.xlsx',42,'America/New_York',reversedMapping).rows[0].sourceKey,expected.sourceKey);
  assert.equal(parser.parseTradeShowWorkbook(customWorkbook(strongHeaders,[row],'biff8'),'fallback.xls',42,'America/New_York',fallbackMapping).rows[0].sourceKey,expected.sourceKey);
});

test('identical fallback identities are flagged and both raw rows remain reviewable',async()=>{
  const buffer=customWorkbook(strongHeaders,[['Jamie','Doe','Example Co','jamie@example.com','','','first note','hot'],['Jamie','Doe','Example Co','jamie@example.com','','','second note','cold']]);
  const plan=await importer.previewTradeShowImport(previewClient(),42,buffer,'duplicates.xlsx',actor,{definition:fallbackMapping,id:null,name:null});
  assert.equal(plan.summary.fallbackCollisionGroups,1);assert.equal(plan.rows.length,2);assert.equal(plan.rows[0].state,'NEW');assert.equal(plan.rows[1].state,'ALREADY_IMPORTED');assert.notDeepEqual(plan.rows[0].rawSourceData,plan.rows[1].rawSourceData);assert.ok(plan.rows.every(row=>row.warnings.some(warning=>warning.includes('identical fallback identity fields'))));
});

test('fallback confirmation persists null capturedAt safely',async()=>{
  const buffer=customWorkbook(strongHeaders,[['Jamie','Doe','Example Co','jamie@example.com','','','note','tag']]),parsed=parser.parseTradeShowWorkbook(buffer,'fallback.xlsx',42,'America/New_York',fallbackMapping);let created=null;
  const tx={user:{findMany:async()=>[{id:9}]},account:{findMany:async()=>[]},contact:{findMany:async()=>[]},tradeShowImport:{create:async()=>({id:3}),update:async()=>{}},tradeShowLead:{findUnique:async()=>null,create:async({data})=>{created=data}}},client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},$transaction:async callback=>callback(tx)};
  const choices=parsed.rows.map(row=>({sourceKey:row.sourceKey,repId:null,accountId:null,contactId:null,refresh:false}));await importer.confirmTradeShowImport(client,42,buffer,'fallback.xlsx',actor,parsed.sha256,9,choices,{definition:fallbackMapping,id:null,name:null});assert.equal(created.capturedAt,null);
});

test('review correction validates email, preserves raw provenance, reruns matching, imports corrected values, and remains repeat-safe',async()=>{
  const buffer=customWorkbook(strongHeaders,[['Info','Desk','Company LLC','info @company.com','','','source note','raw-only']]);
  const parsed=parser.parseTradeShowWorkbook(buffer,'correction.xlsx',42,'America/New_York',fallbackMapping),original=parsed.rows[0];
  const contacts=[{id:55,firstName:'Info',lastName:'Desk',email:'info@company.com',accountId:8,account:{name:'Company LLC'}}],accounts=[{id:8,name:'Company LLC',website:null}];
  const client=previewClient();client.account.findMany=async()=>accounts;client.contact.findMany=async()=>contacts;
  const initial=await importer.previewTradeShowImport(client,42,buffer,'correction.xlsx',actor,{definition:fallbackMapping,id:null,name:null});
  assert.equal(initial.rows[0].state,'INVALID');assert.ok(initial.rows[0].warnings.includes('Email is invalid.'));assert.equal(initial.rows[0].sourceValues.email,'info @company.com');assert.equal(initial.rows[0].rawSourceData.Email,'info @company.com');
  const reviews=[{originalSourceKey:original.sourceKey,reviewedOverrides:{email:'info@company.com'}}];
  const corrected=await importer.reviewTradeShowImport(client,42,buffer,'correction.xlsx',actor,{definition:fallbackMapping,id:null,name:null},reviews),row=corrected.rows[0];
  assert.equal(row.invalid,false);assert.equal(row.state,'NEW');assert.equal(row.email,'info@company.com');assert.equal(row.warnings.includes('Email is invalid.'),false);assert.deepEqual(row.correctionErrors,[]);assert.equal(row.matches.contactSuggestion,55);assert.equal(row.matches.accountSuggestion,8);assert.notEqual(row.sourceKey,original.sourceKey);assert.equal(row.originalSourceKey,original.sourceKey);assert.equal(row.rawSourceData.Email,'info @company.com');
  let created=null;const tx={user:{findMany:async()=>[{id:9}]},account:{findMany:async()=>[{id:8}]},contact:{findMany:async()=>[{id:55,accountId:8}]},tradeShowImport:{create:async()=>({id:3}),update:async()=>{}},tradeShowLead:{findUnique:async()=>null,findFirst:async()=>null,create:async({data})=>{created=data},update:async()=>{throw Error('unexpected update')}}};
  const confirmClient={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},$transaction:async callback=>callback(tx)},choices=[{sourceKey:row.sourceKey,originalSourceKey:row.originalSourceKey,reviewedOverrides:row.reviewedOverrides,repId:null,accountId:8,contactId:55,refresh:false}];
  const result=await importer.confirmTradeShowImport(confirmClient,42,buffer,'correction.xlsx',actor,parsed.sha256,9,choices,{definition:fallbackMapping,id:null,name:null});
  assert.equal(result.created,1);assert.equal(created.email,'info@company.com');assert.equal(created.rawSourceData.Email,'info @company.com');assert.deepEqual(created.reviewedOverrides,{email:'info@company.com'});assert.equal(created.sourceOriginalKey,original.sourceKey);assert.equal(created.sourceKey,row.sourceKey);
  const repeatClient=previewClient();repeatClient.account.findMany=async()=>accounts;repeatClient.contact.findMany=async()=>contacts;repeatClient.tradeShowLead.findMany=async()=>[{sourceKey:created.sourceKey,sourceOriginalKey:created.sourceOriginalKey,rawSourceData:created.rawSourceData,reviewedOverrides:created.reviewedOverrides}];
  const repeated=await importer.previewTradeShowImport(repeatClient,42,buffer,'correction.xlsx',actor,{definition:fallbackMapping,id:null,name:null});
  assert.equal(repeated.rows[0].state,'ALREADY_IMPORTED');assert.equal(repeated.rows[0].sourceKey,created.sourceKey);assert.equal(repeated.rows[0].email,'info@company.com');assert.equal(repeated.rows[0].matches.contactSuggestion,55);
});

test('invalid reviewed correction is blocked while an untouched row keeps parser behavior',async()=>{
  const invalidBuffer=customWorkbook(strongHeaders,[['Info','Desk','Company LLC','info @company.com','','','','']]),invalidParsed=parser.parseTradeShowWorkbook(invalidBuffer,'invalid-correction.xlsx',42,'America/New_York',fallbackMapping),reviews=[{originalSourceKey:invalidParsed.rows[0].sourceKey,reviewedOverrides:{email:'still invalid'}}];
  const plan=await importer.reviewTradeShowImport(previewClient(),42,invalidBuffer,'invalid-correction.xlsx',actor,{definition:fallbackMapping,id:null,name:null},reviews),row=plan.rows[0];
  assert.equal(row.state,'INVALID');assert.ok(row.correctionErrors.includes('Email correction is invalid.'));assert.ok(row.warnings.includes('Email is invalid.'));
  const choice={sourceKey:row.sourceKey,originalSourceKey:row.originalSourceKey,reviewedOverrides:row.reviewedOverrides,repId:null,accountId:null,contactId:null,refresh:false};
  await assert.rejects(importer.confirmTradeShowImport({tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})}},42,invalidBuffer,'invalid-correction.xlsx',actor,invalidParsed.sha256,9,[choice],{definition:fallbackMapping,id:null,name:null}),/Correct invalid reviewed values/);
  const validBuffer=customWorkbook(strongHeaders,[['Jamie','Doe','Example Co','jamie@example.com','555','','note','tag']]),validParsed=parser.parseTradeShowWorkbook(validBuffer,'untouched.xlsx',42,'America/New_York',fallbackMapping),untouched=await importer.previewTradeShowImport(previewClient(),42,validBuffer,'untouched.xlsx',actor,{definition:fallbackMapping,id:null,name:null});
  assert.equal(untouched.rows[0].sourceKey,validParsed.rows[0].sourceKey);assert.equal(untouched.rows[0].email,validParsed.rows[0].email);assert.deepEqual(untouched.rows[0].reviewedOverrides,{});assert.equal(untouched.rows[0].rawSourceData.Email,validParsed.rows[0].rawSourceData.Email);
});

test('reviewed correction schema stores overrides separately and indexes original identity',()=>{
  const schema=fs.readFileSync(path.join(root,'prisma/schema.prisma'),'utf8'),migration=fs.readFileSync(path.join(root,'prisma/migrations/20260923120000_trade_show_reviewed_corrections/migration.sql'),'utf8');
  assert.match(schema,/reviewedOverrides\s+Json\?/);assert.match(schema,/sourceOriginalKey\s+String\?/);assert.match(schema,/@@index\(\[tradeShowId, sourceOriginalKey\]\)/);assert.match(migration,/ADD COLUMN "reviewedOverrides" JSONB/);assert.match(migration,/sourceOriginalKey/);
});

test('manual preview can save a mapping and exact headers reuse it without CRM mutation',async()=>{
  let created=null,writes=0;const client=previewClient();client.tradeShowImportMapping.create=async({data})=>(created={id:11,name:data.name,...data});client.tradeShowLead.create=async()=>writes++;client.account.update=async()=>writes++;client.contact.update=async()=>writes++;
  const plan=await importer.previewMappedTradeShowImport(client,42,customRead('FSTEC'),customFiles.FSTEC,actor,fstecMapping,'FSTEC Lead Export');
  assert.equal(created.name,'FSTEC Lead Export');assert.equal(plan.mapping.id,11);assert.equal(plan.summary.total,15);assert.equal(writes,0);
  const saved={id:11,name:'FSTEC Lead Export',headerFingerprint:plan.parsed.headerFingerprint,mappings:fstecMapping,lastUsedAt:null};
  const reused=await importer.prepareTradeShowImport(previewClient([saved]),42,customRead('FSTEC'),customFiles.FSTEC,actor);
  assert.equal(reused.mappingRequired,null);assert.equal(reused.plan.mapping.name,'FSTEC Lead Export');assert.equal(reused.plan.parsed.format,'CUSTOM_MAPPING');
});

test('compatible added headers suggest a saved mapping but require review',async()=>{
  const source=customRead('FSTEC'),workbook=XLSX.read(source,{type:'buffer'}),sheet=workbook.Sheets[workbook.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,defval:''});aoa[0].push('New Survey Question');for(let index=1;index<aoa.length;index++)aoa[index].push(index===1?'Sample answer':'');const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(aoa),'Leads Per Booth Staff');const buffer=XLSX.write(book,{type:'buffer',bookType:'xlsx'});
  const fingerprint=parser.inspectTradeShowWorkbook(source,customFiles.FSTEC).headerFingerprint,saved={id:4,name:'FSTEC Lead Export',headerFingerprint:fingerprint,mappings:fstecMapping,lastUsedAt:null};const result=await importer.prepareTradeShowImport(previewClient([saved]),42,buffer,'changed.xlsx',actor);
  assert.equal(result.plan,null);assert.equal(result.mappingRequired.suggested.name,'FSTEC Lead Export');assert.equal(result.mappingRequired.suggested.status,'COMPATIBLE');assert.equal(result.mappingRequired.definition.columns.at(-1).destination,null);
});

test('custom confirmed import remains transactional and idempotent',async()=>{
  const buffer=customRead('FSTEC'),parsed=parser.parseTradeShowWorkbook(buffer,customFiles.FSTEC,42,'America/New_York',fstecMapping),stored=new Set(),histories=[];let transactions=0,accountWrites=0,contactWrites=0;
  const tx={user:{findMany:async()=>[{id:9}]},account:{findMany:async()=>[],update:async()=>accountWrites++},contact:{findMany:async()=>[],update:async()=>contactWrites++},tradeShowImport:{create:async({data})=>{histories.push(data);return{id:histories.length}},update:async()=>{}},tradeShowLead:{findUnique:async({where})=>stored.has(where.tradeShowId_sourceKey.sourceKey)?{id:1,rawSourceData:{}}:null,create:async({data})=>{stored.add(data.sourceKey)},update:async()=>{}}};
  const client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},$transaction:async callback=>{transactions++;return callback(tx)}};const choices=parsed.rows.map(row=>({sourceKey:row.sourceKey,repId:null,accountId:null,contactId:null,refresh:false})),selection={definition:fstecMapping,id:null,name:null};
  const first=await importer.confirmTradeShowImport(client,42,buffer,customFiles.FSTEC,actor,parsed.sha256,9,choices,selection),second=await importer.confirmTradeShowImport(client,42,buffer,customFiles.FSTEC,actor,parsed.sha256,9,choices,selection);
  assert.equal(first.created,15);assert.equal(second.existing,15);assert.equal(transactions,2);assert.equal(histories.every(history=>history.format==='CUSTOM_MAPPING'),true);assert.equal(accountWrites+contactWrites,0);
});

test('only Marketing Manager and Admin can manage saved mappings',async()=>{
  let updates=0;const client={tradeShowImportMapping:{update:async()=>{updates++;return{id:1}}}};
  await mappingManager.renameTradeShowImportMapping(client,1,'Renamed',actor);await mappingManager.setTradeShowImportMappingArchived(client,1,true,{...actor,role:'ADMIN'});assert.equal(updates,2);
  await assert.rejects(mappingManager.renameTradeShowImportMapping(client,1,'Denied',{...actor,role:'SALES'}),/Access denied/);assert.equal(updates,2);
});

test('routing defaults and row overrides remove the unconditional import rep requirement',async()=>{
  const buffer=read('NRA'),parsed=parse('NRA'),actor={id:7,role:'MARKETING_MANAGER',active:true,archivedAt:null};
  const run=async(defaultRouting,defaultRep,defaultPartner,override={})=>{const created=[];const tx={user:{findMany:async()=>defaultRep?[{id:defaultRep}]:[]},account:{findMany:async({where})=>where.businessRoles?[{id:20}]:[]},contact:{findMany:async()=>[]},tradeShowImport:{create:async()=>({id:3}),update:async()=>{}},tradeShowLead:{findUnique:async()=>null,create:async({data})=>created.push(data)}};const client={tradeShow:{findUnique:async()=>({timezone:'America/New_York',archivedAt:null})},$transaction:async callback=>callback(tx)};const choices=parsed.rows.map((row,index)=>({sourceKey:row.sourceKey,originalSourceKey:row.sourceKey,reviewedOverrides:{},routing:index===0?(override.routing??null):null,repId:index===0?(override.repId??null):null,partnerAccountId:index===0?(override.partnerAccountId??null):null,accountId:null,contactId:null,refresh:false}));return {created,result:await importer.confirmTradeShowImport(client,42,buffer,files.NRA,actor,parsed.sha256,defaultRouting,defaultRep,defaultPartner,choices,null)}};
  let outcome=await run('UNREVIEWED',null,null);assert.equal(outcome.result.created,75);assert.ok(outcome.created.every(item=>item.routing==='UNREVIEWED'&&item.assignedSalesRepUserId===null));
  outcome=await run('MARKETING_FOLLOW_UP',null,null);assert.ok(outcome.created.every(item=>item.routing==='MARKETING_FOLLOW_UP'&&item.assignedSalesRepUserId===null));
  await assert.rejects(run('BIXOLON_SALES',null,null),/Default Sales Rep/);
  outcome=await run('UNREVIEWED',null,null,{routing:'REFERRED_TO_PARTNER',partnerAccountId:20});assert.equal(outcome.created[0].routing,'REFERRED_TO_PARTNER');assert.equal(outcome.created[0].routedPartnerAccountId,20);assert.equal(outcome.created[0].referredByUserId,7);
  await assert.rejects(run('REFERRED_TO_PARTNER',null,null),/Partner Account/);
});
