import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Content, PageHeader } from '@/components/shell';
import { currentUser } from '@/lib/current-user';
import { prisma } from '@/lib/prisma';
import { canViewMarketingReports } from '@/lib/marketing-attribution-report';
import { leadSourcesReport, type ProspectFilters } from '@/lib/marketing-prospects';

export const dynamic = 'force-dynamic';
const percent = (part: number, whole: number) => whole ? `${(100 * part / whole).toFixed(1)}%` : '—';

export default async function LeadSourcesPage({ searchParams }: { searchParams: Promise<ProspectFilters> }) {
  const actor = await currentUser(); if (!canViewMarketingReports(actor)) notFound();
  const params = await searchParams;
  const [report, sources, campaigns, reps] = await Promise.all([
    leadSourcesReport(prisma, actor, params),
    prisma.leadSourceOption.findMany({ select: { id: true, name: true, active: true }, orderBy: [{ sortOrder: 'asc' }, { name: 'asc' }] }),
    prisma.marketingCampaign.findMany({ select: { id: true, name: true }, orderBy: { name: 'asc' }, take: 500 }),
    prisma.user.findMany({ where: { role: { in: ['SALES', 'SALES_MANAGER'] } }, select: { id: true, firstName: true, lastName: true }, orderBy: [{ lastName: 'asc' }, { firstName: 'asc' }] }),
  ]);
  const query = (changes: Record<string, string>) => { const next = new URLSearchParams(); for (const [key, value] of Object.entries(params)) if (typeof value === 'string' && !(key in changes)) next.set(key, value); for (const [key, value] of Object.entries(changes)) if (value) next.set(key, value); return `/reports/lead-sources?${next}`; };
  const metrics = [['Unique Prospects', report.summary.uniqueProspects], ['Resolved Contacts', report.summary.resolvedContacts], ['Contact-only Prospects', report.summary.contactOnly], ['Unresolved Leads', report.summary.unresolvedLeads], ['Prospects with Opportunities', report.summary.withOpportunities], ['Source Conflicts', report.summary.sourceConflicts]] as const;
  return <Content>
    <PageHeader eyebrow="Marketing reports" title="Lead Sources" description="Unique people by their current first-touch Lead Source, with linked Trade Show leads counted through their Contact." />
    <form className="panel filter-panel filter-grid filter-row mb-5" method="get" aria-label="Filter Lead Sources">
      <label className="text-sm">From<input className="field mt-1 block w-full" type="date" name="from" defaultValue={params.from} /></label>
      <label className="text-sm">To<input className="field mt-1 block w-full" type="date" name="to" defaultValue={params.to} /></label>
      <label className="text-sm">Lead Source<select className="field mt-1 block w-full" name="leadSourceId" defaultValue={params.leadSourceId ?? ''}><option value="">All sources</option><option value="none">Unspecified</option>{sources.map(source => <option value={source.id} key={source.id}>{source.name}{source.active ? '' : ' (inactive)'}</option>)}</select></label>
      <label className="text-sm">Campaign<select className="field mt-1 block w-full" name="campaignId" defaultValue={params.campaignId ?? ''}><option value="">All campaigns</option>{campaigns.map(campaign => <option value={campaign.id} key={campaign.id}>{campaign.name}</option>)}</select></label>
      <label className="text-sm">Prospect state<select className="field mt-1 block w-full" name="state" defaultValue={params.state ?? ''}><option value="">All prospects</option><option value="CONTACT">Contact</option><option value="UNRESOLVED_LEAD">Unresolved Lead</option></select></label>
      <label className="text-sm">Opportunity association<select className="field mt-1 block w-full" name="opportunity" defaultValue={params.opportunity ?? ''}><option value="">All prospects</option><option value="YES">With Opportunities</option><option value="NO">Without Opportunities</option></select></label>
      <label className="text-sm">Assigned Sales Rep<select className="field mt-1 block w-full" name="ownerId" defaultValue={params.ownerId ?? ''}><option value="">All reps</option>{reps.map(rep => <option value={rep.id} key={rep.id}>{rep.firstName} {rep.lastName}</option>)}</select></label>
      <label className="text-sm">Search<input className="field mt-1 block w-full" name="q" maxLength={100} defaultValue={params.q ?? ''} placeholder="Prospect or company" /></label>
      <div className="flex items-end gap-2"><button className="btn-primary">Filter</button><Link className="btn-secondary" href="/reports/lead-sources">Clear</Link></div>
    </form>
    <p className="mb-4 text-sm text-slate-600">Date range uses matching linked lead capture when available, otherwise Contact creation; unresolved leads use capture or import date. A Contact source takes precedence. Conflicts need Marketing review.</p>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{metrics.map(([label, value]) => <div className="panel p-4" key={label}><p className="text-sm text-slate-600">{label}</p><p className="mt-1 text-2xl font-semibold tabular-nums">{value}</p></div>)}</div>
    <section className="panel mb-5 overflow-x-auto"><h2 className="p-4 text-lg font-semibold">By Lead Source</h2><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Lead Source', 'Unique Prospects', 'Resolved Contacts', 'Contact-only', 'Unresolved Leads', 'Prospects with Opportunities', 'Contact Share', 'Opportunity Association', 'Source Conflicts'].map(label => <th className="px-3 py-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{report.groups.map(group => <tr key={group.leadSourceId ?? 'none'}><td className="px-3 py-3"><Link className="text-orange-800 underline" href={query({ leadSourceId: group.leadSourceId?.toString() ?? 'none', page: '' })}>{group.leadSource}</Link></td><td className="px-3 py-3">{group.uniqueProspects}</td><td className="px-3 py-3">{group.resolvedContacts}</td><td className="px-3 py-3">{group.contactOnly}</td><td className="px-3 py-3">{group.unresolvedLeads}</td><td className="px-3 py-3">{group.withOpportunities}</td><td className="px-3 py-3">{percent(group.resolvedContacts + group.contactOnly, group.uniqueProspects)}</td><td className="px-3 py-3">{percent(group.withOpportunities, group.uniqueProspects)}</td><td className="px-3 py-3">{group.sourceConflicts}</td></tr>)}</tbody></table>{!report.groups.length && <p className="p-4 text-sm text-slate-600">No prospects match these filters.</p>}</section>
    <section className="panel overflow-x-auto"><h2 className="p-4 text-lg font-semibold">Prospect detail</h2><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Prospect', 'Company / Account', 'Lead Source', 'Current State', 'Source Record / Origin', 'Report Date', 'Related Campaigns', 'Opportunity Count', 'Assigned Rep', 'Source Conflict'].map(label => <th className="px-3 py-3" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y">{report.rows.map(row => <tr key={`${row.canonical_type}-${row.canonical_id}`}><td className="px-3 py-3"><Link className="text-orange-800 underline" href={row.canonical_type === 'CONTACT' ? `/contacts/${row.canonical_id}` : `/trade-shows/${row.trade_show_id}/leads/${row.canonical_id}`}>{row.display_name}</Link></td><td className="px-3 py-3">{row.company ?? '—'}</td><td className="px-3 py-3">{row.lead_source ?? 'Unspecified'}</td><td className="px-3 py-3">{row.canonical_type === 'CONTACT' ? 'Contact' : 'Unresolved Lead'}</td><td className="px-3 py-3">{row.canonical_type === 'CONTACT' ? row.linked_leads ? `Contact · ${row.linked_leads} linked Trade Show lead${row.linked_leads === 1 ? '' : 's'}` : 'Contact' : 'Trade Show Lead'}</td><td className="whitespace-nowrap px-3 py-3">{row.report_date.toISOString().slice(0, 10)}<span className="block text-xs text-slate-500">{row.date_basis}</span></td><td className="px-3 py-3">{row.campaign_names ?? '—'}</td><td className="px-3 py-3">{row.opportunity_count}</td><td className="px-3 py-3">{row.owner_name ?? '—'}</td><td className="px-3 py-3">{row.source_conflict ? 'Review' : '—'}</td></tr>)}</tbody></table>{!report.rows.length && <p className="p-4 text-sm text-slate-600">No prospects match these filters.</p>}</section>
    <nav className="mt-4 flex items-center gap-3 text-sm" aria-label="Report pages">{report.filters.page > 1 && <Link className="text-orange-800 underline" href={query({ page: String(report.filters.page - 1) })}>Previous</Link>}<span>Page {report.filters.page}</span>{report.hasNext && <Link className="text-orange-800 underline" href={query({ page: String(report.filters.page + 1) })}>Next</Link>}</nav>
  </Content>;
}
