"use server";
import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { currentUser } from "@/lib/current-user";
import { audienceContactWhere, audienceVisibilities, canManageAudience, canViewAudience, parseAudienceForm } from "@/lib/marketing-audiences";

export type AudienceFormState={message?:string};
function positive(value:FormDataEntryValue|null){const id=Number(value);return Number.isSafeInteger(id)&&id>0?id:null;}
async function managed(id:number){const actor=await currentUser(),audience=await prisma.marketingAudience.findUnique({where:{id}});if(!audience||!canManageAudience(actor,audience))throw new Error("Audience not found or access denied.");return {actor,audience};}

export async function saveAudience(_state:AudienceFormState,form:FormData):Promise<AudienceFormState>{
  const actor=await currentUser();if(!canManageAudience(actor))throw new Error("Access denied");
  const audienceId=positive(form.get("audienceId")),name=String(form.get("name")??"").trim(),description=String(form.get("description")??"").trim()||null,visibility=String(form.get("visibility")??"");
  if(!name||name.length>120)return {message:"Audience name is required and must be 120 characters or fewer."};
  if(description&&description.length>1000)return {message:"Description must be 1,000 characters or fewer."};
  if(!audienceVisibilities.includes(visibility as never))return {message:"Choose a valid visibility."};
  let config;try{config=parseAudienceForm(form);}catch(error){return {message:error instanceof Error?error.message:"Audience filters are invalid."};}
  let id:number;
  if(audienceId){const existing=await prisma.marketingAudience.findUnique({where:{id:audienceId}});if(!existing||!canManageAudience(actor,existing))throw new Error("Access denied");const updated=await prisma.marketingAudience.update({where:{id:audienceId},data:{name,description,visibility:visibility as never,filterConfig:config as Prisma.InputJsonValue,updatedById:actor.id}});id=updated.id;}
  else{id=(await prisma.marketingAudience.create({data:{name,description,visibility:visibility as never,filterConfig:config as Prisma.InputJsonValue,ownerId:actor.id,createdById:actor.id,updatedById:actor.id}})).id;}
  revalidatePath("/marketing/audiences");redirect(`/marketing/audiences/${id}`);
}

export async function duplicateAudience(form:FormData){const sourceId=positive(form.get("audienceId"));if(!sourceId)throw new Error("Invalid audience.");const actor=await currentUser(),source=await prisma.marketingAudience.findUnique({where:{id:sourceId}});if(!source||!canViewAudience(actor,source)||!canManageAudience(actor))throw new Error("Access denied");const copy=await prisma.$transaction(async tx=>{const created=await tx.marketingAudience.create({data:{name:`${source.name} (copy)`.slice(0,120),description:source.description,visibility:"PERSONAL",filterConfig:source.filterConfig as Prisma.InputJsonValue,ownerId:actor.id,createdById:actor.id,updatedById:actor.id}});const overrides=await tx.marketingAudienceContactOverride.findMany({where:{audienceId:source.id}});if(overrides.length)await tx.marketingAudienceContactOverride.createMany({data:overrides.map(x=>({audienceId:created.id,contactId:x.contactId,kind:x.kind}))});return created;});revalidatePath("/marketing/audiences");redirect(`/marketing/audiences/${copy.id}`);}
export async function setAudienceArchived(form:FormData){const id=positive(form.get("audienceId"));if(!id)throw new Error("Invalid audience.");const {actor}=await managed(id);const archived=form.get("archived")==="true";await prisma.marketingAudience.update({where:{id},data:{archivedAt:archived?new Date():null,updatedById:actor.id}});revalidatePath("/marketing/audiences");redirect(archived?"/marketing/audiences":`/marketing/audiences/${id}`);}

export async function setContactSelection(form:FormData){const audienceId=positive(form.get("audienceId")),contactId=positive(form.get("contactId"));if(!audienceId||!contactId)throw new Error("Invalid selection.");const {audience}=await managed(audienceId);if(audience.archivedAt)throw new Error("Archived audiences cannot be changed.");const selected=form.get("selected")==="true";const matches=await prisma.contact.count({where:{AND:[audienceContactWhere(audience.filterConfig),{id:contactId}]}})>0;if(selected){if(matches)await prisma.marketingAudienceContactOverride.deleteMany({where:{audienceId,contactId}});else{const contact=await prisma.contact.findFirst({where:{id:contactId,active:true,archivedAt:null},select:{id:true}});if(!contact)throw new Error("Only active Contacts may be included.");await prisma.marketingAudienceContactOverride.upsert({where:{audienceId_contactId:{audienceId,contactId}},create:{audienceId,contactId,kind:"INCLUDE"},update:{kind:"INCLUDE"}});}}else if(matches)await prisma.marketingAudienceContactOverride.upsert({where:{audienceId_contactId:{audienceId,contactId}},create:{audienceId,contactId,kind:"EXCLUDE"},update:{kind:"EXCLUDE"}});else await prisma.marketingAudienceContactOverride.deleteMany({where:{audienceId,contactId}});revalidatePath(`/marketing/audiences/${audienceId}`);}

export async function selectAllMatching(form:FormData){const id=positive(form.get("audienceId"));if(!id)throw new Error("Invalid audience.");const {audience}=await managed(id);const matched=(await prisma.contact.findMany({where:audienceContactWhere(audience.filterConfig),select:{id:true}})).map(x=>x.id);if(matched.length)await prisma.marketingAudienceContactOverride.deleteMany({where:{audienceId:id,contactId:{in:matched}}});revalidatePath(`/marketing/audiences/${id}`);}
export async function clearAudienceSelection(form:FormData){const id=positive(form.get("audienceId"));if(!id)throw new Error("Invalid audience.");const {audience}=await managed(id);const matched=(await prisma.contact.findMany({where:audienceContactWhere(audience.filterConfig),select:{id:true}})).map(x=>x.id);await prisma.$transaction(async tx=>{await tx.marketingAudienceContactOverride.deleteMany({where:{audienceId:id,kind:"INCLUDE"}});if(matched.length){await tx.marketingAudienceContactOverride.deleteMany({where:{audienceId:id,contactId:{in:matched}}});await tx.marketingAudienceContactOverride.createMany({data:matched.map(contactId=>({audienceId:id,contactId,kind:"EXCLUDE"}))});}});revalidatePath(`/marketing/audiences/${id}`);}
export async function includeContact(form:FormData){const id=positive(form.get("audienceId")),contactId=positive(form.get("contactId"));if(!id||!contactId)throw new Error("Enter a valid Contact ID.");const {audience}=await managed(id);const contact=await prisma.contact.findFirst({where:{id:contactId,active:true,archivedAt:null},select:{id:true}});if(!contact)throw new Error("Active Contact not found.");const matches=await prisma.contact.count({where:{AND:[audienceContactWhere(audience.filterConfig),{id:contactId}]}})>0;if(matches)await prisma.marketingAudienceContactOverride.deleteMany({where:{audienceId:id,contactId}});else await prisma.marketingAudienceContactOverride.upsert({where:{audienceId_contactId:{audienceId:id,contactId}},create:{audienceId:id,contactId,kind:"INCLUDE"},update:{kind:"INCLUDE"}});revalidatePath(`/marketing/audiences/${id}`);}
