import Link from "next/link";
import { Content, PageHeader } from "@/components/shell";
import { currentUser } from "@/lib/current-user";
import { can } from "@/lib/authorization";
import { audienceListWhere, audienceSummary, resolveAudienceContactIds } from "@/lib/marketing-audiences";
import { prisma } from "@/lib/prisma";
import { setAudienceArchived } from "./actions";
export const dynamic="force-dynamic";
export default async function AudiencesPage({searchParams}:{searchParams:Promise<{archived?:string}>}){const actor=await currentUser(),showArchived=(await searchParams).archived==="1";if(!can(actor,"marketing.read"))return null;const audiences=await prisma.marketingAudience.findMany({where:audienceListWhere(actor,showArchived),include:{owner:true},orderBy:[{updatedAt:"desc"},{id:"desc"}],take:50});const rows=await Promise.all(audiences.map(async audience=>{try{const resolved=await resolveAudienceContactIds(prisma,audience);return {...audience,summary:await audienceSummary(prisma,resolved.selected,resolved.matched.length),invalid:null};}catch(error){return {...audience,summary:null,invalid:error instanceof Error?error.message:"Invalid saved filters."};}}));return <Content><PageHeader eyebrow="Marketing" title="Marketing Audiences" description="Reusable Contact audiences that rerun against current SalesHub data." action={can(actor,"marketing.write")?<Link className="btn-primary" href="/marketing/audiences/new">New audience</Link>:undefined}/><div className="mb-4 flex justify-end"><Link className="btn-secondary" href={showArchived?"/marketing/audiences":"/marketing/audiences?archived=1"}>{showArchived?"Active audiences":"Include archived"}</Link></div><div className="panel overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-4 py-3">Audience</th><th className="px-4 py-3">Owner / Visibility</th><th className="px-4 py-3">Selected</th><th className="px-4 py-3">Marketing Ready</th><th className="px-4 py-3">Updated</th><th className="px-4 py-3">State</th></tr></thead><tbody>{rows.map(row=><tr className="border-b odd:bg-white even:bg-slate-50/60 hover:bg-orange-50/50" key={row.id}><td className="px-4 py-3"><Link className="font-semibold text-orange-800 underline" href={`/marketing/audiences/${row.id}`}>{row.name}</Link>{row.invalid&&<p className="mt-1 text-xs text-red-700">Needs filter review</p>}</td><td className="px-4 py-3">{row.owner.firstName} {row.owner.lastName}<span className="block text-xs text-slate-500">{row.visibility==="PERSONAL"?"Personal":"Shared"}</span></td><td className="px-4 py-3">{row.summary?.selected??"—"}</td><td className="px-4 py-3">{row.summary?.marketingReady??"—"}</td><td className="px-4 py-3">{row.updatedAt.toISOString().slice(0,10)}</td><td className="px-4 py-3">{row.archivedAt?<span className="text-slate-500">Archived</span>:"Active"}{row.archivedAt&&can(actor,"marketing.write")&&<form action={setAudienceArchived} className="mt-1"><input type="hidden" name="audienceId" value={row.id}/><input type="hidden" name="archived" value="false"/><button className="text-xs font-semibold text-orange-800 underline">Restore</button></form>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-sm text-slate-500">No Marketing Audiences found.</p>}</div></Content>}
