'use client';
import { useState } from 'react';
import type { ProductImportPlan, ProductImportCounts } from '@/lib/product-import';
import { previewProductUpload, confirmProductUpload } from './actions';

const labels:Record<keyof ProductImportCounts,string>={newProducts:'New Products',updatedProducts:'Updated Products',newSkus:'New SKUs',updatedSkus:'Updated SKUs',priceChanges:'Price changes',unchanged:'Unchanged',warnings:'Warnings',errors:'Errors'};
function Counts({counts}:{counts:ProductImportCounts}) {return <div className="mt-4 grid gap-2 sm:grid-cols-4">{Object.entries(counts).map(([key,value])=><div className="rounded bg-slate-50 p-3 text-sm" key={key}><strong>{value}</strong> {labels[key as keyof ProductImportCounts]}</div>)}</div>;}
function Values({value}:{value:ProductImportPlan['items'][number]['before']}) {return value ? <dl className="min-w-48">{Object.entries(value).map(([key,entry])=><div key={key}><dt className="inline font-medium">{key}: </dt><dd className="inline">{entry===undefined || entry==='' ? '—' : String(entry)}</dd></div>)}</dl> : <span>New record</span>;}
export function ProductImportWorkflow({template}:{template:string}) {
  const [file,setFile]=useState<File|null>(null),[sheet,setSheet]=useState(''),[currency,setCurrency]=useState(''),[sheets,setSheets]=useState<string[]>([]),[plan,setPlan]=useState<ProductImportPlan|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[result,setResult]=useState<ProductImportCounts|null>(null);
  function load(selected?:File) {setFile(null);setSheet('');setSheets([]);setPlan(null);setResult(null);setMessage('');if (!selected)return;const name=selected.name.toLowerCase();if (!name.endsWith('.csv')&&!name.endsWith('.xlsx')){setMessage('Choose a CSV or XLSX file.');return;}if(selected.size>(name.endsWith('.csv')?2_000_000:4_000_000)){setMessage(name.endsWith('.csv')?'CSV limit is 2 MB.':'XLSX limit is 4 MB.');return;}setFile(selected);}
  function form() {const data=new FormData();if(file)data.set('file',file);if(sheet)data.set('sheet',sheet);if(currency)data.set('currency',currency);return data;}
  async function preview() {if(!file)return;setBusy(true);setMessage('');setResult(null);try {const response=await previewProductUpload(form());setPlan(response.plan ?? null);setSheets((response.sheets ?? []).filter(name=>name.trim()!=='TT ribbon'));if(response.selectedSheet)setSheet(response.selectedSheet);if(response.error)setMessage(response.error);}catch{setMessage('Preview failed. Please try again.');}finally{setBusy(false);}}
  async function confirm() {if(!file||!plan)return;setBusy(true);setMessage('');try {const response=await confirmProductUpload(form(),plan.digest);if(response.ok){setResult(response.counts);setPlan(null);setFile(null);setSheet('');setSheets([]);}else setMessage(response.message);}catch{setMessage('Import failed. Check the data before retrying.');}finally{setBusy(false);}}
  const link=`data:text/csv;charset=utf-8,${encodeURIComponent(template)}`;
  return <div className="space-y-5"><section className="panel p-6"><h2 className="text-lg font-semibold">1. Upload CSV or XLSX</h2><p className="mt-2 text-sm text-slate-600">Upload the BIXOLON pricing workbook directly or use the import template. Select a worksheet to review. STANDARD is used as the base price where available; MSRP, reseller, and distributor prices remain separate.</p><p className="mt-2 text-sm text-slate-600">For template files, use one row per part number and include model and part_number. Blank cells leave existing values unchanged. If a worksheet has no currency, enter it below. Price units in template files: EACH, CASE, BOX, or ROLL.</p><a className="mt-3 inline-block text-xs font-medium text-slate-600 underline hover:text-orange-800" href={link} download="products-pricing-template.csv">Download import template</a><p className="mt-2 text-xs text-slate-600">The template works with CSV or XLSX. File limits: CSV 2 MB; XLSX 4 MB and 5,000 rows. Only the selected worksheet is imported.</p><div className="mt-4 flex flex-wrap items-center gap-3"><label className="btn-secondary cursor-pointer" htmlFor="product-import-file">Choose CSV or XLSX</label><input id="product-import-file" aria-label="CSV or XLSX file" className="sr-only" type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>load(e.target.files?.[0])}/><span className="text-sm text-slate-600">{file?.name ?? 'No file chosen'}</span><button className="btn-primary" disabled={!file||busy} onClick={()=>void preview()}>Preview changes</button></div><label className="mt-3 block text-sm">Worksheet currency, if not shown in the file <input className="ml-2 w-24 rounded border border-slate-300 p-2 uppercase" aria-label="Workbook currency" maxLength={3} placeholder="e.g. USD" value={currency} onChange={e=>{setCurrency(e.target.value.toUpperCase());setPlan(null);setMessage('');}}/></label>{sheets.length>1&&<label className="mt-3 block text-sm">Worksheet <select className="ml-2 rounded border border-slate-300 p-2" value={sheet} onChange={e=>{setSheet(e.target.value);setPlan(null);setMessage('');}}><option value="">Choose a worksheet</option>{sheets.map(name=><option key={name} value={name}>{name}</option>)}</select></label>}</section>
  {message&&<p role="alert" className="rounded border border-red-300 bg-red-50 p-4 text-sm text-red-900">{message}</p>}
  {result&&<section className="panel p-6"><h2 className="text-lg font-semibold">Import complete</h2><p className="mt-2 text-sm">The reviewed changes have been saved.</p><Counts counts={result}/></section>}
  {plan&&<section className="panel p-6"><h2 className="text-lg font-semibold">2. Review proposed changes</h2><Counts counts={plan.counts}/>{plan.errors.length>0&&<ul className="mt-4 list-disc pl-5 text-sm text-red-800">{plan.errors.map(error=><li key={error}>{error}</li>)}</ul>}<div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-2">Line</th><th className="p-2">Part number</th><th className="p-2">Change</th><th className="p-2">Before</th><th className="p-2">After</th><th className="p-2">Messages</th></tr></thead><tbody>{plan.items.map(item=><tr key={item.line} className="border-b align-top"><td className="p-2">{item.line}</td><td className="p-2">{item.label}</td><td className="p-2 font-semibold">{item.classes.join(', ')}</td><td className="p-2"><Values value={item.before}/></td><td className="p-2"><Values value={item.after}/></td><td className="p-2 text-red-800">{item.messages.join(' ')}</td></tr>)}</tbody></table></div><div className="mt-5"><button className="btn-primary" disabled={busy||!plan.digest||!!plan.errors.length||!!plan.counts.errors||!plan.items.length} onClick={()=>void confirm()}>Confirm and apply import</button><p className="mt-2 text-xs text-slate-600">Review the proposed changes before confirming. If CRM records change after preview, review the import again.</p></div></section>}</div>;
}
