import Link from "next/link";
import { notFound } from "next/navigation";
import { Content, PageHeader } from "@/components/shell";
import { CrmStateControl } from "@/components/crm-state-control";
import { forecastLabels, partyLabels } from "@/lib/crm-validation";
import { lineTotal, opportunityTotal, weightedValue } from "@/lib/opportunities";
import { prisma } from "@/lib/prisma";
export const dynamic = "force-dynamic";
export default async function OpportunityPage({ params }: { params: Promise<{ id: string }> }) {
  const id = Number((await params).id); if (!Number.isSafeInteger(id) || id <= 0) notFound();
  const o = await prisma.opportunity.findUnique({ where: { id }, include: { stage: true, owner: true, participants: { include: { account: true, roles: true } }, products: { include: { product: true }, orderBy: { id: "asc" } } } }); if (!o) notFound();
  const total = opportunityTotal(o.products), probability = o.probability ?? o.stage.probability;
  return <Content><PageHeader eyebrow="Opportunities" title={o.name} description={`Opportunity #${id}`} action={<div className="flex gap-2"><Link className="btn-secondary" href="/opportunities">All opportunities</Link>{!o.archivedAt && <Link className="btn-primary" href={`/opportunities/${id}/edit`}>Edit opportunity</Link>}</div>}/>
    <div className="panel mb-5 flex flex-wrap items-center gap-3 p-5"><span className="rounded bg-slate-100 px-3 py-1 text-sm">{o.archivedAt ? "Archived" : "Current"}</span><CrmStateControl kind="opportunity" id={id} state={o.archivedAt ? "archived" : "active"}/></div>
    <div className="mb-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="panel p-5"><div className="label">Total estimated value</div><div className="text-xl font-semibold">{o.currencyCode} {total.toFixed(2)}</div></div><div className="panel p-5"><div className="label">Weighted value</div><div className="text-xl font-semibold">{o.currencyCode} {weightedValue(total, probability).toFixed(2)}</div></div><div className="panel p-5"><div className="label">Sales stage</div><div className="text-lg font-semibold">{o.stage.name}</div></div><div className="panel p-5"><div className="label">Probability</div><div className="text-lg font-semibold">{probability}%{o.probability !== null ? " override" : " stage"}</div></div></div>
    <div className="panel mb-5 p-6"><dl className="grid gap-5 sm:grid-cols-2"><div><dt className="label">Forecast category</dt><dd>{o.forecastCategory ? forecastLabels[o.forecastCategory] : "Unspecified"}</dd></div><div><dt className="label">Expected close date</dt><dd>{o.expectedCloseDate?.toISOString().slice(0, 10) ?? "—"}</dd></div><div><dt className="label">Owner</dt><dd>{o.owner ? `${o.owner.firstName} ${o.owner.lastName}` : "Unassigned"}</dd></div><div><dt className="label">Currency</dt><dd>{o.currencyCode}</dd></div></dl>{o.description && <div className="mt-5"><div className="label">Description</div><p className="whitespace-pre-wrap text-sm">{o.description}</p></div>}</div>
    <section className="panel mb-5 p-6"><h2 className="mb-4 text-lg font-semibold">Participating accounts and roles</h2><div className="space-y-3">{o.participants.map((p) => <div key={p.accountId} className="flex flex-wrap items-center gap-3 border-b pb-3 last:border-0"><Link className="font-medium text-orange-800" href={`/accounts/${p.accountId}`}>{p.account.name}</Link><span className="text-sm text-slate-600">{p.roles.map((r) => partyLabels[r.role]).join(", ") || "No role"}</span></div>)}</div></section>
    <section className="panel overflow-x-auto"><h2 className="p-6 text-lg font-semibold">Products</h2><table className="w-full min-w-[600px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Product</th><th className="px-5 py-3">Quantity</th><th className="px-5 py-3">Unit price</th><th className="px-5 py-3 text-right">Line total</th></tr></thead><tbody className="divide-y">{o.products.filter((line) => !line.archivedAt).map((line) => <tr key={line.id}><td className="px-5 py-4"><Link className="text-orange-800" href={`/products/${line.productId}/edit`}>{line.product.name}</Link><span className="ml-2 text-slate-500">{line.product.sku}</span></td><td className="px-5 py-4">{line.quantity}</td><td className="px-5 py-4">{o.currencyCode} {line.estimatedUnitPrice.toFixed(2)}</td><td className="px-5 py-4 text-right">{o.currencyCode} {lineTotal(line).toFixed(2)}</td></tr>)}</tbody></table>{!o.products.some((line) => !line.archivedAt) && <p className="p-6 text-sm text-slate-500">No products added yet.</p>}</section>
  </Content>;
}
